classdef About < matlab.apps.AppBase
    % App Designer style replacement for legacy GUIDE About dialog.

    properties (Access = public)
        UIFigure            matlab.ui.Figure
        TitleLabel          matlab.ui.control.Label
        DetailsTextArea     matlab.ui.control.TextArea
        WebsiteButton       matlab.ui.control.Button
        GitHubButton        matlab.ui.control.Button
        CloseButton         matlab.ui.control.Button
    end

    methods (Access = private)
        function openWebsite(~, ~, ~)
            web('https://www.mingsongli.com/', '-browser');
        end

        function openGitHub(~, ~, ~)
            web('https://github.com/mingsongli/acycle', '-browser');
        end

        function closeApp(app, ~, ~)
            delete(app);
        end

        function createComponents(app)
            app.UIFigure = uifigure( ...
                'Name', 'Acycle: Copyright', ...
                'Position', [100 100 650 460], ...
                'Resize', 'on', ...
                'Color', [1 1 1]);

            app.TitleLabel = uilabel(app.UIFigure, ...
                'Text', sprintf('%s\n%s', ...
                'DYnamic Noise after Orbital Tuning (DYNOT) model', ...
                'version 0.1 (May 1, 2017)'), ...
                'Position', [40 380 570 52], ...
                'FontSize', 14, ...
                'FontWeight', 'bold', ...
                'HorizontalAlignment', 'left');

            details = { ...
                'The dynamic sea-level model is described:'; ...
                'Li, M., Hinnov, L.A., Huang, C., Ogg, J.G., 2018. Sedimentary noise and'; ...
                'sea levels linked to land-ocean water exchange and obliquity forcing.'; ...
                'Nature Communications 9, 1004. doi: 10.1038/s41467-018-03454-y'; ...
                ''; ...
                'Script by:'; ...
                'Mingsong Li'; ...
                'Department of Geosciences, Penn State'; ...
                '410 Deike Bldg, University Park, PA 16802, USA'; ...
                'Emails: mul450@psu.edu; limingsonglms@gmail.com'; ...
                'Website: www.mingsongli.com'; ...
                ''; ...
                'Update may be found at:'; ...
                'https://www.mingsongli.com'; ...
                'https://github.com/mingsongli/acycle' ...
                };

            app.DetailsTextArea = uitextarea(app.UIFigure, ...
                'Value', details, ...
                'Position', [40 80 570 285], ...
                'Editable', 'off', ...
                'FontSize', 12, ...
                'BackgroundColor', [1 1 1]);

            app.WebsiteButton = uibutton(app.UIFigure, 'push', ...
                'Text', 'Website', ...
                'Position', [40 28 120 32], ...
                'ButtonPushedFcn', @(src,event)openWebsite(app, src, event));

            app.GitHubButton = uibutton(app.UIFigure, 'push', ...
                'Text', 'GitHub', ...
                'Position', [172 28 120 32], ...
                'ButtonPushedFcn', @(src,event)openGitHub(app, src, event));

            app.CloseButton = uibutton(app.UIFigure, 'push', ...
                'Text', 'Close', ...
                'Position', [490 28 120 32], ...
                'ButtonPushedFcn', @(src,event)closeApp(app, src, event));
        end
    end

    methods (Access = public)
        function app = About(varargin)
            %#ok<INUSD> Preserve external calling compatibility.
            createComponents(app);
            registerApp(app, app.UIFigure);

            if nargout == 0
                clear app
            end
        end

        function delete(app)
            if ~isempty(app.UIFigure) && isvalid(app.UIFigure)
                delete(app.UIFigure);
            end
        end
    end
end
