function app = settingsGUI(varargin)
%SETTINGSGUI Acycle interface settings for font size and language.
%
% This dialog intentionally uses classic figure/uicontrol components. They
% avoid the CEF figure host involved in the Windows standalone toFront
% failure while remaining compatible with MATLAB R2023b through R2026a.

context = struct();
if nargin > 0 && isstruct(varargin{1})
    context = varargin{1};
end
if nargin > 1
    settingsPath = varargin{2};
    if isstring(settingsPath) && isscalar(settingsPath)
        settingsPath = char(settingsPath);
    end
else
    settingsPath = ac_user_settings('path');
end

existingFigure = findall(groot,'Type','figure', ...
    'Tag','AcycleSettingsFigure');
if ~isempty(existingFigure)
    app = getappdata(existingFigure(1),'AcycleSettingsHandles');
    try
        set(existingFigure(1),'Visible','on');
        drawnow;
    catch
    end
    if nargout == 0
        clear app
    end
    return
end

fontSizeValues = ac_user_settings('fontSizes');
fontTickLabels = {'Small (10 pt)','Normal (11.5 pt)', ...
    'Large (12.5 pt)','Extra Large (13.5 pt)'};
languageNames = {'English','中文简体','中文繁體','Deutsch', ...
    'Español','Français','Italiano','Nederlands','rumuński', ...
    'Polski','Português','Português do Brasil','Русский', ...
    'Türk','українська','हिंदी','عربي','やまと','বাংলা','한국인'};
languageValues = [0,1,2,10,4,5,12,17,16,15,9,19, ...
    8,13,14,3,6,11,7,18];
currentSettings = ac_user_settings('load',settingsPath);
[~,fontIndex] = min(abs(fontSizeValues-currentSettings.fontSize));
languageIndex = find(languageValues == currentSettings.languageChoice,1);
if isempty(languageIndex)
    languageIndex = 1;
end

dialogFigure = figure( ...
    'Name','Acycle: Setting', ...
    'NumberTitle','off', ...
    'MenuBar','none', ...
    'ToolBar','none', ...
    'DockControls','off', ...
    'Resize','off', ...
    'WindowStyle','modal', ...
    'Color',get(groot,'DefaultUicontrolBackgroundColor'), ...
    'Units','pixels', ...
    'Position',dialogPosition(context), ...
    'Tag','AcycleSettingsFigure', ...
    'Visible','off');

tabGroup = uitabgroup('Parent',dialogFigure, ...
    'Units','normalized', ...
    'Position',[0.025 0.18 0.95 0.79]);
fontSizeTab = uitab(tabGroup,'Title','Font Size');
languageTab = uitab(tabGroup,'Title','Language');

uicontrol(fontSizeTab, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',[0.10 0.76 0.80 0.12], ...
    'String','Choose the interface font size', ...
    'FontUnits','points', ...
    'FontSize',12, ...
    'HorizontalAlignment','center');

fontSizeSlider = uicontrol(fontSizeTab, ...
    'Style','slider', ...
    'Units','normalized', ...
    'Position',[0.10 0.52 0.80 0.10], ...
    'Min',1, ...
    'Max',4, ...
    'Value',fontIndex, ...
    'SliderStep',[1/3 1/3], ...
    'Callback',@onFontSizeChanged);

labelCenters = [0.10 0.3667 0.6333 0.90];
labelWidth = 0.24;
for tickIndex = 1:numel(fontTickLabels)
    uicontrol(fontSizeTab, ...
        'Style','text', ...
        'Units','normalized', ...
        'Position',[labelCenters(tickIndex)-labelWidth/2,0.34,labelWidth,0.10], ...
        'String',fontTickLabels{tickIndex}, ...
        'FontUnits','points', ...
        'FontSize',10, ...
        'HorizontalAlignment','center');
end

selectedFontLabel = uicontrol(fontSizeTab, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',[0.10 0.15 0.80 0.10], ...
    'String','', ...
    'FontUnits','points', ...
    'FontSize',12, ...
    'HorizontalAlignment','center');

uicontrol(languageTab, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',[0.10 0.64 0.80 0.12], ...
    'String','Select language', ...
    'FontUnits','points', ...
    'FontSize',12, ...
    'HorizontalAlignment','center');

languageDropDown = uicontrol(languageTab, ...
    'Style','popupmenu', ...
    'Units','normalized', ...
    'Position',[0.10 0.42 0.80 0.13], ...
    'String',languageNames, ...
    'Value',languageIndex, ...
    'FontUnits','points', ...
    'FontSize',12, ...
    'BackgroundColor','white', ...
    'Enable','off');

okButton = uicontrol(dialogFigure, ...
    'Style','pushbutton', ...
    'Units','normalized', ...
    'Position',[0.81 0.04 0.165 0.10], ...
    'String','OK', ...
    'FontUnits','points', ...
    'FontSize',12, ...
    'Callback',@onOKButtonPushed);

app = struct( ...
    'UIFigure',dialogFigure, ...
    'TabGroup',tabGroup, ...
    'FontSizeTab',fontSizeTab, ...
    'LanguageTab',languageTab, ...
    'FontSizeSlider',fontSizeSlider, ...
    'SelectedFontLabel',selectedFontLabel, ...
    'LanguageDropDown',languageDropDown, ...
    'OKButton',okButton, ...
    'FontSizeTicks',1:4, ...
    'FontSizeTickLabels',{fontTickLabels}, ...
    'LanguageValues',languageValues);
setappdata(dialogFigure,'AcycleSettingsHandles',app);
updateFontSizeLabel(fontIndex);
set(dialogFigure,'Visible','on');

if nargout == 0
    clear app
end

    function onFontSizeChanged(~,~)
        index = min(max(1,round(get(fontSizeSlider,'Value'))), ...
            numel(fontSizeValues));
        set(fontSizeSlider,'Value',index);
        updateFontSizeLabel(index);
    end

    function updateFontSizeLabel(fontIndexValue)
        set(selectedFontLabel,'String',sprintf( ...
            'Selected font size: %g pt',fontSizeValues(fontIndexValue)));
    end

    function onOKButtonPushed(~,~)
        selectedFontIndex = min(max(1, ...
            round(get(fontSizeSlider,'Value'))),numel(fontSizeValues));
        selectedLanguageIndex = min(max(1, ...
            round(get(languageDropDown,'Value'))),numel(languageValues));
        fontSize = fontSizeValues(selectedFontIndex);
        languageChoice = languageValues(selectedLanguageIndex);

        try
            ac_user_settings('save',fontSize,languageChoice,settingsPath);
        catch exception
            errordlg(sprintf( ...
                'Acycle could not save the settings.\n\n%s', ...
                exception.message),'Settings Error','modal');
            return
        end

        set(dialogFigure,'Visible','off');
        try
            runRestart(context);
        catch exception
            if isgraphics(dialogFigure)
                set(dialogFigure,'Visible','on');
            end
            errordlg(sprintf( ...
                'Acycle could not restart.\n\n%s', ...
                exception.message),'Restart Error','modal');
            return
        end
        if isgraphics(dialogFigure)
            delete(dialogFigure);
        end
    end
end

function position = dialogPosition(context)
width = 560;
height = 310;
oldUnits = get(groot,'Units');
unitsCleanup = onCleanup(@()set(groot,'Units',oldUnits));
set(groot,'Units','pixels');
screenPosition = get(groot,'ScreenSize');

x = screenPosition(1)+(screenPosition(3)-width)/2;
y = screenPosition(2)+(screenPosition(4)-height)/2;
if isfield(context,'acfigmain')
    mainFigure = context.acfigmain;
    if ~isempty(mainFigure) && all(isgraphics(mainFigure))
        try
            mainPosition = getpixelposition(mainFigure,true);
            x = mainPosition(1)+(mainPosition(3)-width)/2;
            y = mainPosition(2)+(mainPosition(4)-height)/2;
        catch
        end
    end
end

xMaximum = screenPosition(1)+screenPosition(3)-width;
yMaximum = screenPosition(2)+screenPosition(4)-height;
x = min(max(x,screenPosition(1)),max(screenPosition(1),xMaximum));
y = min(max(y,screenPosition(2)),max(screenPosition(2),yMaximum));
position = round([x,y,width,height]);
clear unitsCleanup
end

function runRestart(context)
if isfield(context,'SettingsRestartFcn') && ...
        isa(context.SettingsRestartFcn,'function_handle')
    context.SettingsRestartFcn();
    return
end

closeMainACFigures(context);
pause(0.1);
if isdeployed || exist('ac','file') == 2
    ac;
else
    AC;
end
end

function closeMainACFigures(context)
mainFigures = findall(groot,'Type','figure','Tag','acfigmain');
if isfield(context,'acfigmain')
    candidate = context.acfigmain;
    if ~isempty(candidate) && all(isgraphics(candidate)) && ...
            (isempty(mainFigures) || ~any(mainFigures == candidate))
        mainFigures(end+1) = candidate;
    end
end
for index = 1:numel(mainFigures)
    try
        close(mainFigures(index));
    catch
        try
            delete(mainFigures(index));
        catch
        end
    end
end
end
