function [result,meta] = acycleSedimentationRateAgeModel( ...
        data,depthUnit,firstAgeKyr)
%ACYCLESEDIMENTATIONRATEAGEMODEL Integrate depth-dependent rates to age.
%   [RESULT,META] = ACYCLESEDIMENTATIONRATEAGEMODEL(DATA,DEPTHUNIT,
%   FIRSTAGEKYR) converts a strict N-by-2 [depth,sedimentation_rate] series
%   into [depth,age_kyr]. DATA must be a finite, real SINGLE or DOUBLE
%   matrix with at least two rows, strictly increasing unique depths, and a
%   positive rate in every row. Rows are not sorted, removed, merged, or
%   interpolated.
%
%   DEPTHUNIT is 'm', 'dm', 'cm', 'mm', 'ft', or 'km'. Rates are always
%   interpreted as cm/kyr. FIRSTAGEKYR is a finite real scalar. For each
%   interval i-1 -> i, the left-endpoint rate is used exactly:
%
%       age(i) = age(i-1) + depth_delta_in_cm/rate(i-1).
%
%   Thus the final input rate is validated as positive but is not used by
%   any interval. The historical GUI call DATA,'m',0 is equivalent to
%   age(i)=age(i-1)+100*(depth(i)-depth(i-1))/rate(i-1).
%
%   RESULT is a finite DOUBLE N-by-2 matrix. Positive physical increments
%   that underflow, overflow, or cannot increase a large accumulated age at
%   DOUBLE precision are rejected rather than silently flattened. No file
%   I/O, graphics, dialogs, current-directory or path changes, root-state
%   changes, base-workspace assignment, or random-number generation occurs.

narginchk(3,3);

maximumInputRows = 1e6;
if ~(isa(data,'double') || isa(data,'single')) || ~isreal(data) || ...
        ~ismatrix(data) || size(data,2) ~= 2
    error('Acycle:SedRateAgeModel:InvalidData', ...
        ['DATA must be a real SINGLE or DOUBLE N-by-2 matrix with depth ', ...
         'in column 1 and sedimentation rate in column 2.']);
end
inputRows = size(data,1);
if inputRows < 2
    error('Acycle:SedRateAgeModel:TooFewRows', ...
        'DATA must contain at least two rows.');
end
if inputRows > maximumInputRows
    error('Acycle:SedRateAgeModel:InputRowLimitExceeded', ...
        'DATA exceeds the fixed maximum of %.17g input rows.', ...
        maximumInputRows);
end
if any(~isfinite(data(:)))
    error('Acycle:SedRateAgeModel:NonfiniteData', ...
        'Every DATA depth and sedimentation rate must be finite.');
end

[depthUnit,depthToCentimetres] = normalizeDepthUnit(depthUnit);
if ~(isnumeric(firstAgeKyr) && ~islogical(firstAgeKyr) && ...
        isreal(firstAgeKyr) && isscalar(firstAgeKyr) && ...
        isfinite(firstAgeKyr))
    error('Acycle:SedRateAgeModel:InvalidFirstAge', ...
        'FIRSTAGEKYR must be a finite real numeric scalar.');
end
firstAgeKyr = double(firstAgeKyr);

working = full(double(data));
depth = working(:,1);
rate = working(:,2);
depthSpacing = diff(depth);
if any(depthSpacing <= 0)
    error('Acycle:SedRateAgeModel:DepthNotStrictlyIncreasing', ...
        ['DATA(:,1) must already be sorted, contain no duplicates, and ', ...
         'be strictly increasing.']);
end
if any(~isfinite(depthSpacing))
    error('Acycle:SedRateAgeModel:UnrepresentableDepthSpacing', ...
        'Every depth spacing must be representable as a finite DOUBLE.');
end
if any(rate <= 0)
    error('Acycle:SedRateAgeModel:NonpositiveRate', ...
        ['Every sedimentation rate, including the validated but unused ', ...
         'final-row rate, must be positive.']);
end

age = zeros(inputRows,1);
age(1) = firstAgeKyr;
ageIncrement = zeros(inputRows-1,1);
for row = 2:inputRows
    interval = row-1;
    ageIncrement(interval) = intervalAgeIncrement( ...
        depthSpacing(interval),depthToCentimetres,rate(interval));
    candidateAge = age(interval)+ageIncrement(interval);
    if ~isfinite(candidateAge)
        error('Acycle:SedRateAgeModel:CumulativeAgeOverflow', ...
            'Cumulative age overflowed at output row %d.',row);
    end
    if candidateAge <= age(interval)
        error('Acycle:SedRateAgeModel:UnrepresentableCumulativeAge', ...
            ['The positive age increment at output row %d cannot increase ', ...
             'the accumulated age at DOUBLE precision.'],row);
    end
    age(row) = candidateAge;
end

result = [depth,age];
if ~isequal(size(result),[inputRows,2]) || ~isa(result,'double') || ...
        ~isreal(result) || any(~isfinite(result(:)))
    error('Acycle:SedRateAgeModel:InvalidOutput', ...
        ['The sedimentation-rate age model must be a finite real DOUBLE ', ...
         'N-by-2 matrix.']);
end

meta = struct( ...
    'version','sedimentation-rate-age-model-v1', ...
    'input_policy','strict-finite-real-two-column-unique-increasing', ...
    'input_rows',inputRows, ...
    'input_columns',2, ...
    'output_rows',inputRows, ...
    'output_columns',2, ...
    'result_columns',{{'depth','age_kyr'}}, ...
    'depth_unit',depthUnit, ...
    'depth_to_cm_factor',depthToCentimetres, ...
    'rate_unit','cm_per_kyr', ...
    'age_unit','kyr', ...
    'first_age_kyr',firstAgeKyr, ...
    'integration_rule','piecewise-constant-left-endpoint-rate', ...
    'interval_formula','delta_depth_cm/left_endpoint_rate_cm_per_kyr', ...
    'rate_rows_used',[1,inputRows-1], ...
    'last_rate_validated',true, ...
    'last_rate_used',false, ...
    'depth_start',depth(1), ...
    'depth_end',depth(end), ...
    'depth_spacing_minimum',min(depthSpacing), ...
    'depth_spacing_maximum',max(depthSpacing), ...
    'rate_minimum',min(rate), ...
    'rate_maximum',max(rate), ...
    'age_start_kyr',age(1), ...
    'age_end_kyr',age(end), ...
    'age_increment_minimum_kyr',min(ageIncrement), ...
    'age_increment_maximum_kyr',max(ageIncrement), ...
    'sorted',false, ...
    'removed_rows',0, ...
    'interpolated',false, ...
    'toolbox_dependency','MATLAB_only', ...
    'maximum_input_rows',maximumInputRows, ...
    'file_io',false, ...
    'graphics',false, ...
    'random_number_generation',false, ...
    'side_effect_policy','none');
end

function increment = intervalAgeIncrement( ...
        depthDifference,depthToCentimetres,rate)
depthDifferenceCentimetres = depthDifference*depthToCentimetres;
if isfinite(depthDifferenceCentimetres)
    increment = depthDifferenceCentimetres/rate;
else
    % Preserve a representable quotient when converting an enormous finite
    % depth difference to centimetres would overflow before division by a
    % correspondingly enormous rate.
    increment = (depthDifference/rate)*depthToCentimetres;
end
if ~(isfinite(increment) && increment > 0)
    error('Acycle:SedRateAgeModel:UnrepresentableAgeIncrement', ...
        ['Every positive depth interval and rate must produce a finite, ', ...
         'strictly positive age increment.']);
end
end

function [unit,factor] = normalizeDepthUnit(unit)
if isstring(unit) && isscalar(unit)
    unit = char(unit);
end
if ~(ischar(unit) && isrow(unit) && ~isempty(unit))
    error('Acycle:SedRateAgeModel:InvalidDepthUnit', ...
        'DEPTHUNIT must be ''m'', ''dm'', ''cm'', ''mm'', ''ft'', or ''km''.');
end
unit = lower(strtrim(unit));
switch unit
    case 'm'
        factor = 100;
    case 'dm'
        factor = 10;
    case 'cm'
        factor = 1;
    case 'mm'
        factor = 0.1;
    case 'ft'
        factor = 30.48;
    case 'km'
        factor = 1e5;
    otherwise
        error('Acycle:SedRateAgeModel:InvalidDepthUnit', ...
            ['DEPTHUNIT must be ''m'', ''dm'', ''cm'', ''mm'', ', ...
             '''ft'', or ''km''.']);
end
end
