function [result,meta] = acycleSpectralMoments(data,options)
%ACYCLESPECTRALMOMENTS Strict deterministic sliding spectral moments.
%   [RESULT,META] = ACYCLESPECTRALMOMENTS(DATA,OPTIONS) calculates mean
%   frequency and bandwidth in sliding windows of a finite, real, full
%   SINGLE or DOUBLE N-by-2 series [coordinate,value]. Coordinates must be
%   strictly increasing and near-uniform within the fixed relative spacing
%   tolerance 1e-5. Rows are never sorted, removed, merged, or interpolated.
%
%   OPTIONS is a scalar structure containing exactly these required fields:
%     window_length        positive physical first-to-last window span
%     step_length          positive physical displacement between windows
%     zero_padding_factor  positive integer minimum NFFT multiplier
%     edge_padding         'none' or 'zero'
%
%   WINDOW_LENGTH/DT is rounded to the nearest positive number of sampling
%   intervals (half ties away from zero), then one is added to obtain the
%   number of samples. At least two intervals (three samples) are required.
%   STEP_LENGTH/DT is rounded by the same rule and must yield at least one
%   sample; it is never silently clamped. Requested and effective lengths,
%   ratios, and quantization errors are returned in META.
%
%   NFFT starts as ZERO_PADDING_FACTOR*WINDOW_SAMPLES. If that product is
%   odd, one point is added so the one-sided periodogram contains the
%   physical Nyquist bin exactly. Each globally mean-centred window is
%   linearly detrended against sample ordinal, scaled without changing its
%   spectral moments, and evaluated from DC through physical Nyquist.
%   Windows with zero or numerically unresolvable detrended power fail
%   explicitly rather than returning NaN or a rounding-noise spectrum.
%
%   EDGE_PADDING='zero' adds synthetic zero values after global mean
%   centring. It adds FLOOR(WINDOW_INTERVALS/2) samples on the left and
%   CEIL(WINDOW_INTERVALS/2) on the right, once only, and retains window
%   centres inside the original coordinate domain. Every reported centre
%   is the arithmetic mean of that window's actual first and last
%   coordinates.
%
%   RESULT is a DOUBLE matrix with columns
%     [window_center,mean_frequency,bandwidth].
%   The function performs no file I/O, graphics, dialogs, folder or path
%   changes, random-number generation, or base-workspace assignment.

narginchk(2,2);
limits = resourceLimits();
inputClass = class(data);
contract = validateSeries(data,limits);
options = validateOptions(options);

working = full(double(data));
coordinates = working(:,1);
values = working(:,2);
inputRows = size(working,1);
coordinateStart = coordinates(1);
coordinateEnd = coordinates(end);
coordinateSpan = coordinateEnd-coordinateStart;

[windowIntervals,windowSamples,effectiveWindowLength,windowRatio] = ...
    resolveWindow(options.window_length,contract.sample_interval, ...
    coordinateSpan,inputRows);
[stepSamples,effectiveStepLength,stepRatio] = resolveStep( ...
    options.step_length,contract.sample_interval,coordinateSpan);
[nominalNfft,nfft] = resolveNfft( ...
    options.zero_padding_factor,windowSamples,limits);

[preparedCoordinates,preparedValues,leftPadding,rightPadding, ...
    valueScale,normalizedGlobalMean] = prepareSeries( ...
    coordinates,values,contract.sample_interval,windowIntervals, ...
    options.edge_padding);

lastStart = numel(preparedValues)-windowSamples+1;
if lastStart < 1
    error('Acycle:SpectralMoments:WindowExceedsPreparedData', ...
        'The effective window is longer than the prepared series.');
end
candidateStarts = (1:stepSamples:lastStart)';
candidateEnds = candidateStarts+windowSamples-1;
candidateCenters = preparedCoordinates(candidateStarts)+ ...
    (preparedCoordinates(candidateEnds)- ...
    preparedCoordinates(candidateStarts))/2;
centerCropTolerance = max( ...
    64*eps(max(1,max(abs([coordinateStart,coordinateEnd])))), ...
    64*eps(max(1,abs(contract.sample_interval))));
insideOriginalDomain = ...
    candidateCenters >= coordinateStart-centerCropTolerance & ...
    candidateCenters <= coordinateEnd+centerCropTolerance;
startIndices = candidateStarts(insideOriginalDomain);
endIndices = candidateEnds(insideOriginalDomain);
centers = candidateCenters(insideOriginalDomain);
centers(abs(centers-coordinateStart) <= centerCropTolerance) = ...
    coordinateStart;
centers(abs(centers-coordinateEnd) <= centerCropTolerance) = ...
    coordinateEnd;

windowCount = numel(startIndices);
if windowCount < 1
    error('Acycle:SpectralMoments:NoRetainedWindows', ...
        ['The requested window, step, and edge policy retain no window ', ...
         'centre inside the original coordinate domain.']);
end
if windowCount > limits.maximum_window_count
    error('Acycle:SpectralMoments:WindowCountLimitExceeded', ...
        ['The request produces %d windows; the fixed maximum is %d. ', ...
         'Increase STEP_LENGTH or shorten the input.'], ...
        windowCount,limits.maximum_window_count);
end
outputElements = double(windowCount)*3;
if ~isfinite(outputElements) || ...
        outputElements > limits.maximum_output_elements
    error('Acycle:SpectralMoments:OutputElementLimitExceeded', ...
        ['The result would contain %.17g values; the fixed maximum is ', ...
         '%.17g.'],outputElements,limits.maximum_output_elements);
end
fftWorkUnits = double(windowCount)*double(nfft)* ...
    max(1,ceil(log2(double(nfft))));
if ~isfinite(fftWorkUnits) || ...
        fftWorkUnits > limits.maximum_fft_work_units
    error('Acycle:SpectralMoments:FFTWorkLimitExceeded', ...
        ['The request requires %.17g fixed FFT work units; the maximum ', ...
         'is %.17g. Increase STEP_LENGTH, reduce WINDOW_LENGTH or ', ...
         'ZERO_PADDING_FACTOR, or shorten the input.'], ...
        fftWorkUnits,limits.maximum_fft_work_units);
end

physicalNyquist = contract.physical_nyquist;
samplingFrequency = 2*physicalNyquist;
frequencyBinCount = nfft/2+1;
meanFrequency = zeros(windowCount,1);
bandwidth = zeros(windowCount,1);
totalPowers = zeros(windowCount,1);
detrendedPeakMagnitudes = zeros(windowCount,1);
inputEpsilon = double(eps(inputClass));
residualResolutionMultiplier = 16;
frequency = [];

for windowIndex = 1:windowCount
    segment = preparedValues(startIndices(windowIndex): ...
        endIndices(windowIndex));
    [residual,detrendedPeakMagnitudes(windowIndex)] = ...
        linearDetrendSegment(segment,inputEpsilon, ...
        residualResolutionMultiplier,windowIndex);
    [power,frequencyCurrent] = periodogram( ...
        residual,[],nfft,samplingFrequency,'onesided');
    power = power(:);
    frequencyCurrent = frequencyCurrent(:);
    validatePeriodogram(power,frequencyCurrent,nfft, ...
        physicalNyquist,windowIndex);
    frequencyCurrent(end) = physicalNyquist;
    if isempty(frequency)
        frequency = frequencyCurrent;
    elseif ~isequal(frequencyCurrent,frequency)
        error('Acycle:SpectralMoments:InconsistentFrequencyGrid', ...
            'Window %d produced a different periodogram frequency grid.', ...
            windowIndex);
    end

    totalPower = sum(power);
    if ~(isfinite(totalPower) && totalPower > 0)
        error('Acycle:SpectralMoments:InvalidTotalPower', ...
            ['Window %d has zero or nonfinite one-sided periodogram ', ...
             'power after linear detrending.'],windowIndex);
    end
    weights = power/totalPower;
    if any(~isfinite(weights)) || any(weights < 0) || ...
            ~(isfinite(sum(weights)) && sum(weights) > 0)
        error('Acycle:SpectralMoments:InvalidSpectralWeights', ...
            'Window %d produced invalid normalized spectral weights.', ...
            windowIndex);
    end
    normalizedFrequency = frequency/physicalNyquist;
    meanNormalized = sum(normalizedFrequency.*weights);
    varianceNormalized = sum( ...
        (normalizedFrequency-meanNormalized).^2.*weights);
    varianceTolerance = 128*eps(max(1,abs(meanNormalized)));
    if varianceNormalized < 0 && ...
            varianceNormalized >= -varianceTolerance
        varianceNormalized = 0;
    end
    if ~(isfinite(meanNormalized) && meanNormalized >= 0 && ...
            meanNormalized <= 1+varianceTolerance && ...
            isfinite(varianceNormalized) && varianceNormalized >= 0)
        error('Acycle:SpectralMoments:InvalidMoment', ...
            'Window %d produced an invalid normalized spectral moment.', ...
            windowIndex);
    end
    meanNormalized = min(meanNormalized,1);
    meanFrequency(windowIndex) = meanNormalized*physicalNyquist;
    bandwidth(windowIndex) = sqrt(varianceNormalized)*physicalNyquist;
    totalPowers(windowIndex) = totalPower;
end

result = [centers,meanFrequency,bandwidth];
if ~isequal(size(result),[windowCount,3]) || ...
        ~isreal(result) || any(~isfinite(result(:)))
    error('Acycle:SpectralMoments:InvalidOutput', ...
        ['Spectral moments must produce one finite real three-column ', ...
         'result row per retained window.']);
end
if windowCount > 1 && any(diff(result(:,1)) <= 0)
    error('Acycle:SpectralMoments:InvalidOutputCenters', ...
        'Window centres must remain finite and strictly increasing.');
end

actualWindowSpans = preparedCoordinates(endIndices)- ...
    preparedCoordinates(startIndices);
if windowCount > 1
    actualCenterSteps = diff(centers);
    minimumCenterStep = min(actualCenterSteps);
    maximumCenterStep = max(actualCenterSteps);
else
    minimumCenterStep = NaN;
    maximumCenterStep = NaN;
end
frequencyResolution = frequency(2)-frequency(1);
meta = struct( ...
    'version','spectral-moments-v1', ...
    'method','sliding_one_sided_periodogram_spectral_moments', ...
    'input_policy', ...
        'strict_finite_real_full_single_or_double_n_by_2_increasing_near_uniform', ...
    'input_class',inputClass, ...
    'input_rows',inputRows, ...
    'input_columns',2, ...
    'output_rows',windowCount, ...
    'output_columns',3, ...
    'result_columns',{{ ...
        'window_center','mean_frequency','bandwidth'}}, ...
    'coordinate_start',coordinateStart, ...
    'coordinate_end',coordinateEnd, ...
    'coordinate_span',coordinateSpan, ...
    'sample_interval',contract.sample_interval, ...
    'maximum_spacing_error',contract.maximum_spacing_error, ...
    'relative_spacing_departure', ...
        contract.relative_spacing_departure, ...
    'spacing_tolerance',contract.spacing_tolerance, ...
    'physical_nyquist',physicalNyquist, ...
    'requested_window_length',options.window_length, ...
    'window_length_interpretation','first_to_last_coordinate_span', ...
    'window_interval_ratio',windowRatio, ...
    'window_interval_rounding', ...
        'nearest_integer_half_away_from_zero', ...
    'window_intervals',windowIntervals, ...
    'window_samples',windowSamples, ...
    'effective_window_length',effectiveWindowLength, ...
    'window_length_quantization_error', ...
        effectiveWindowLength-options.window_length, ...
    'minimum_actual_window_span',min(actualWindowSpans), ...
    'maximum_actual_window_span',max(actualWindowSpans), ...
    'requested_step_length',options.step_length, ...
    'step_interval_ratio',stepRatio, ...
    'step_interval_rounding','nearest_integer_half_away_from_zero', ...
    'step_samples',stepSamples, ...
    'effective_step_length',effectiveStepLength, ...
    'step_length_quantization_error', ...
        effectiveStepLength-options.step_length, ...
    'minimum_actual_center_step',minimumCenterStep, ...
    'maximum_actual_center_step',maximumCenterStep, ...
    'edge_padding',options.edge_padding, ...
    'edge_padding_application_count',double(~strcmp( ...
        options.edge_padding,'none')), ...
    'left_padding_samples',leftPadding, ...
    'right_padding_samples',rightPadding, ...
    'prepared_rows',numel(preparedValues), ...
    'candidate_window_count',numel(candidateStarts), ...
    'cropped_outside_domain_window_count', ...
        sum(~insideOriginalDomain), ...
    'window_count',windowCount, ...
    'window_start_index_policy','one_plus_k_times_step_samples', ...
    'window_center_semantics', ...
        'arithmetic_mean_of_actual_first_and_last_coordinates', ...
    'center_domain_policy','retain_original_coordinate_domain_only', ...
    'zero_padding_value_policy','zero_after_global_mean_centering', ...
    'value_normalization_scale',valueScale, ...
    'normalized_global_mean',normalizedGlobalMean, ...
    'segment_detrend','linear_least_squares_against_sample_ordinal', ...
    'segment_amplitude_scaling','unit_peak_after_detrend', ...
    'input_epsilon',inputEpsilon, ...
    'residual_resolution_multiplier',residualResolutionMultiplier, ...
    'minimum_detrended_peak_magnitude', ...
        min(detrendedPeakMagnitudes), ...
    'maximum_detrended_peak_magnitude', ...
        max(detrendedPeakMagnitudes), ...
    'spectrum','periodogram_rectangular_one_sided', ...
    'frequency_coverage','dc_through_physical_nyquist_inclusive', ...
    'zero_padding_factor',options.zero_padding_factor, ...
    'nominal_nfft',nominalNfft, ...
    'nfft',nfft, ...
    'nfft_even_policy','add_one_when_nominal_nfft_is_odd', ...
    'frequency_bins',frequencyBinCount, ...
    'frequency_resolution',frequencyResolution, ...
    'calculation_frequency_minimum',frequency(1), ...
    'calculation_frequency_maximum',frequency(end), ...
    'minimum_total_periodogram_power',min(totalPowers), ...
    'maximum_total_periodogram_power',max(totalPowers), ...
    'mean_frequency_formula','sum(frequency.*normalized_power)', ...
    'bandwidth_formula', ...
        'sqrt(sum((frequency-mean_frequency).^2.*normalized_power))', ...
    'interpolated',false, ...
    'sorted',false, ...
    'removed_rows',0, ...
    'toolbox_dependency','Signal Processing Toolbox', ...
    'maximum_input_rows',limits.maximum_input_rows, ...
    'maximum_fft_length',limits.maximum_fft_length, ...
    'maximum_window_count',limits.maximum_window_count, ...
    'maximum_output_elements',limits.maximum_output_elements, ...
    'fft_work_units',fftWorkUnits, ...
    'maximum_fft_work_units',limits.maximum_fft_work_units, ...
    'file_io',false, ...
    'graphics',false, ...
    'dialogs',false, ...
    'current_folder_changes',false, ...
    'path_changes',false, ...
    'random_number_generation',false, ...
    'base_workspace_assignment',false, ...
    'side_effect_policy','none');
end

function limits = resourceLimits()
limits = struct( ...
    'maximum_input_rows',1e6, ...
    'maximum_fft_length',2^20, ...
    'maximum_window_count',1e5, ...
    'maximum_output_elements',3e5, ...
    'maximum_fft_work_units',1e10);
end

function contract = validateSeries(data,limits)
if ~((isa(data,'double') || isa(data,'single')) && ...
        ~issparse(data) && isreal(data) && ismatrix(data) && ...
        size(data,2) == 2)
    error('Acycle:SpectralMoments:InvalidData', ...
        ['DATA must be a full, real SINGLE or DOUBLE N-by-2 matrix ', ...
         '[coordinate,value].']);
end
inputRows = size(data,1);
if inputRows < 3
    error('Acycle:SpectralMoments:InsufficientRows', ...
        'Spectral moments require at least three input rows.');
end
if inputRows > limits.maximum_input_rows
    error('Acycle:SpectralMoments:InputRowLimitExceeded', ...
        'DATA exceeds the fixed maximum of %d input rows.', ...
        limits.maximum_input_rows);
end
if any(~isfinite(data(:)))
    error('Acycle:SpectralMoments:NonfiniteData', ...
        'Every DATA coordinate and value must be finite.');
end

coordinates = double(data(:,1));
spacing = diff(coordinates);
if any(~isfinite(spacing)) || any(spacing <= 0)
    error('Acycle:SpectralMoments:InvalidCoordinate', ...
        'Coordinates must be finite, unique, and strictly increasing.');
end
sampleInterval = median(spacing);
maximumSpacingError = max(abs(spacing-sampleInterval));
relativeSpacingDeparture = maximumSpacingError/sampleInterval;
spacingTolerance = 1e-5;
if ~(isfinite(sampleInterval) && sampleInterval > 0 && ...
        isfinite(relativeSpacingDeparture))
    error('Acycle:SpectralMoments:InvalidSamplingInterval', ...
        'The sampling interval is not representable as a positive DOUBLE.');
end
if relativeSpacingDeparture > spacingTolerance
    error('Acycle:SpectralMoments:UnevenSampling', ...
        ['Relative spacing departure %.17g exceeds the fixed ', ...
         'near-uniform tolerance %.17g.'], ...
        relativeSpacingDeparture,spacingTolerance);
end
physicalNyquist = 1/(2*sampleInterval);
if ~(isfinite(physicalNyquist) && physicalNyquist > 0)
    error('Acycle:SpectralMoments:InvalidPhysicalNyquist', ...
        'The physical Nyquist 1/(2*dt) must be finite and positive.');
end
coordinateSpan = coordinates(end)-coordinates(1);
if ~(isfinite(coordinateSpan) && coordinateSpan > 0)
    error('Acycle:SpectralMoments:InvalidCoordinateSpan', ...
        'The coordinate span must be representable as positive DOUBLE.');
end
contract = struct( ...
    'sample_interval',sampleInterval, ...
    'maximum_spacing_error',maximumSpacingError, ...
    'relative_spacing_departure',relativeSpacingDeparture, ...
    'spacing_tolerance',spacingTolerance, ...
    'physical_nyquist',physicalNyquist);
end

function options = validateOptions(options)
if ~(isstruct(options) && isscalar(options))
    error('Acycle:SpectralMoments:InvalidOptions', ...
        'OPTIONS must be one scalar structure.');
end
required = { ...
    'window_length','step_length','zero_padding_factor','edge_padding'};
provided = fieldnames(options);
missing = setdiff(required,provided);
if ~isempty(missing)
    error('Acycle:SpectralMoments:MissingOption', ...
        'Missing required OPTIONS field: %s.',strjoin(missing,', '));
end
unknown = setdiff(provided,required);
if ~isempty(unknown)
    error('Acycle:SpectralMoments:UnknownOption', ...
        'Unknown OPTIONS field: %s.',strjoin(unknown,', '));
end
options.window_length = positiveFiniteScalar( ...
    options.window_length,'WINDOW_LENGTH');
options.step_length = positiveFiniteScalar( ...
    options.step_length,'STEP_LENGTH');

factor = options.zero_padding_factor;
if ~(isnumeric(factor) && isreal(factor) && isscalar(factor) && ...
        isfinite(factor) && factor >= 1 && factor == fix(factor))
    error('Acycle:SpectralMoments:InvalidZeroPaddingFactor', ...
        'ZERO_PADDING_FACTOR must be a finite positive integer scalar.');
end
options.zero_padding_factor = double(factor);
options.edge_padding = textChoice(options.edge_padding, ...
    {'none','zero'},'EDGE_PADDING');
end

function value = positiveFiniteScalar(value,label)
if ~(isnumeric(value) && isreal(value) && isscalar(value) && ...
        isfinite(value) && value > 0)
    error('Acycle:SpectralMoments:InvalidPhysicalLength', ...
        '%s must be a finite positive numeric scalar.',label);
end
value = double(value);
end

function value = textChoice(value,choices,label)
if isstring(value) && isscalar(value)
    value = char(value);
end
if ~(ischar(value) && isrow(value) && ~isempty(strtrim(value)))
    error('Acycle:SpectralMoments:InvalidEdgePadding', ...
        '%s must be none or zero.',label);
end
value = lower(strtrim(value));
if ~ismember(value,choices)
    error('Acycle:SpectralMoments:InvalidEdgePadding', ...
        '%s must be none or zero.',label);
end
end

function [intervals,samples,effective,ratio] = resolveWindow( ...
        requested,dt,span,inputRows)
if requested > span
    error('Acycle:SpectralMoments:WindowLongerThanSpan', ...
        ['WINDOW_LENGTH %.17g exceeds the input coordinate span ', ...
         '%.17g.'],requested,span);
end
ratio = requested/dt;
if ~(isfinite(ratio) && ratio > 0)
    error('Acycle:SpectralMoments:InvalidWindowRatio', ...
        'WINDOW_LENGTH/DT must be finite and positive.');
end
intervals = round(ratio);
if intervals < 2
    error('Acycle:SpectralMoments:WindowTooShort', ...
        ['WINDOW_LENGTH/DT rounds to %d interval(s); at least two ', ...
         'intervals (three samples) are required.'],intervals);
end
samples = intervals+1;
if samples > inputRows
    error('Acycle:SpectralMoments:WindowSampleCountTooLarge', ...
        ['WINDOW_LENGTH rounds to %d samples, exceeding the %d input ', ...
         'rows.'],samples,inputRows);
end
effective = intervals*dt;
if ~(isfinite(effective) && effective > 0)
    error('Acycle:SpectralMoments:InvalidEffectiveWindow', ...
        'The effective first-to-last window span must be finite and positive.');
end
end

function [samples,effective,ratio] = resolveStep(requested,dt,span)
if requested > span
    error('Acycle:SpectralMoments:StepLongerThanSpan', ...
        'STEP_LENGTH %.17g exceeds the input coordinate span %.17g.', ...
        requested,span);
end
ratio = requested/dt;
if ~(isfinite(ratio) && ratio > 0)
    error('Acycle:SpectralMoments:InvalidStepRatio', ...
        'STEP_LENGTH/DT must be finite and positive.');
end
samples = round(ratio);
if samples < 1
    error('Acycle:SpectralMoments:StepTooShort', ...
        ['STEP_LENGTH/DT rounds to zero samples. Increase STEP_LENGTH; ', ...
         'the reviewed core never silently clamps it to DT.']);
end
effective = samples*dt;
if ~(isfinite(effective) && effective > 0)
    error('Acycle:SpectralMoments:InvalidEffectiveStep', ...
        'The effective step length must be finite and positive.');
end
end

function [nominal,nfft] = resolveNfft(factor,windowSamples,limits)
nominal = factor*double(windowSamples);
if ~(isfinite(nominal) && nominal >= windowSamples && ...
        nominal == fix(nominal))
    error('Acycle:SpectralMoments:InvalidNominalNfft', ...
        'ZERO_PADDING_FACTOR*WINDOW_SAMPLES must be a finite integer.');
end
nfft = nominal+mod(nominal,2);
if ~(isfinite(nfft) && nfft >= windowSamples && nfft == fix(nfft))
    error('Acycle:SpectralMoments:InvalidNfft', ...
        'The even one-sided periodogram NFFT is not representable.');
end
if nfft > limits.maximum_fft_length
    error('Acycle:SpectralMoments:FFTLengthLimitExceeded', ...
        ['The request requires NFFT=%d; the fixed maximum is %d. ', ...
         'Reduce WINDOW_LENGTH or ZERO_PADDING_FACTOR.'], ...
        nfft,limits.maximum_fft_length);
end
end

function [xPrepared,yPrepared,leftCount,rightCount,valueScale,meanValue] = ...
        prepareSeries(x,y,dt,windowIntervals,edgePadding)
valueScale = max(abs(y));
if valueScale == 0
    yNormalized = zeros(size(y));
    meanValue = 0;
else
    yNormalized = y/valueScale;
    meanValue = mean(yNormalized);
    yNormalized = yNormalized-meanValue;
end
if any(~isfinite(yNormalized))
    error('Acycle:SpectralMoments:InvalidNormalizedValues', ...
        'Global scaling and mean centring must remain finite.');
end

if strcmp(edgePadding,'none')
    xPrepared = x;
    yPrepared = yNormalized;
    leftCount = 0;
    rightCount = 0;
    return
end

leftCount = floor(windowIntervals/2);
rightCount = ceil(windowIntervals/2);
leftCoordinates = x(1)-(leftCount:-1:1)'*dt;
rightCoordinates = x(end)+(1:rightCount)'*dt;
if any(~isfinite(leftCoordinates)) || ...
        any(~isfinite(rightCoordinates)) || ...
        (~isempty(leftCoordinates) && leftCoordinates(end) >= x(1)) || ...
        (~isempty(rightCoordinates) && rightCoordinates(1) <= x(end))
    error('Acycle:SpectralMoments:UnrepresentablePaddingCoordinates', ...
        ['Synthetic padding coordinates must be finite and distinct at ', ...
         'DOUBLE precision. Shift or rescale the coordinate axis.']);
end
xPrepared = [leftCoordinates;x;rightCoordinates];
yPrepared = [zeros(leftCount,1);yNormalized;zeros(rightCount,1)];
if any(diff(xPrepared) <= 0) || any(~isfinite(xPrepared))
    error('Acycle:SpectralMoments:InvalidPreparedCoordinates', ...
        'Prepared coordinates must remain finite and strictly increasing.');
end
end

function [residual,peak] = linearDetrendSegment( ...
        segment,inputEpsilon,resolutionMultiplier,windowIndex)
segmentScale = max(abs(segment));
if ~(isfinite(segmentScale) && segmentScale > 0)
    error('Acycle:SpectralMoments:UnresolvableWindowPower', ...
        ['Window %d is constant after global mean centring and has no ', ...
         'resolvable detrended spectral power.'],windowIndex);
end
scaled = segment/segmentScale;
sampleCount = numel(scaled);
ordinal = (0:sampleCount-1)';
ordinal = ordinal-(sampleCount-1)/2;
centered = scaled-mean(scaled);
denominator = sum(ordinal.^2);
if ~(isfinite(denominator) && denominator > 0)
    error('Acycle:SpectralMoments:InvalidDetrendBasis', ...
        'Window %d has an invalid linear-detrend basis.',windowIndex);
end
slope = sum(ordinal.*centered)/denominator;
residual = centered-slope*ordinal;
peak = max(abs(residual));
resolution = resolutionMultiplier*inputEpsilon* ...
    max(1,max(abs(scaled)));
if ~(isfinite(peak) && peak > resolution)
    error('Acycle:SpectralMoments:UnresolvableWindowPower', ...
        ['Window %d has zero or numerically unresolvable residual ', ...
         'power after linear detrending.'],windowIndex);
end
residual = residual/peak;
if any(~isfinite(residual))
    error('Acycle:SpectralMoments:InvalidDetrendedSegment', ...
        'Window %d produced a nonfinite detrended segment.',windowIndex);
end
end

function validatePeriodogram(power,frequency,nfft,nyquist,windowIndex)
expectedBins = nfft/2+1;
if ~(iscolumn(power) && iscolumn(frequency) && ...
        numel(power) == expectedBins && numel(frequency) == expectedBins)
    error('Acycle:SpectralMoments:InvalidPeriodogramShape', ...
        'Window %d produced an unexpected one-sided periodogram shape.', ...
        windowIndex);
end
if any(~isfinite(power)) || any(power < 0) || ...
        any(~isfinite(frequency)) || frequency(1) ~= 0 || ...
        any(diff(frequency) <= 0)
    error('Acycle:SpectralMoments:InvalidPeriodogram', ...
        ['Window %d must produce finite nonnegative power on a finite, ', ...
         'strictly increasing frequency grid beginning at DC.'], ...
        windowIndex);
end
endpointTolerance = 64*eps(max(1,nyquist));
if abs(frequency(end)-nyquist) > endpointTolerance
    error('Acycle:SpectralMoments:PeriodogramNyquistMismatch', ...
        ['Window %d periodogram endpoint %.17g does not match physical ', ...
         'Nyquist %.17g.'],windowIndex,frequency(end),nyquist);
end
end
