function [result,meta] = acycleAmplitudeModulation(data)
%ACYCLEAMPLITUDEMODULATION Demeaned analytic-signal envelope.
%   [RESULT,META] = ACYCLEAMPLITUDEMODULATION(DATA) extracts the amplitude
%   envelope of a finite, real SINGLE or DOUBLE N-by-2 series. DATA(:,1)
%   must already be unique and strictly increasing; rows are never sorted,
%   merged, removed, or otherwise silently preprocessed.
%
%   Sampling regularity follows ACYCLESAMPLINGISUNEVEN, Acycle's shared
%   relative-spacing policy. An irregular series is linearly interpolated
%   at MEDIAN(DIFF(X)) by
%   ACYCLEINTERPOLATESERIES. That helper uses a release-stable integer-index
%   grid anchored at the first coordinate: the final input coordinate is
%   included only when the raw interval count is within eight ULPs of an
%   integer; otherwise the trailing fractional interval is omitted. This
%   deliberately replaces the release-dependent endpoint behavior of the
%   legacy START:STEP:STOP expression.
%
%   The processed values are demeaned before the analytic signal is formed.
%   A standard one-sided FFT multiplier is used directly in base MATLAB:
%   DC and an even-length Nyquist bin have gain 1, positive-frequency bins
%   have gain 2, and negative-frequency bins have gain 0. No call to the
%   Signal Processing Toolbox HILBERT function is made.
%
%   RESULT is a finite DOUBLE matrix with columns coordinate and envelope.
%   Its row count equals N when interpolation is not triggered and equals
%   the explicit interpolation-grid length otherwise. No files, graphics,
%   dialogs, current folders, paths, root state, base workspace, or random
%   state are read or modified.

narginchk(1,1);

maximumInputRows = 1e6;
if ~(isa(data,'double') || isa(data,'single')) || ~isreal(data) || ...
        ~ismatrix(data) || size(data,2) ~= 2
    error('Acycle:AmplitudeModulation:InvalidData', ...
        ['DATA must be a real SINGLE or DOUBLE N-by-2 matrix with ', ...
         'coordinate in column 1 and value in column 2.']);
end
inputRows = size(data,1);
if inputRows < 2
    error('Acycle:AmplitudeModulation:TooFewRows', ...
        'DATA must contain at least two rows.');
end
if inputRows > maximumInputRows
    error('Acycle:AmplitudeModulation:InputRowLimitExceeded', ...
        'DATA exceeds the fixed maximum of %.17g input rows.', ...
        maximumInputRows);
end
if any(~isfinite(data(:)))
    error('Acycle:AmplitudeModulation:NonfiniteData', ...
        'Every DATA coordinate and value must be finite.');
end

working = full(double(data));
coordinates = working(:,1);
spacing = diff(coordinates);
if any(spacing <= 0)
    error( ...
        'Acycle:AmplitudeModulation:CoordinatesNotStrictlyIncreasing', ...
        ['DATA(:,1) must already be sorted, contain no duplicates, and ', ...
         'be strictly increasing.']);
end
if any(~isfinite(spacing))
    error('Acycle:AmplitudeModulation:UnrepresentableSpacing', ...
        'Every coordinate spacing must be representable as a finite DOUBLE.');
end

inputSpacingMinimum = min(spacing);
inputSpacingMedian = median(spacing);
inputSpacingMaximum = max(spacing);
spacingSpread = inputSpacingMaximum-inputSpacingMinimum;
[interpolated,samplingInfo] = acycleSamplingIsUneven(coordinates);
irregularityTolerance = samplingInfo.RelativeTolerance;
if interpolated
    [processed,interpolationMeta] = acycleInterpolateSeries( ...
        working,inputSpacingMedian);
else
    processed = working;
    interpolationMeta = struct();
end

processedCoordinates = processed(:,1);
processedValues = processed(:,2);
processedMean = finiteArithmeticMean(processedValues);
centeredValues = processedValues-processedMean;
if any(~isfinite(centeredValues))
    error('Acycle:AmplitudeModulation:UnrepresentableCentering', ...
        ['Subtracting the processed value mean must produce finite ', ...
         'DOUBLE values. Rescale extreme input values.']);
end

[envelope,analyticScale,multiplierPolicy] = ...
    fftAnalyticEnvelope(centeredValues);
result = [processedCoordinates,envelope];
outputRows = size(result,1);
if ~isequal(size(result),[outputRows,2]) || ~isa(result,'double') || ...
        ~isreal(result) || any(~isfinite(result(:)))
    error('Acycle:AmplitudeModulation:InvalidOutput', ...
        ['Amplitude modulation must produce one finite real DOUBLE ', ...
         'two-column row for every processed coordinate.']);
end

outputSpacing = diff(processedCoordinates);
if any(~isfinite(outputSpacing)) || any(outputSpacing <= 0)
    error('Acycle:AmplitudeModulation:InvalidOutputSpacing', ...
        'Output coordinates must be finite and strictly increasing.');
end
if interpolated
    endpointIncluded = interpolationMeta.EndpointIncluded;
    unfilledTail = interpolationMeta.UnfilledTail;
    gridChanged = interpolationMeta.GridChanged;
    interpolationMethod = interpolationMeta.Method;
else
    endpointIncluded = true;
    unfilledTail = 0;
    gridChanged = false;
    interpolationMethod = 'none';
end

meta = struct( ...
    'version','amplitude-modulation-v1', ...
    'input_policy','strict-finite-real-two-column-unique-increasing', ...
    'input_rows',inputRows, ...
    'input_columns',2, ...
    'output_rows',outputRows, ...
    'output_columns',2, ...
    'result_columns',{{'coordinate','envelope'}}, ...
    'coordinate_start',coordinates(1), ...
    'coordinate_end',coordinates(end), ...
    'input_spacing_minimum',inputSpacingMinimum, ...
    'input_spacing_median',inputSpacingMedian, ...
    'input_spacing_maximum',inputSpacingMaximum, ...
    'input_spacing_spread',spacingSpread, ...
    'irregularity_metric','maximum_spacing_departure_from_median_relative', ...
    'relative_spacing_error',samplingInfo.RelativeSpacingError, ...
    'irregularity_tolerance',irregularityTolerance, ...
    'irregularity_trigger','relative_spacing_error_greater_than_tolerance', ...
    'interpolated',interpolated, ...
    'interpolation_method',interpolationMethod, ...
    'interpolation_sampling_interval',inputSpacingMedian, ...
    'interpolation_grid_origin','first_input_coordinate', ...
    'interpolation_endpoint_policy', ...
        'eight-ulp-near-integer-include-otherwise-floor', ...
    'legacy_colon_endpoint_policy', ...
        'replaced-release-dependent-colon-with-explicit-grid', ...
    'endpoint_included',endpointIncluded, ...
    'unfilled_tail',unfilledTail, ...
    'grid_changed',gridChanged, ...
    'interpolation_meta',interpolationMeta, ...
    'output_spacing_minimum',min(outputSpacing), ...
    'output_spacing_median',median(outputSpacing), ...
    'output_spacing_maximum',max(outputSpacing), ...
    'sorted',false, ...
    'duplicates_rejected',true, ...
    'removed_rows',0, ...
    'demeaned',true, ...
    'processed_value_mean',processedMean, ...
    'analytic_signal','base-matlab-fft', ...
    'analytic_signal_multiplier',multiplierPolicy, ...
    'analytic_signal_scale',analyticScale, ...
    'nfft',outputRows, ...
    'toolbox_dependency','MATLAB_only', ...
    'maximum_input_rows',maximumInputRows, ...
    'file_io',false, ...
    'graphics',false, ...
    'random_number_generation',false, ...
    'side_effect_policy','none');
end

function value = finiteArithmeticMean(values)
valueScale = max(abs(values));
if valueScale == 0
    value = 0;
elseif valueScale <= realmax('double')/numel(values)
    value = mean(values);
else
    scaledMean = mean(values/valueScale);
    scaledMean = min(1,max(-1,scaledMean));
    value = valueScale*scaledMean;
end
if ~isfinite(value)
    error('Acycle:AmplitudeModulation:UnrepresentableMean', ...
        'The processed value mean must be representable as a finite DOUBLE.');
end
value = min(max(values),max(min(values),value));
end

function [envelope,analyticScale,multiplierPolicy] = ...
        fftAnalyticEnvelope(values)
pointCount = numel(values);
multiplier = zeros(pointCount,1);
multiplier(1) = 1;
if mod(pointCount,2) == 0
    multiplier(2:pointCount/2) = 2;
    multiplier(pointCount/2+1) = 1;
    multiplierPolicy = ...
        'even:dc=1,positive=2,nyquist=1,negative=0';
else
    multiplier(2:(pointCount+1)/2) = 2;
    multiplierPolicy = 'odd:dc=1,positive=2,negative=0';
end

analyticScale = max(abs(values));
if analyticScale == 0
    envelope = zeros(pointCount,1);
    return
end

% The one-sided multiplier can double a Fourier coefficient. Use the
% unscaled path whenever the conservative 2*N*MAXABS bound is finite so
% ordinary inputs agree point-for-point with HILBERT's standard FFT method.
if analyticScale <= realmax('double')/(2*pointCount)
    analyticSignal = ifft(fft(values).*multiplier);
    envelope = abs(analyticSignal);
else
    normalizedSignal = values/analyticScale;
    analyticSignal = ifft(fft(normalizedSignal).*multiplier);
    normalizedEnvelope = abs(analyticSignal);
    envelope = analyticScale*normalizedEnvelope;
end
if any(~isfinite(envelope))
    error('Acycle:AmplitudeModulation:NonfiniteEnvelope', ...
        ['The analytic-signal envelope is not representable as finite ', ...
         'DOUBLE values. Rescale extreme input values.']);
end
end
