function [result,meta] = acycleBandpassFilter(data,options)
%ACYCLEBANDPASSFILTER Corrected, side-effect-free Acycle band-pass core.
%   [RESULT,META] = ACYCLEBANDPASSFILTER(DATA,OPTIONS) filters a finite,
%   real N-by-2 series [coordinate,value] without sorting, interpolation,
%   plotting, file output, or workspace mutation. Coordinates must be
%   strictly increasing and regularly spaced to relative tolerance 1e-5.
%
%   OPTIONS requires METHOD, LOWER_FREQUENCY, and UPPER_FREQUENCY. METHOD is
%   'gaussian' or 'taner_hilbert'. Taner additionally accepts
%   ROLLOFF_EXPONENT q in (0,20], with default 12 and c=10^q.
%
%   Both methods remove the value mean and use median(diff(coordinate)).
%   Their center is exactly (lower+upper)/2, and both band edges are -3 dB
%   half-power points. The implementation identifier is
%   'corrected-bandpass-v2'.
%
%   Algorithm lineage: the Acycle Gaussian filter was edited by L. Hinnov
%   (2016) from K. Ramamurthy's 2013 Analyseries-compatible parameterization.
%   The Taner-Hilbert path follows Linda Hinnov's 2006 implementation of the
%   filter described by Turhan Taner (2000), "Attributes revisited."

narginchk(2,2);
limits = fixedLimits();
[working,contract] = validateSeries(data,limits);
options = validateOptions(options,limits);

coordinate = working(:,1);
inputValue = working(:,2);
inputRows = size(working,1);
inputMean = stableMean(inputValue);
centeredValue = inputValue-inputMean;
if any(~isfinite(centeredValue))
    error('Acycle:BandpassFilter:UnrepresentableCentering', ...
        'Mean removal is not representable at DOUBLE precision.');
end
inputVariance = stableVariance(inputValue);
analysisVariance = stableVariance(centeredValue);
if ~(isfinite(inputVariance) && inputVariance > 0 && ...
        isfinite(analysisVariance) && analysisVariance > 0)
    error('Acycle:BandpassFilter:InvalidVariance', ...
        'The value column must have finite positive sample variance.');
end

sampleInterval = contract.sample_interval;
nyquist = 1/(2*sampleInterval);
validateFrequencyBand(options.lower_frequency, ...
    options.upper_frequency,nyquist);
centerFrequency = ...
    (options.lower_frequency+options.upper_frequency)/2;
if ~isfinite(centerFrequency)
    error('Acycle:BandpassFilter:InvalidCenterFrequency', ...
        'The frequency-band midpoint is not representable.');
end

switch options.method
    case 'gaussian'
        [filtered,responseFrequency,responseGain,kernel] = ...
            gaussianKernel(centeredValue,sampleInterval, ...
            centerFrequency,options.lower_frequency, ...
            options.upper_frequency);
    case 'taner_hilbert'
        [filtered,responseFrequency,responseGain,kernel] = ...
            tanerKernel(centeredValue,sampleInterval, ...
            centerFrequency,options.lower_frequency, ...
            options.upper_frequency,options.rolloff_exponent);
    otherwise
        error('Acycle:BandpassFilter:InternalMethod', ...
            'An unsupported method reached the filter kernel.');
end

analytic = hilbert(filtered);
envelope = abs(analytic);
if any(~isfinite(envelope))
    error('Acycle:BandpassFilter:NonfiniteEnvelope', ...
        'The analytic-signal envelope contains a nonfinite value.');
end

result = struct( ...
    'coordinate',coordinate, ...
    'filtered',filtered, ...
    'envelope',envelope, ...
    'response_frequency',responseFrequency, ...
    'response_gain',responseGain, ...
    'method',options.method);

phase = struct();
if strcmp(options.method,'taner_hilbert')
    wrappedPhase = angle(analytic);
    unwrappedPhase = unwrap(wrappedPhase);
    shiftedCoordinate = coordinate-coordinate(1);
    phaseFit = polyfit(shiftedCoordinate,unwrappedPhase,1);
    phaseTrend = polyval(phaseFit,shiftedCoordinate);
    phaseResidual = unwrappedPhase-phaseTrend;
    coordinateSpacing = diff(coordinate);
    instantaneousFrequency = ...
        diff(unwrappedPhase)./(2*pi*coordinateSpacing);
    instantaneousCoordinate = ...
        coordinate(1:end-1)+coordinateSpacing/2;
    if any(~isfinite([wrappedPhase;unwrappedPhase;phaseResidual; ...
            instantaneousFrequency;instantaneousCoordinate]))
        error('Acycle:BandpassFilter:NonfinitePhaseAttribute', ...
            'A corrected Taner-Hilbert phase attribute is nonfinite.');
    end
    result.wrapped_phase_rad = wrappedPhase;
    result.unwrapped_phase_rad = unwrappedPhase;
    result.phase_residual_rad = phaseResidual;
    result.instantaneous_frequency = instantaneousFrequency;
    result.instantaneous_frequency_coordinate = instantaneousCoordinate;
    phase = struct( ...
        'linear_phase_slope_rad_per_coordinate',phaseFit(1), ...
        'linear_phase_intercept_rad',phaseFit(2));
end

warningIds = cell(0,1);
warningMessages = cell(0,1);
if contract.spacing_departure_above_roundoff
    warningIds{end+1,1} = ...
        'Acycle:BandpassFilter:SpacingDepartureWithinTolerance';
    warningMessages{end+1,1} = sprintf( ...
        ['Coordinate spacing departure %.17g exceeds roundoff but remains ', ...
         'within the accepted relative tolerance %.17g. No interpolation ', ...
         'was performed.'],contract.maximum_spacing_error, ...
        contract.spacing_tolerance);
end

meta = struct( ...
    'version','corrected-bandpass-v2', ...
    'implementation','corrected-bandpass-v2', ...
    'method',options.method, ...
    'input_policy', ...
        'strict_finite_increasing_near_uniform_two_column_series', ...
    'input_rows',inputRows, ...
    'input_columns',2, ...
    'coordinate_start',coordinate(1), ...
    'coordinate_end',coordinate(end), ...
    'sample_interval',sampleInterval, ...
    'sample_interval_source','median_coordinate_spacing', ...
    'maximum_spacing_error',contract.maximum_spacing_error, ...
    'relative_spacing_departure',contract.relative_spacing_departure, ...
    'spacing_tolerance',contract.spacing_tolerance, ...
    'spacing_roundoff_absolute_tolerance', ...
        contract.roundoff_absolute_tolerance, ...
    'spacing_departure_above_roundoff', ...
        contract.spacing_departure_above_roundoff, ...
    'sorted',false, ...
    'removed_rows',0, ...
    'interpolated',false, ...
    'demeaned',true, ...
    'input_mean',inputMean, ...
    'input_variance',inputVariance, ...
    'analysis_variance',analysisVariance, ...
    'lower_frequency',options.lower_frequency, ...
    'upper_frequency',options.upper_frequency, ...
    'center_frequency',centerFrequency, ...
    'nyquist_frequency',nyquist, ...
    'nfft',kernel.nfft, ...
    'frequency_resolution',kernel.frequency_resolution, ...
    'response_bins',numel(responseFrequency), ...
    'response_includes_nyquist',kernel.response_includes_nyquist, ...
    'maximum_hermitian_error',kernel.maximum_hermitian_error, ...
    'ifft_imaginary_maximum',kernel.ifft_imaginary_maximum, ...
    'ifft_imaginary_tolerance',kernel.ifft_imaginary_tolerance, ...
    'gaussian_cutoff_gain',kernel.gaussian_cutoff_gain, ...
    'gaussian_shape_exponent',kernel.gaussian_shape_exponent, ...
    'rolloff_exponent',kernel.rolloff_exponent, ...
    'rolloff_c',kernel.rolloff_c, ...
    'taner_shape_exponent',kernel.taner_shape_exponent, ...
    'taner_normalized_octave_gain',kernel.taner_normalized_octave_gain, ...
    'phase',phase, ...
    'filtered_minimum',min(filtered), ...
    'filtered_maximum',max(filtered), ...
    'envelope_minimum',min(envelope), ...
    'envelope_maximum',max(envelope), ...
    'warning_ids',{warningIds}, ...
    'warnings',{warningMessages}, ...
    'side_effect_policy','none');
end

function limits = fixedLimits()
limits = struct( ...
    'minimum_input_rows',8, ...
    'spacing_tolerance',1e-5, ...
    'minimum_rolloff_exponent',0, ...
    'maximum_rolloff_exponent',20);
end

function [working,contract] = validateSeries(data,limits)
if ~((isa(data,'double') || isa(data,'single')) && ...
        isreal(data) && ismatrix(data) && size(data,2) == 2 && ...
        ~issparse(data))
    error('Acycle:BandpassFilter:InvalidData', ...
        'DATA must be a full real SINGLE or DOUBLE N-by-2 matrix.');
end
if size(data,1) < limits.minimum_input_rows
    error('Acycle:BandpassFilter:TooFewRows', ...
        'Filtering requires at least eight input rows.');
end
if any(~isfinite(data),'all')
    error('Acycle:BandpassFilter:NonfiniteData', ...
        'Every coordinate and value must be finite.');
end
working = double(data);
coordinate = working(:,1);
spacing = diff(coordinate);
if any(spacing <= 0) || any(~isfinite(spacing))
    error('Acycle:BandpassFilter:CoordinatesNotStrictlyIncreasing', ...
        'Coordinates must already be finite and strictly increasing.');
end
sampleInterval = median(spacing);
maximumSpacingError = max(abs(spacing-sampleInterval));
relativeSpacingDeparture = maximumSpacingError/sampleInterval;
if ~(isfinite(sampleInterval) && sampleInterval > 0 && ...
        isfinite(relativeSpacingDeparture)) || ...
        relativeSpacingDeparture > limits.spacing_tolerance
    error('Acycle:BandpassFilter:UnevenSampling', ...
        ['Relative spacing departure %.17g exceeds the fixed tolerance ', ...
         '%.17g. Interpolate explicitly before filtering.'], ...
        relativeSpacingDeparture,limits.spacing_tolerance);
end
scale = max([1;abs(coordinate);abs(sampleInterval)]);
roundoffTolerance = 128*eps(scale);
contract = struct( ...
    'sample_interval',sampleInterval, ...
    'maximum_spacing_error',maximumSpacingError, ...
    'relative_spacing_departure',relativeSpacingDeparture, ...
    'spacing_tolerance',limits.spacing_tolerance, ...
    'roundoff_absolute_tolerance',roundoffTolerance, ...
    'spacing_departure_above_roundoff', ...
        maximumSpacingError > roundoffTolerance);
end

function options = validateOptions(options,limits)
if ~isstruct(options) || ~isscalar(options)
    error('Acycle:BandpassFilter:InvalidOptions', ...
        'OPTIONS must be a scalar struct.');
end
allowed = {'method','lower_frequency','upper_frequency', ...
    'rolloff_exponent'};
unknown = setdiff(fieldnames(options),allowed);
if ~isempty(unknown)
    error('Acycle:BandpassFilter:UnknownOption', ...
        'Unknown band-pass option: %s.',unknown{1});
end
required = {'method','lower_frequency','upper_frequency'};
for index = 1:numel(required)
    if ~isfield(options,required{index}) || isempty(options.(required{index}))
        error('Acycle:BandpassFilter:MissingOption', ...
            'Required option %s is missing.',upper(required{index}));
    end
end
options.method = textChoice(options.method, ...
    {'gaussian','taner_hilbert'},'method');
options.lower_frequency = positiveFiniteScalar( ...
    options.lower_frequency,'lower_frequency');
options.upper_frequency = positiveFiniteScalar( ...
    options.upper_frequency,'upper_frequency');
if options.upper_frequency <= options.lower_frequency
    error('Acycle:BandpassFilter:InvalidFrequencyOrder', ...
        'UPPER_FREQUENCY must be greater than LOWER_FREQUENCY.');
end
if strcmp(options.method,'gaussian')
    if isfield(options,'rolloff_exponent')
        error('Acycle:BandpassFilter:InactiveRolloffExponent', ...
            'ROLLOFF_EXPONENT is accepted only for taner_hilbert.');
    end
    options.rolloff_exponent = [];
else
    if ~isfield(options,'rolloff_exponent') || ...
            isempty(options.rolloff_exponent)
        options.rolloff_exponent = 12;
    else
        options.rolloff_exponent = finiteScalar( ...
            options.rolloff_exponent,'rolloff_exponent');
    end
    if options.rolloff_exponent <= limits.minimum_rolloff_exponent || ...
            options.rolloff_exponent > limits.maximum_rolloff_exponent
        error('Acycle:BandpassFilter:RolloffExponentOutOfRange', ...
            'ROLLOFF_EXPONENT must lie in the interval (0,20].');
    end
end
end

function validateFrequencyBand(lowerFrequency,upperFrequency,nyquist)
if upperFrequency <= lowerFrequency
    error('Acycle:BandpassFilter:InvalidFrequencyOrder', ...
        'UPPER_FREQUENCY must be greater than LOWER_FREQUENCY.');
end
if upperFrequency >= nyquist
    error('Acycle:BandpassFilter:FrequencyAtOrAboveNyquist', ...
        ['UPPER_FREQUENCY must be strictly below the Nyquist frequency ', ...
         '%.17g.'],nyquist);
end
end

function [filtered,responseFrequency,responseGain,kernel] = ...
        gaussianKernel(values,dt,fc,fl,fh)
n = numel(values);
baseLength = 2^nextpow2(n);
nfft = 10*baseLength;
if ~(isfinite(nfft) && nfft >= n && nfft == fix(nfft) && mod(nfft,2) == 0)
    error('Acycle:BandpassFilter:InvalidGaussianFftLength', ...
        'The corrected Gaussian FFT length is invalid.');
end
frequencyResolution = 1/(nfft*dt);
indices = (0:nfft-1)';
absoluteBins = min(indices,nfft-indices);
absoluteFrequency = absoluteBins*frequencyResolution;
halfBandwidth = (fh-fl)/2;
halfPowerCoefficient = log(sqrt(2));
normalizedOffset = (absoluteFrequency-fc)/halfBandwidth;
responseAll = exp(-halfPowerCoefficient*normalizedOffset.^2);
validateResponse(responseAll,nfft,'Gaussian');
[hermitianError,imaginaryMaximum,imaginaryTolerance,timeDomain] = ...
    applyRealResponse(values,responseAll);
filtered = real(timeDomain(1:n));
responseFrequency = (0:nfft/2)'*frequencyResolution;
responseGain = responseAll(1:nfft/2+1);
kernel = kernelMetadata(nfft,frequencyResolution,true, ...
    hermitianError,imaginaryMaximum,imaginaryTolerance);
kernel.gaussian_cutoff_gain = 1/sqrt(2);
kernel.gaussian_shape_exponent = 2;
end

function [filtered,responseFrequency,responseGain,kernel] = ...
        tanerKernel(values,dt,fc,fl,fh,q)
nfft = numel(values);
frequencyResolution = 1/(nfft*dt);
indices = (0:nfft-1)';
absoluteBins = min(indices,nfft-indices);
absoluteFrequency = absoluteBins*frequencyResolution;
bandwidth = fh-fl;
normalizedOffset = 2*abs(absoluteFrequency-fc)/bandwidth;
a = log(sqrt(2));
c = 10^q;
shapeExponent = log2(1+log(c)/a);
if ~(isfinite(c) && c > 1 && isfinite(shapeExponent) && shapeExponent > 0)
    error('Acycle:BandpassFilter:InvalidTanerParameters', ...
        'The corrected Taner roll-off parameters are invalid.');
end
responseAll = exp(-a*normalizedOffset.^shapeExponent);
validateResponse(responseAll,nfft,'Taner');
[hermitianError,imaginaryMaximum,imaginaryTolerance,timeDomain] = ...
    applyRealResponse(values,responseAll);
filtered = real(timeDomain);
ncut = floor(nfft/2)+1;
responseFrequency = (0:ncut-1)'*frequencyResolution;
responseGain = responseAll(1:ncut);
kernel = kernelMetadata(nfft,frequencyResolution,mod(nfft,2) == 0, ...
    hermitianError,imaginaryMaximum,imaginaryTolerance);
kernel.rolloff_exponent = q;
kernel.rolloff_c = c;
kernel.taner_shape_exponent = shapeExponent;
kernel.taner_normalized_octave_gain = 1/(sqrt(2)*c);
end

function validateResponse(response,nfft,label)
if ~(iscolumn(response) && numel(response) == nfft && ...
        all(isfinite(response)) && all(response >= 0) && all(response <= 1))
    error('Acycle:BandpassFilter:InvalidResponse', ...
        '%s response is not a finite gain in [0,1].',label);
end
end

function [hermitianError,imaginaryMaximum,imaginaryTolerance,timeDomain] = ...
        applyRealResponse(values,response)
nfft = numel(response);
if mod(nfft,2) == 0
    positive = response(2:nfft/2);
    mirroredNegative = flipud(response(nfft/2+2:end));
else
    positive = response(2:(nfft+1)/2);
    mirroredNegative = flipud(response((nfft+3)/2:end));
end
if isempty(positive)
    hermitianError = 0;
else
    hermitianError = max(abs(positive-mirroredNegative));
end
if hermitianError ~= 0
    error('Acycle:BandpassFilter:NonHermitianResponse', ...
        'The corrected full FFT response is not exactly Hermitian.');
end
coefficients = fft(values,nfft).*response;
timeDomain = ifft(coefficients,nfft);
imaginaryMaximum = max(abs(imag(timeDomain)));
scale = max(1,max(abs(timeDomain)));
imaginaryTolerance = 512*eps(scale)*max(1,ceil(log2(nfft)));
if imaginaryMaximum > imaginaryTolerance
    error('Acycle:BandpassFilter:ComplexRoundoffExceeded', ...
        ['The inverse FFT imaginary residual %.17g exceeds the roundoff ', ...
         'tolerance %.17g.'],imaginaryMaximum,imaginaryTolerance);
end
end

function kernel = kernelMetadata(nfft,df,includesNyquist, ...
        hermitianError,imaginaryMaximum,imaginaryTolerance)
kernel = struct( ...
    'nfft',nfft, ...
    'frequency_resolution',df, ...
    'response_includes_nyquist',includesNyquist, ...
    'maximum_hermitian_error',hermitianError, ...
    'ifft_imaginary_maximum',imaginaryMaximum, ...
    'ifft_imaginary_tolerance',imaginaryTolerance, ...
    'gaussian_cutoff_gain',[], ...
    'gaussian_shape_exponent',[], ...
    'rolloff_exponent',[], ...
    'rolloff_c',[], ...
    'taner_shape_exponent',[], ...
    'taner_normalized_octave_gain',[]);
end

function value = textChoice(value,choices,name)
if isstring(value) && isscalar(value)
    value = char(value);
end
if ~(ischar(value) && isrow(value) && ~isempty(strtrim(value)))
    error('Acycle:BandpassFilter:InvalidTextOption', ...
        '%s must be one supported text value.',upper(name));
end
value = lower(strtrim(value));
if ~any(strcmp(value,choices))
    error('Acycle:BandpassFilter:InvalidTextOption', ...
        '%s must be one of: %s.',upper(name),strjoin(choices,', '));
end
end

function value = positiveFiniteScalar(value,name)
value = finiteScalar(value,name);
if value <= 0
    error('Acycle:BandpassFilter:InvalidNumericOption', ...
        '%s must be a finite positive numeric scalar.',upper(name));
end
end

function value = finiteScalar(value,name)
if ~(isnumeric(value) && ~islogical(value) && isreal(value) && ...
        isscalar(value) && isfinite(value))
    error('Acycle:BandpassFilter:InvalidNumericOption', ...
        '%s must be a finite real numeric scalar.',upper(name));
end
value = double(value);
end

function value = stableMean(values)
scale = max(abs(values));
if scale == 0
    value = 0;
else
    value = scale*mean(values/scale);
end
end

function value = stableVariance(values)
center = stableMean(values);
residual = values-center;
scale = max(abs(residual));
if scale == 0
    value = 0;
else
    rootVariance = scale*sqrt(sum((residual/scale).^2)/(numel(values)-1));
    value = rootVariance^2;
end
end
