function [result,meta] = acycleEvolutionaryRho1( ...
        data,samplingInterval,windowLength)
%ACYCLEEVOLUTIONARYRHO1 Deterministic sliding-window lag-1 rho.
%   [RESULT,META] = ACYCLEEVOLUTIONARYRHO1(DATA,SAMPLINGINTERVAL,
%   WINDOWLENGTH) runs the reviewed deterministic/single evolutionary-rho
%   analysis. DATA must be a finite real SINGLE or DOUBLE N-by-2 matrix
%   [coordinate,value] with strictly increasing coordinates.
%
%   The series is linearly resampled by ACYCLEINTERPOLATESERIES on its
%   release-stable integer-index grid. The historical window conversion is
%   retained exactly:
%
%       K = round(WINDOWLENGTH/SAMPLINGINTERVAL)
%
%   K must be at least three and no greater than the interpolated row count.
%   Each consecutive K-point window is independently linear-detrended on a
%   centered sample-index basis. After removing residual roundoff in its
%   mean, lag-1 rho follows the historical RHOAR1ML convention:
%
%       sum(z(2:end).*z(1:end-1)) / sum(z(1:end-1).^2)
%
%   RESULT contains [actual_window_center,rho1]. The center is the stable
%   midpoint of the actual first and last coordinates in each K-point
%   window; it is not reconstructed from the requested physical window.
%   The requested window length, nominal effective span (K-1)*dt, and the
%   actual span range are reported separately in META.
%
%   This core covers only the deterministic single-run calculation. It
%   performs no Monte Carlo simulation, padding, file I/O, plotting,
%   dialogs, folder or path changes, base-workspace access, or random-number
%   generation.

narginchk(3,3);

maximumInputRows = 1e6;
maximumWindowWork = 1e7;
if ~((isa(data,'double') || isa(data,'single')) && ...
        ~issparse(data) && isreal(data) && ismatrix(data) && ...
        size(data,2) == 2)
    error('Acycle:EvolutionaryRho1:InvalidData', ...
        ['DATA must be a full, real SINGLE or DOUBLE N-by-2 matrix ', ...
         '[coordinate,value].']);
end
inputRows = size(data,1);
if inputRows < 2
    error('Acycle:EvolutionaryRho1:TooFewRows', ...
        'DATA must contain at least two rows.');
end
if inputRows > maximumInputRows
    error('Acycle:EvolutionaryRho1:InputRowLimitExceeded', ...
        'DATA exceeds the fixed maximum of 1000000 input rows.');
end
if any(~isfinite(data(:)))
    error('Acycle:EvolutionaryRho1:NonfiniteData', ...
        'Every DATA coordinate and value must be finite.');
end

working = full(double(data));
coordinate = working(:,1);
inputSpacing = diff(coordinate);
if any(~isfinite(inputSpacing))
    error('Acycle:EvolutionaryRho1:UnrepresentableSpacing', ...
        'Every coordinate spacing must be representable as finite DOUBLE.');
end
if any(inputSpacing <= 0)
    error('Acycle:EvolutionaryRho1:CoordinatesNotStrictlyIncreasing', ...
        ['DATA coordinates must already be unique and strictly ', ...
         'increasing; rows are never sorted or merged.']);
end
coordinateSpan = coordinate(end)-coordinate(1);
if ~(isfinite(coordinateSpan) && coordinateSpan > 0)
    error('Acycle:EvolutionaryRho1:UnrepresentableCoordinateSpan', ...
        'The input coordinate span must be finite and positive.');
end

samplingInterval = positiveScalar( ...
    samplingInterval,'SAMPLINGINTERVAL');
if samplingInterval > coordinateSpan
    error('Acycle:EvolutionaryRho1:SamplingIntervalExceedsSpan', ...
        'SAMPLINGINTERVAL must not exceed the input coordinate span.');
end
windowLength = positiveScalar(windowLength,'WINDOWLENGTH');

[interpolated,interpolationMeta] = ...
    acycleInterpolateSeries(working,samplingInterval);
interpolatedRows = size(interpolated,1);
rawWindowPoints = windowLength/samplingInterval;
if ~isfinite(rawWindowPoints)
    error('Acycle:EvolutionaryRho1:UnrepresentableWindowPoints', ...
        'WINDOWLENGTH/SAMPLINGINTERVAL must be finite.');
end
windowPoints = round(rawWindowPoints);
if windowPoints < 3
    error('Acycle:EvolutionaryRho1:WindowTooShort', ...
        ['round(WINDOWLENGTH/SAMPLINGINTERVAL) must be at least ', ...
         'three points.']);
end
if windowPoints > interpolatedRows
    error('Acycle:EvolutionaryRho1:WindowExceedsInterpolatedSeries', ...
        ['The rounded K-point window must not exceed the interpolated ', ...
         'row count.']);
end

outputRows = interpolatedRows-windowPoints+1;
windowWork = outputRows*windowPoints;
if ~isfinite(windowWork) || windowWork > maximumWindowWork
    error('Acycle:EvolutionaryRho1:WindowWorkLimitExceeded', ...
        ['window_points times output_rows must not exceed the fixed ', ...
         'limit of 10000000.']);
end
effectiveWindowSpan = (windowPoints-1)*samplingInterval;
if ~isfinite(effectiveWindowSpan)
    error('Acycle:EvolutionaryRho1:UnrepresentableWindowSpan', ...
        'The nominal effective K-point window span is not finite.');
end

sampleIndex = (1:windowPoints)';
detrendBasis = sampleIndex-(windowPoints+1)/2;
basisSumSquares = sum(detrendBasis.^2);
if ~(isfinite(basisSumSquares) && basisSumSquares > 0)
    error('Acycle:EvolutionaryRho1:InvalidDetrendBasis', ...
        'The fixed centered sample-index detrend basis is invalid.');
end

rho = zeros(outputRows,1);
for outputRow = 1:outputRows
    values = interpolated( ...
        outputRow:outputRow+windowPoints-1,2);
    valueMean = mean(values);
    centeredValues = values-valueMean;
    slopeNumerator = sum(detrendBasis.*centeredValues);
    if ~(isfinite(valueMean) && all(isfinite(centeredValues)) && ...
            isfinite(slopeNumerator))
        error('Acycle:EvolutionaryRho1:NonfiniteDetrend', ...
            ['Window %d cannot be linear-detrended using finite ', ...
             'DOUBLE arithmetic.'],outputRow);
    end
    detrended = centeredValues- ...
        (slopeNumerator/basisSumSquares)*detrendBasis;
    z = detrended-mean(detrended);
    if any(~isfinite(z))
        error('Acycle:EvolutionaryRho1:NonfiniteDetrend', ...
            'Window %d produced nonfinite detrended values.',outputRow);
    end
    lagged = z(1:end-1);
    leading = z(2:end);
    denominator = sum(lagged.^2);
    if ~isfinite(denominator)
        error('Acycle:EvolutionaryRho1:NonfiniteRhoDenominator', ...
            ['Window %d has a nonfinite historical rhoAR1ML ', ...
             'denominator.'],outputRow);
    end
    if denominator <= 0
        error('Acycle:EvolutionaryRho1:DegenerateRhoDenominator', ...
            ['Window %d has a degenerate historical rhoAR1ML ', ...
             'denominator.'],outputRow);
    end
    numerator = sum(leading.*lagged);
    if ~isfinite(numerator)
        error('Acycle:EvolutionaryRho1:NonfiniteRhoNumerator', ...
            ['Window %d has a nonfinite historical rhoAR1ML ', ...
             'numerator.'],outputRow);
    end
    rho(outputRow) = numerator/denominator;
    if ~isfinite(rho(outputRow))
        error('Acycle:EvolutionaryRho1:NonfiniteRho', ...
            'Window %d produced a nonfinite lag-1 rho.',outputRow);
    end
end

firstCoordinate = interpolated(1:outputRows,1);
lastCoordinate = interpolated(windowPoints:end,1);
actualWindowSpan = lastCoordinate-firstCoordinate;
windowCenter = firstCoordinate+actualWindowSpan/2;
result = [windowCenter,rho];
if ~(isa(result,'double') && isreal(result) && ...
        isequal(size(result),[outputRows,2]) && ...
        all(isfinite(result),'all') && ...
        (outputRows == 1 || all(diff(result(:,1)) > 0)))
    error('Acycle:EvolutionaryRho1:InvalidOutput', ...
        ['Evolutionary rho1 must produce a finite real two-column ', ...
         'result with strictly increasing window centers.']);
end

outputSpacing = diff(interpolated(:,1));
meta = struct( ...
    'version','evolutionary-rho1-v1', ...
    'analysis_scope','deterministic-single-run', ...
    'input_policy','strict-finite-real-two-column-unique-increasing', ...
    'input_rows',inputRows, ...
    'input_columns',2, ...
    'interpolated_rows',interpolatedRows, ...
    'output_rows',outputRows, ...
    'output_columns',2, ...
    'result_columns',{{'window_center','rho1'}}, ...
    'coordinate_start',coordinate(1), ...
    'coordinate_end',coordinate(end), ...
    'coordinate_span',coordinateSpan, ...
    'input_spacing_minimum',min(inputSpacing), ...
    'input_spacing_median',median(inputSpacing), ...
    'input_spacing_maximum',max(inputSpacing), ...
    'sampling_interval',samplingInterval, ...
    'output_spacing_minimum',min(outputSpacing), ...
    'output_spacing_median',median(outputSpacing), ...
    'output_spacing_maximum',max(outputSpacing), ...
    'requested_window_length',windowLength, ...
    'raw_window_points',rawWindowPoints, ...
    'window_points',windowPoints, ...
    'window_point_policy', ...
        'round(requested_window_length/sampling_interval)', ...
    'effective_window_span',effectiveWindowSpan, ...
    'actual_window_span_minimum',min(actualWindowSpan), ...
    'actual_window_span_maximum',max(actualWindowSpan), ...
    'window_count',outputRows, ...
    'window_work',windowWork, ...
    'maximum_input_rows',maximumInputRows, ...
    'maximum_window_work',maximumWindowWork, ...
    'interpolated',interpolationMeta.GridChanged, ...
    'interpolation_method','linear', ...
    'interpolation_grid_policy', ...
        'acycleInterpolateSeries-release-stable-integer-index', ...
    'interpolation_meta',interpolationMeta, ...
    'detrend_policy','linear-least-squares-centered-sample-index', ...
    'estimator','rhoAR1ML', ...
    'estimator_formula', ...
        'sum(z(2:end).*z(1:end-1))/sum(z(1:end-1).^2)', ...
    'estimator_centering','demean-after-linear-detrend', ...
    'rho_denominator_policy','finite-and-strictly-positive', ...
    'center_policy','actual-first-and-last-window-coordinate-midpoint', ...
    'sorted',false, ...
    'removed_rows',0, ...
    'file_io',false, ...
    'graphics',false, ...
    'random_number_generation',false, ...
    'side_effect_policy','none');
end

function value = positiveScalar(value,label)
if ~(isnumeric(value) && ~islogical(value) && isreal(value) && ...
        isscalar(value) && isfinite(value) && value > 0)
    error('Acycle:EvolutionaryRho1:InvalidPositiveScalar', ...
        '%s must be a finite positive real numeric scalar.',label);
end
value = double(value);
end
