function [result,meta] = acyclePrewhitenSeries(data,options)
%ACYCLEPREWHITENSERIES Strict historical lead-direction pre-whitening.
%   [RESULT,META] = ACYCLEPREWHITENSERIES(DATA,OPTIONS) pre-whitens one
%   finite, real, floating-point N-by-2 series [coordinate,value] on a
%   strictly increasing, near-uniform grid.  The fixed relative spacing
%   tolerance is 1e-5; rows are never sorted, removed, merged, or
%   interpolated.
%
%   OPTIONS is a scalar structure with RHO_SOURCE equal to 'classic',
%   'robust', or 'user'.  RHO is required only for RHO_SOURCE='user' and
%   must be a finite real scalar in the closed interval [-1,1].  Classic
%   and user modes require at least two rows; robust mode requires at least
%   four rows and the Signal Processing Toolbox.
%
%   RESULT has N-1 rows and the columns [coordinate,prewhitened_value].
%   The historical Acycle direction is deliberately retained:
%
%       result(i,2) = value(i)-rho*value(i+1)
%
%   Thus RESULT(:,1) is DATA(1:end-1,1).  This is a lead/forward-looking
%   residual, not the conventional past-lag residual.
%
%   Robust mode may truncate the frequency bins used for fitting at the
%   99-percent cumulative-power limit.  That fit limit is never used as
%   Nyquist: MINIRHOS0 always receives the physical Nyquist 1/(2*dt).
%   The function performs no file I/O, plotting, dialogs, folder or path
%   changes, base-workspace assignment, or random-number generation.

narginchk(2,2);
options = validateOptions(options);
contract = validateSeries(data,options.rho_source);

working = full(double(data));
coordinate = working(:,1);
values = working(:,2);

fit = emptyFitMetadata();
switch options.rho_source
    case 'classic'
        rho = rhoAR1ML(values);
        if ~(isnumeric(rho) && isreal(rho) && isscalar(rho) && ...
                isfinite(rho))
            error('Acycle:Prewhiten:InvalidClassicRho', ...
                ['Classic AR(1) estimation requires a value series with ', ...
                 'a finite, nonzero lagged sum of squares.']);
        end
    case 'robust'
        [rho,fit] = robustRho(values,contract);
    case 'user'
        rho = options.rho;
    otherwise
        error('Acycle:Prewhiten:InternalRhoSource', ...
            'The validated RHO_SOURCE was not recognized.');
end
rho = double(rho);

prewhitened = values(1:end-1)-rho*values(2:end);
result = [coordinate(1:end-1),prewhitened];
if ~isequal(size(result),[size(working,1)-1,2]) || ...
        ~isreal(result) || any(~isfinite(result(:)))
    error('Acycle:Prewhiten:InvalidOutput', ...
        ['Pre-whitening must produce a finite real (N-1)-by-2 result. ', ...
         'Rescale extreme finite values if the subtraction overflows.']);
end

meta = struct( ...
    'version','prewhiten-series-v1', ...
    'rho_source',options.rho_source, ...
    'rho',rho, ...
    'direction','lead', ...
    'formula','y(i)-rho*y(i+1)', ...
    'coordinate_alignment','input_rows_1_through_n_minus_1', ...
    'input_policy', ...
        'strict_finite_real_two_column_increasing_near_uniform', ...
    'input_rows',size(working,1), ...
    'input_columns',2, ...
    'output_rows',size(result,1), ...
    'output_columns',2, ...
    'result_columns',{{'coordinate','prewhitened_value'}}, ...
    'sample_interval',contract.sample_interval, ...
    'maximum_spacing_error',contract.maximum_spacing_error, ...
    'relative_spacing_departure', ...
        contract.relative_spacing_departure, ...
    'spacing_tolerance',contract.spacing_tolerance, ...
    'physical_nyquist',contract.physical_nyquist, ...
    'fit_upper_frequency',fit.fit_upper_frequency, ...
    'fit_frequency_bins',fit.fit_frequency_bins, ...
    'fit_smoothing_bins',fit.fit_smoothing_bins, ...
    'fit_time_bandwidth',fit.fit_time_bandwidth, ...
    'fit_initial_s0',fit.fit_initial_s0, ...
    'fit_s0',fit.fit_s0, ...
    'minirhos_nyquist',fit.minirhos_nyquist, ...
    'fit_upper_frequency_policy',fit.fit_upper_frequency_policy, ...
    'sorted',false, ...
    'removed_rows',0, ...
    'interpolated',false, ...
    'file_io',false, ...
    'graphics',false, ...
    'random_number_generation',false, ...
    'side_effect_policy','none');
end

function options = validateOptions(options)
if ~(isstruct(options) && isscalar(options))
    error('Acycle:Prewhiten:InvalidOptions', ...
        'OPTIONS must be one scalar structure.');
end
fields = fieldnames(options);
allowed = {'rho_source','rho'};
unknown = setdiff(fields,allowed);
if ~isempty(unknown)
    error('Acycle:Prewhiten:UnknownOption', ...
        'Unknown OPTIONS field: %s.',strjoin(unknown,', '));
end
if ~isfield(options,'rho_source')
    error('Acycle:Prewhiten:MissingRhoSource', ...
        'OPTIONS.rho_source is required.');
end

source = options.rho_source;
if isstring(source) && isscalar(source)
    source = char(source);
end
if ~(ischar(source) && isrow(source) && ~isempty(strtrim(source)))
    error('Acycle:Prewhiten:InvalidRhoSource', ...
        'RHO_SOURCE must be classic, robust, or user.');
end
source = lower(strtrim(source));
if ~ismember(source,{'classic','robust','user'})
    error('Acycle:Prewhiten:InvalidRhoSource', ...
        'RHO_SOURCE must be classic, robust, or user.');
end
options.rho_source = source;

if strcmp(source,'user')
    if ~isfield(options,'rho')
        error('Acycle:Prewhiten:MissingUserRho', ...
            'OPTIONS.rho is required when RHO_SOURCE is user.');
    end
    rho = options.rho;
    if ~(isnumeric(rho) && isreal(rho) && isscalar(rho) && ...
            isfinite(rho) && rho >= -1 && rho <= 1)
        error('Acycle:Prewhiten:InvalidUserRho', ...
            'User RHO must be a finite real scalar in [-1,1].');
    end
    options.rho = double(rho);
elseif isfield(options,'rho')
    error('Acycle:Prewhiten:InactiveUserRho', ...
        'OPTIONS.rho is valid only when RHO_SOURCE is user.');
end
end

function contract = validateSeries(data,rhoSource)
if ~((isa(data,'double') || isa(data,'single')) && ...
        ~issparse(data) && isreal(data) && ismatrix(data) && ...
        size(data,2) == 2)
    error('Acycle:Prewhiten:InvalidData', ...
        ['DATA must be a full, real SINGLE or DOUBLE N-by-2 matrix ', ...
         '[coordinate,value].']);
end
if any(~isfinite(data(:)))
    error('Acycle:Prewhiten:NonfiniteData', ...
        'Every DATA coordinate and value must be finite.');
end

inputRows = size(data,1);
if strcmp(rhoSource,'robust')
    minimumRows = 4;
else
    minimumRows = 2;
end
if inputRows < minimumRows
    error('Acycle:Prewhiten:InsufficientRows', ...
        '%s pre-whitening requires at least %d input rows.', ...
        upper(rhoSource),minimumRows);
end

coordinate = double(data(:,1));
spacing = diff(coordinate);
if any(~isfinite(spacing)) || any(spacing <= 0)
    error('Acycle:Prewhiten:InvalidCoordinate', ...
        'Coordinates must be finite, unique, and strictly increasing.');
end
sampleInterval = median(spacing);
maximumSpacingError = max(abs(spacing-sampleInterval));
relativeSpacingDeparture = maximumSpacingError/sampleInterval;
spacingTolerance = 1e-5;
if ~(isfinite(sampleInterval) && sampleInterval > 0 && ...
        isfinite(relativeSpacingDeparture))
    error('Acycle:Prewhiten:InvalidSamplingInterval', ...
        'The sampling interval is not representable as a positive DOUBLE.');
end
if relativeSpacingDeparture > spacingTolerance
    error('Acycle:Prewhiten:UnevenSampling', ...
        ['Relative spacing departure %.17g exceeds the fixed ', ...
         'near-uniform tolerance %.17g.'], ...
        relativeSpacingDeparture,spacingTolerance);
end

physicalNyquist = 1/(2*sampleInterval);
if ~(isfinite(physicalNyquist) && physicalNyquist > 0)
    error('Acycle:Prewhiten:InvalidPhysicalNyquist', ...
        'The physical Nyquist 1/(2*dt) must be finite and positive.');
end
contract = struct( ...
    'sample_interval',sampleInterval, ...
    'maximum_spacing_error',maximumSpacingError, ...
    'relative_spacing_departure',relativeSpacingDeparture, ...
    'spacing_tolerance',spacingTolerance, ...
    'physical_nyquist',physicalNyquist);
end

function [rho,fit] = robustRho(values,contract)
if ~any(values ~= values(1))
    error('Acycle:Prewhiten:InvalidVariance', ...
        'Robust AR(1) estimation requires a nonconstant value series.');
end
[periodogramPower,periodogramAngularFrequency] = periodogram(values);
periodogramPower = periodogramPower(:);
periodogramAngularFrequency = periodogramAngularFrequency(:);
if isempty(periodogramPower) || any(~isfinite(periodogramPower)) || ...
        any(periodogramPower < 0) || ...
        any(~isfinite(periodogramAngularFrequency))
    error('Acycle:Prewhiten:InvalidPeriodogram', ...
        'The robust AR(1) periodogram must be finite and nonnegative.');
end
cumulativePower = cumsum(periodogramPower);
totalPower = max(cumulativePower);
if ~(isfinite(totalPower) && totalPower > 0)
    error('Acycle:Prewhiten:InvalidVariance', ...
        'Robust AR(1) estimation requires a positive spectral power.');
end
cumulativePercent = 100*cumulativePower/totalPower;
cutoffIndex = find(cumulativePercent > 99,1,'first');
if isempty(cutoffIndex)
    error('Acycle:Prewhiten:MissingPowerCutoff', ...
        'The 99-percent cumulative-power cutoff could not be determined.');
end

periodogramFrequency = periodogramAngularFrequency/ ...
    (2*pi*contract.sample_interval);
frequencyEndpoint = periodogramFrequency(end);
cutoffFrequency = periodogramFrequency(cutoffIndex);
if ~(isfinite(frequencyEndpoint) && frequencyEndpoint > 0 && ...
        isfinite(cutoffFrequency) && cutoffFrequency >= 0)
    error('Acycle:Prewhiten:InvalidPeriodogramFrequency', ...
        'The periodogram frequency grid is invalid.');
end
if cutoffFrequency/frequencyEndpoint <= 0.85
    fitUpperFrequency = cutoffFrequency;
else
    fitUpperFrequency = frequencyEndpoint;
end

inputRows = numel(values);
timeBandwidth = 2;
if inputRows == 4
    % PMTM requires NW < N/2.  NW=1.5 is the closest supported contract at
    % the explicitly allowed four-row boundary; N>=5 retains legacy NW=2.
    timeBandwidth = 1.5;
end
[mtmPower,mtmAngularFrequency] = pmtm( ...
    values,timeBandwidth,inputRows);
mtmPower = mtmPower(:);
mtmAngularFrequency = mtmAngularFrequency(:);
frequency = mtmAngularFrequency/pi*contract.physical_nyquist;
fitMask = frequency <= fitUpperFrequency;
fitFrequency = frequency(fitMask);
fitPower = mtmPower(fitMask);
if isempty(fitPower) || numel(fitPower) ~= numel(fitFrequency) || ...
        any(~isfinite(fitPower) | fitPower <= 0) || ...
        any(~isfinite(fitFrequency))
    error('Acycle:Prewhiten:InvalidMtmFitSpectrum', ...
        'No finite positive MTM fit spectrum remains below the fit limit.');
end

smoothingBins = max(1,round(0.2*numel(fitPower)));
smoothedPower = moveMedian(fitPower,smoothingBins);
initialS0 = mean(smoothedPower);
if ~(isfinite(initialS0) && initialS0 > 0) || ...
        any(~isfinite(smoothedPower) | smoothedPower <= 0)
    error('Acycle:Prewhiten:InvalidSmoothedSpectrum', ...
        'The median-smoothed MTM fit spectrum must be finite and positive.');
end

% FITUPPERFREQUENCY selects bins only.  The transfer-function frequency in
% MINIRHOS0 is always normalized by the physical Nyquist.
[rho,fittedS0] = minirhos0( ...
    initialS0,contract.physical_nyquist,fitFrequency,smoothedPower,2);
if ~(isnumeric(rho) && isreal(rho) && isscalar(rho) && ...
        isfinite(rho) && rho > 0 && rho < 1 && ...
        isfinite(fittedS0) && fittedS0 > 0)
    error('Acycle:Prewhiten:InvalidRobustRho', ...
        'The deterministic robust AR(1) fit returned invalid parameters.');
end

fit = struct( ...
    'fit_upper_frequency',fitUpperFrequency, ...
    'fit_frequency_bins',numel(fitFrequency), ...
    'fit_smoothing_bins',smoothingBins, ...
    'fit_time_bandwidth',timeBandwidth, ...
    'fit_initial_s0',initialS0, ...
    'fit_s0',fittedS0, ...
    'minirhos_nyquist',contract.physical_nyquist, ...
    'fit_upper_frequency_policy', ...
        '99-percent-cumulative-power-with-85-percent-endpoint-fallback');
end

function fit = emptyFitMetadata()
fit = struct( ...
    'fit_upper_frequency',NaN, ...
    'fit_frequency_bins',0, ...
    'fit_smoothing_bins',0, ...
    'fit_time_bandwidth',NaN, ...
    'fit_initial_s0',NaN, ...
    'fit_s0',NaN, ...
    'minirhos_nyquist',NaN, ...
    'fit_upper_frequency_policy','not_applicable');
end
