function [result,bandPowers,meta] = acyclePowerDecomposition( ...
        data,targetBands,options)
%ACYCLEPOWERDECOMPOSITION Strict evolutionary MTM power decomposition.
%   [RESULT,BANDPOWERS,META] = ACYCLEPOWERDECOMPOSITION(DATA,BANDS,OPTIONS)
%   calculates the evolutionary multitaper power inside an explicit union
%   of target bands relative to an explicit total-frequency band. DATA is a
%   finite real N-by-2 floating-point series [coordinate,value] that must
%   already be strictly increasing and regularly sampled to relative
%   tolerance 1e-5. No sorting, duplicate merging, row removal, or implicit
%   interpolation is performed.
%
%   BANDS is a finite B-by-2 floating-point matrix [lower,upper]. Rows must
%   be ordered by increasing lower frequency and must not overlap (touching
%   endpoints are allowed). OPTIONS is a scalar structure containing exactly
%   these required fields:
%     window_length   positive first-to-last window span in coordinate units
%     step_length     positive displacement between successive window starts
%     time_bandwidth  DPSS time-half-bandwidth product accepted by PMTM
%     fft_length      explicit even integer NFFT, at least WINDOW_SAMPLES
%     total_band      finite [lower,upper] integration limits
%
%   All requested limits must satisfy 0 <= lower < upper <= the physical
%   Nyquist frequency. Every target band must lie inside TOTAL_BAND. Neither
%   limits nor FFT length are silently clipped, expanded, or inferred from a
%   random probe. Requested window and step lengths are rounded to sampling
%   intervals using positive half-away-from-zero rounding. Only complete
%   windows on the regular start grid are evaluated; an unused trailing
%   sample count is reported in META and no irregular terminal step is added.
%
%   Each window is linearly detrended against sample ordinal and evaluated by
%   PMTM on the explicit FFT grid. Powers are integrals of the returned PSD,
%   evaluated with piecewise-linear boundary interpolation and TRAPZ at the
%   exact requested frequency limits. This avoids the legacy proportional
%   index mapping error. Input values are divided by one global VALUE_SCALE
%   before analysis, so all reported powers remain comparable across windows
%   and have units input_value^2/VALUE_SCALE^2.
%
%   RESULT columns are [window_center,target_union_to_total_ratio,
%   target_union_power,total_power]. BANDPOWERS columns are window_center
%   followed by one power column for each input BANDS row. The function does
%   not use random numbers and performs no file I/O, graphics, dialogs,
%   current-folder/path changes, or workspace assignment.

narginchk(3,3);
limits = resourceLimits();
inputClass = class(data);
contract = validateSeries(data,limits);
options = validateOptions(options);
targetBands = validateBands(targetBands,limits);

working = full(double(data));
coordinates = working(:,1);
values = working(:,2);
inputRows = size(working,1);
coordinateStart = coordinates(1);
coordinateEnd = coordinates(end);
coordinateSpan = coordinateEnd-coordinateStart;
nyquist = contract.physical_nyquist;

[windowIntervals,windowSamples,effectiveWindowLength,windowRatio] = ...
    resolveWindow(options.window_length,contract.sample_interval, ...
    coordinateSpan,inputRows);
[stepSamples,effectiveStepLength,stepRatio] = resolveStep( ...
    options.step_length,contract.sample_interval);
timeBandwidth = validateTimeBandwidth( ...
    options.time_bandwidth,windowSamples);
fftLength = validateFftLength( ...
    options.fft_length,windowSamples,limits);
totalBand = validateFrequencyContract( ...
    targetBands,options.total_band,nyquist);

samplingFrequency = 1/contract.sample_interval;
frequencyResolution = samplingFrequency/fftLength;
resolutionTolerance = 64*eps(max(1,frequencyResolution));
targetBandWidths = targetBands(:,2)-targetBands(:,1);
if any(targetBandWidths < frequencyResolution-resolutionTolerance)
    first = find(targetBandWidths < ...
        frequencyResolution-resolutionTolerance,1,'first');
    error('Acycle:PowerDecomposition:TargetBandBelowResolution', ...
        ['Target band %d has width %.17g, below the explicit FFT ', ...
         'resolution %.17g. Increase FFT_LENGTH or widen the band.'], ...
        first,targetBandWidths(first),frequencyResolution);
end
totalBandWidth = totalBand(2)-totalBand(1);
if totalBandWidth < frequencyResolution-resolutionTolerance
    error('Acycle:PowerDecomposition:TotalBandBelowResolution', ...
        ['TOTAL_BAND width %.17g is below the explicit FFT resolution ', ...
         '%.17g.'],totalBandWidth,frequencyResolution);
end

lastStart = inputRows-windowSamples+1;
startIndices = (1:stepSamples:lastStart)';
endIndices = startIndices+windowSamples-1;
windowCenters = coordinates(startIndices)+ ...
    (coordinates(endIndices)-coordinates(startIndices))/2;
windowCount = numel(startIndices);
if windowCount < 1
    error('Acycle:PowerDecomposition:NoCompleteWindows', ...
        'The request produces no complete evolutionary MTM window.');
end
if windowCount > limits.maximum_window_count
    error('Acycle:PowerDecomposition:WindowCountLimitExceeded', ...
        ['The request produces %d windows; the fixed maximum is %d. ', ...
         'Increase STEP_LENGTH or shorten the input.'], ...
        windowCount,limits.maximum_window_count);
end
bandCount = size(targetBands,1);
outputElements = double(windowCount)*double(5+bandCount);
if ~isfinite(outputElements) || ...
        outputElements > limits.maximum_output_elements
    error('Acycle:PowerDecomposition:OutputElementLimitExceeded', ...
        ['RESULT and BANDPOWERS would contain %.17g values; the fixed ', ...
         'maximum is %.17g.'],outputElements,limits.maximum_output_elements);
end
nominalTaperCount = max(1,floor(2*timeBandwidth)-1);
fftWorkUnits = double(windowCount)*double(fftLength)* ...
    max(1,ceil(log2(double(fftLength))))*double(nominalTaperCount);
if ~isfinite(fftWorkUnits) || ...
        fftWorkUnits > limits.maximum_fft_work_units
    error('Acycle:PowerDecomposition:FFTWorkLimitExceeded', ...
        ['The request requires %.17g fixed multitaper FFT work units; ', ...
         'the maximum is %.17g. Increase STEP_LENGTH, reduce FFT_LENGTH ', ...
         'or TIME_BANDWIDTH, or shorten the input.'], ...
        fftWorkUnits,limits.maximum_fft_work_units);
end

valueScale = max(abs(values));
if ~(isfinite(valueScale) && valueScale > 0)
    error('Acycle:PowerDecomposition:NoValueVariation', ...
        'The value column must contain nonzero finite variation.');
end
scaledValues = values/valueScale;
inputEpsilon = double(eps(inputClass));
residualResolutionMultiplier = 16;
ratio = zeros(windowCount,1);
targetUnionPower = zeros(windowCount,1);
totalPower = zeros(windowCount,1);
individualPower = zeros(windowCount,bandCount);
detrendedPeakMagnitude = zeros(windowCount,1);
ratioClampCount = 0;
frequency = [];

for windowIndex = 1:windowCount
    segment = scaledValues(startIndices(windowIndex):endIndices(windowIndex));
    [residual,detrendedPeakMagnitude(windowIndex)] = ...
        linearDetrendSegment(segment,inputEpsilon, ...
        residualResolutionMultiplier,windowIndex);
    [power,currentFrequency] = pmtm( ...
        residual,timeBandwidth,fftLength,samplingFrequency);
    power = power(:);
    currentFrequency = currentFrequency(:);
    validateMtmSpectrum(power,currentFrequency,fftLength,nyquist,windowIndex);
    currentFrequency(1) = 0;
    currentFrequency(end) = nyquist;
    if isempty(frequency)
        frequency = currentFrequency;
    elseif ~isequal(currentFrequency,frequency)
        error('Acycle:PowerDecomposition:InconsistentFrequencyGrid', ...
            'Window %d produced a different PMTM frequency grid.', ...
            windowIndex);
    end

    totalPower(windowIndex) = integratePsdBand( ...
        frequency,power,totalBand(1),totalBand(2));
    for bandIndex = 1:bandCount
        individualPower(windowIndex,bandIndex) = integratePsdBand( ...
            frequency,power,targetBands(bandIndex,1), ...
            targetBands(bandIndex,2));
    end
    targetUnionPower(windowIndex) = sum( ...
        individualPower(windowIndex,:));
    if ~(isfinite(totalPower(windowIndex)) && totalPower(windowIndex) > 0)
        error('Acycle:PowerDecomposition:InvalidTotalPower', ...
            ['Window %d has zero or nonfinite integrated power inside ', ...
             'TOTAL_BAND.'],windowIndex);
    end
    if ~(isfinite(targetUnionPower(windowIndex)) && ...
            targetUnionPower(windowIndex) >= 0)
        error('Acycle:PowerDecomposition:InvalidTargetPower', ...
            'Window %d has invalid integrated target power.',windowIndex);
    end
    rawRatio = targetUnionPower(windowIndex)/totalPower(windowIndex);
    ratioTolerance = 4096*eps(1);
    if rawRatio < 0 || rawRatio > 1+ratioTolerance || ~isfinite(rawRatio)
        error('Acycle:PowerDecomposition:InvalidPowerRatio', ...
            ['Window %d produced target/total ratio %.17g outside ', ...
             'the reviewed interval [0,1].'],windowIndex,rawRatio);
    end
    if rawRatio > 1
        rawRatio = 1;
        ratioClampCount = ratioClampCount+1;
    end
    ratio(windowIndex) = rawRatio;
end

result = [windowCenters,ratio,targetUnionPower,totalPower];
bandPowers = [windowCenters,individualPower];
if ~isequal(size(result),[windowCount,4]) || ...
        ~isequal(size(bandPowers),[windowCount,bandCount+1]) || ...
        ~isreal(result) || ~isreal(bandPowers) || ...
        any(~isfinite(result(:))) || any(~isfinite(bandPowers(:)))
    error('Acycle:PowerDecomposition:InvalidOutput', ...
        'Power decomposition produced an invalid output matrix.');
end
if windowCount > 1 && any(diff(windowCenters) <= 0)
    error('Acycle:PowerDecomposition:InvalidWindowCenters', ...
        'Evolutionary window centers must be strictly increasing.');
end

unusedTrailingSamples = inputRows-endIndices(end);
if windowCount > 1
    centerSteps = diff(windowCenters);
    minimumCenterStep = min(centerSteps);
    maximumCenterStep = max(centerSteps);
else
    minimumCenterStep = NaN;
    maximumCenterStep = NaN;
end
warningIds = cell(0,1);
warningMessages = cell(0,1);
if contract.spacing_departure_above_roundoff
    warningIds{end+1,1} = ...
        'Acycle:PowerDecomposition:SpacingDepartureWithinTolerance';
    warningMessages{end+1,1} = sprintf( ...
        ['Coordinate spacing departure %.17g exceeds roundoff but ', ...
         'remains within the accepted relative tolerance %.17g. No ', ...
         'interpolation was performed.'], ...
        contract.maximum_spacing_error,contract.spacing_tolerance);
end

bandPowerColumns = cell(1,bandCount+1);
bandPowerColumns{1} = 'window_center';
for bandIndex = 1:bandCount
    bandPowerColumns{bandIndex+1} = sprintf( ...
        'target_band_%d_power',bandIndex);
end
meta = struct( ...
    'version','power-decomposition-v1', ...
    'method','evolutionary_adaptive_multitaper_band_power_ratio', ...
    'reviewed_subset','deterministic_unpadded_complete_windows', ...
    'input_policy', ...
        'strict_finite_real_full_single_or_double_increasing_near_uniform', ...
    'input_rows',inputRows, ...
    'input_columns',2, ...
    'output_rows',windowCount, ...
    'output_columns',4, ...
    'result_columns',{{'window_center','target_union_to_total_ratio', ...
        'target_union_power','total_power'}}, ...
    'band_power_columns',{bandPowerColumns}, ...
    'coordinate_start',coordinateStart, ...
    'coordinate_end',coordinateEnd, ...
    'coordinate_span',coordinateSpan, ...
    'sample_interval',contract.sample_interval, ...
    'sample_interval_source','median_coordinate_spacing', ...
    'maximum_spacing_error',contract.maximum_spacing_error, ...
    'relative_spacing_departure',contract.relative_spacing_departure, ...
    'spacing_tolerance',contract.spacing_tolerance, ...
    'spacing_roundoff_absolute_tolerance', ...
        contract.roundoff_absolute_tolerance, ...
    'spacing_departure_above_roundoff', ...
        contract.spacing_departure_above_roundoff, ...
    'physical_nyquist',nyquist, ...
    'target_bands',targetBands, ...
    'target_band_count',bandCount, ...
    'target_band_policy','ordered_nonoverlapping_union', ...
    'target_band_widths',targetBandWidths, ...
    'target_band_widths_in_fft_bins', ...
        targetBandWidths/frequencyResolution, ...
    'total_band',totalBand, ...
    'total_band_width',totalBandWidth, ...
    'requested_window_length',options.window_length, ...
    'window_length_interpretation','first_to_last_coordinate_span', ...
    'window_interval_ratio',windowRatio, ...
    'window_interval_rounding','nearest_integer_half_away_from_zero', ...
    'window_intervals',windowIntervals, ...
    'window_samples',windowSamples, ...
    'effective_window_length',effectiveWindowLength, ...
    'window_length_quantization_error', ...
        effectiveWindowLength-options.window_length, ...
    'requested_step_length',options.step_length, ...
    'step_interval_ratio',stepRatio, ...
    'step_interval_rounding','nearest_integer_half_away_from_zero', ...
    'step_samples',stepSamples, ...
    'effective_step_length',effectiveStepLength, ...
    'step_length_quantization_error', ...
        effectiveStepLength-options.step_length, ...
    'window_start_index_policy','one_plus_k_times_step_samples', ...
    'window_endpoint_policy','complete_windows_only_no_terminal_append', ...
    'window_center_semantics', ...
        'arithmetic_mean_of_actual_first_and_last_coordinates', ...
    'window_count',windowCount, ...
    'last_window_end_index',endIndices(end), ...
    'unused_trailing_samples',unusedTrailingSamples, ...
    'minimum_actual_center_step',minimumCenterStep, ...
    'maximum_actual_center_step',maximumCenterStep, ...
    'time_bandwidth',timeBandwidth, ...
    'nominal_taper_count',nominalTaperCount, ...
    'multitaper_weighting','pmtm_default_adaptive', ...
    'segment_detrend','linear_least_squares_against_sample_ordinal', ...
    'value_scale',valueScale, ...
    'power_units','input_value_squared_divided_by_value_scale_squared', ...
    'input_epsilon',inputEpsilon, ...
    'residual_resolution_multiplier',residualResolutionMultiplier, ...
    'minimum_detrended_peak_magnitude',min(detrendedPeakMagnitude), ...
    'maximum_detrended_peak_magnitude',max(detrendedPeakMagnitude), ...
    'fft_length',fftLength, ...
    'frequency_bins',numel(frequency), ...
    'frequency_resolution',frequencyResolution, ...
    'calculation_frequency_minimum',frequency(1), ...
    'calculation_frequency_maximum',frequency(end), ...
    'frequency_boundary_policy', ...
        'exact_limits_piecewise_linear_psd_interpolation', ...
    'power_integration','trapezoidal_integral_of_pmtm_psd', ...
    'minimum_target_union_power',min(targetUnionPower), ...
    'maximum_target_union_power',max(targetUnionPower), ...
    'minimum_total_power',min(totalPower), ...
    'maximum_total_power',max(totalPower), ...
    'minimum_power_ratio',min(ratio), ...
    'maximum_power_ratio',max(ratio), ...
    'power_ratio_roundoff_tolerance',ratioTolerance, ...
    'ratio_roundoff_clamp_count',ratioClampCount, ...
    'interpolated',false, ...
    'sorted',false, ...
    'removed_rows',0, ...
    'edge_padding','none', ...
    'toolbox_dependency','Signal Processing Toolbox', ...
    'maximum_input_rows',limits.maximum_input_rows, ...
    'maximum_target_bands',limits.maximum_target_bands, ...
    'maximum_fft_length',limits.maximum_fft_length, ...
    'maximum_window_count',limits.maximum_window_count, ...
    'maximum_output_elements',limits.maximum_output_elements, ...
    'fft_work_units',fftWorkUnits, ...
    'maximum_fft_work_units',limits.maximum_fft_work_units, ...
    'warning_ids',{warningIds}, ...
    'warnings',{warningMessages}, ...
    'file_io',false, ...
    'graphics',false, ...
    'dialogs',false, ...
    'current_folder_changes',false, ...
    'path_changes',false, ...
    'random_number_generation',false, ...
    'base_workspace_assignment',false, ...
    'side_effect_policy','none');
end

function limits = resourceLimits()
limits = struct( ...
    'maximum_input_rows',1e6, ...
    'maximum_target_bands',64, ...
    'maximum_fft_length',2^20, ...
    'maximum_window_count',1e4, ...
    'maximum_output_elements',2e6, ...
    'maximum_fft_work_units',1e10);
end

function contract = validateSeries(data,limits)
if ~((isa(data,'double') || isa(data,'single')) && ...
        ~issparse(data) && isreal(data) && ismatrix(data) && ...
        size(data,2) == 2)
    error('Acycle:PowerDecomposition:InvalidData', ...
        ['DATA must be a full real SINGLE or DOUBLE N-by-2 matrix ', ...
         '[coordinate,value].']);
end
inputRows = size(data,1);
if inputRows < 8
    error('Acycle:PowerDecomposition:TooFewRows', ...
        'Power decomposition requires at least eight input rows.');
end
if inputRows > limits.maximum_input_rows
    error('Acycle:PowerDecomposition:InputRowLimitExceeded', ...
        'DATA exceeds the fixed maximum of %d rows.', ...
        limits.maximum_input_rows);
end
if any(~isfinite(data(:)))
    error('Acycle:PowerDecomposition:NonfiniteData', ...
        'Every DATA coordinate and value must be finite.');
end
coordinates = double(data(:,1));
spacing = diff(coordinates);
if any(~isfinite(spacing))
    error('Acycle:PowerDecomposition:UnrepresentableSpacing', ...
        'Every coordinate spacing must be representable as finite DOUBLE.');
end
if any(spacing <= 0)
    error('Acycle:PowerDecomposition:CoordinatesNotStrictlyIncreasing', ...
        ['DATA coordinates must already be sorted, unique, and strictly ', ...
         'increasing.']);
end
sampleInterval = median(spacing);
maximumSpacingError = max(abs(spacing-sampleInterval));
relativeSpacingDeparture = maximumSpacingError/sampleInterval;
spacingTolerance = 1e-5;
if ~(isfinite(sampleInterval) && sampleInterval > 0 && ...
        isfinite(relativeSpacingDeparture)) || ...
        relativeSpacingDeparture > spacingTolerance
    error('Acycle:PowerDecomposition:UnevenSampling', ...
        ['Relative spacing departure %.17g exceeds the fixed tolerance ', ...
         '%.17g. Interpolate explicitly before power decomposition.'], ...
        relativeSpacingDeparture,spacingTolerance);
end
coordinateScale = max([1;abs(coordinates);abs(sampleInterval)]);
roundoffTolerance = 128*eps(coordinateScale);
nyquist = 1/(2*sampleInterval);
if ~(isfinite(nyquist) && nyquist > 0)
    error('Acycle:PowerDecomposition:InvalidNyquist', ...
        'The physical Nyquist frequency must be finite and positive.');
end
contract = struct( ...
    'sample_interval',sampleInterval, ...
    'maximum_spacing_error',maximumSpacingError, ...
    'relative_spacing_departure',relativeSpacingDeparture, ...
    'spacing_tolerance',spacingTolerance, ...
    'roundoff_absolute_tolerance',roundoffTolerance, ...
    'spacing_departure_above_roundoff', ...
        maximumSpacingError > roundoffTolerance, ...
    'physical_nyquist',nyquist);
end

function options = validateOptions(options)
if ~isstruct(options) || ~isscalar(options)
    error('Acycle:PowerDecomposition:InvalidOptions', ...
        'OPTIONS must be a scalar structure.');
end
allowed = {'window_length','step_length','time_bandwidth', ...
    'fft_length','total_band'};
unknown = setdiff(fieldnames(options),allowed);
if ~isempty(unknown)
    error('Acycle:PowerDecomposition:UnknownOption', ...
        'Unknown power-decomposition option: %s.',unknown{1});
end
for index = 1:numel(allowed)
    if ~isfield(options,allowed{index}) || isempty(options.(allowed{index}))
        error('Acycle:PowerDecomposition:MissingOption', ...
            'Required option %s is missing.',upper(allowed{index}));
    end
end
options.window_length = positiveFiniteScalar( ...
    options.window_length,'window_length');
options.step_length = positiveFiniteScalar( ...
    options.step_length,'step_length');
end

function bands = validateBands(bands,limits)
if ~((isa(bands,'double') || isa(bands,'single')) && ...
        ~issparse(bands) && isreal(bands) && ismatrix(bands) && ...
        size(bands,2) == 2)
    error('Acycle:PowerDecomposition:InvalidTargetBands', ...
        ['BANDS must be a full real SINGLE or DOUBLE B-by-2 matrix ', ...
         '[lower,upper].']);
end
if isempty(bands)
    error('Acycle:PowerDecomposition:EmptyTargetBands', ...
        'BANDS must contain at least one target-frequency row.');
end
if size(bands,1) > limits.maximum_target_bands
    error('Acycle:PowerDecomposition:TargetBandLimitExceeded', ...
        'BANDS exceeds the fixed maximum of %d rows.', ...
        limits.maximum_target_bands);
end
if any(~isfinite(bands(:)))
    error('Acycle:PowerDecomposition:NonfiniteTargetBands', ...
        'Every target-band limit must be finite.');
end
bands = full(double(bands));
if any(bands(:,1) < 0) || any(bands(:,2) <= bands(:,1))
    error('Acycle:PowerDecomposition:InvalidTargetBandOrder', ...
        'Every target band must satisfy 0 <= LOWER < UPPER.');
end
if size(bands,1) > 1
    if any(diff(bands(:,1)) <= 0)
        error('Acycle:PowerDecomposition:TargetBandsNotOrdered', ...
            'BANDS rows must be ordered by strictly increasing LOWER.');
    end
    if any(bands(2:end,1) < bands(1:end-1,2))
        error('Acycle:PowerDecomposition:OverlappingTargetBands', ...
            'Target bands must not overlap; merge overlaps explicitly.');
    end
end
end

function total = validateFrequencyContract(bands,total,nyquist)
if ~(isnumeric(total) && ~islogical(total) && isreal(total) && ...
        isvector(total) && numel(total) == 2 && all(isfinite(total)))
    error('Acycle:PowerDecomposition:InvalidTotalBand', ...
        'TOTAL_BAND must be a finite real two-element numeric vector.');
end
total = double(total(:).');
if total(1) < 0 || total(2) <= total(1)
    error('Acycle:PowerDecomposition:InvalidTotalBandOrder', ...
        'TOTAL_BAND must satisfy 0 <= LOWER < UPPER.');
end
if total(2) > nyquist
    error('Acycle:PowerDecomposition:FrequencyAboveNyquist', ...
        ['TOTAL_BAND upper frequency %.17g exceeds the physical ', ...
         'Nyquist frequency %.17g.'],total(2),nyquist);
end
if any(bands(:,2) > nyquist)
    first = find(bands(:,2) > nyquist,1,'first');
    error('Acycle:PowerDecomposition:FrequencyAboveNyquist', ...
        ['Target band %d upper frequency %.17g exceeds the physical ', ...
         'Nyquist frequency %.17g.'],first,bands(first,2),nyquist);
end
if any(bands(:,1) < total(1)) || any(bands(:,2) > total(2))
    error('Acycle:PowerDecomposition:TargetOutsideTotalBand', ...
        'Every target band must lie completely inside TOTAL_BAND.');
end
end

function [intervals,samples,effective,ratio] = resolveWindow( ...
        requested,dt,span,inputRows)
if requested > span
    error('Acycle:PowerDecomposition:WindowLongerThanSpan', ...
        'WINDOW_LENGTH %.17g exceeds the DATA coordinate span %.17g.', ...
        requested,span);
end
ratio = requested/dt;
intervals = roundPositiveHalfAway(ratio);
samples = intervals+1;
if samples < 8
    error('Acycle:PowerDecomposition:WindowTooShort', ...
        ['WINDOW_LENGTH resolves to %d samples; power decomposition ', ...
         'requires at least eight.'],samples);
end
if samples > inputRows
    error('Acycle:PowerDecomposition:WindowSampleCountTooLarge', ...
        ['WINDOW_LENGTH resolves to %d samples, exceeding the %d ', ...
         'input rows.'],samples,inputRows);
end
effective = intervals*dt;
end

function [samples,effective,ratio] = resolveStep(requested,dt)
ratio = requested/dt;
samples = roundPositiveHalfAway(ratio);
if samples < 1
    error('Acycle:PowerDecomposition:StepTooShort', ...
        ['STEP_LENGTH resolves to zero samples. Increase it to at least ', ...
         'half the sample interval.']);
end
effective = samples*dt;
if ~(isfinite(effective) && effective > 0)
    error('Acycle:PowerDecomposition:InvalidEffectiveStep', ...
        'The effective step length must be finite and positive.');
end
end

function value = validateTimeBandwidth(value,windowSamples)
value = positiveFiniteScalar(value,'time_bandwidth');
if value < 0.5 || value >= windowSamples/2
    error('Acycle:PowerDecomposition:TimeBandwidthOutOfRange', ...
        ['TIME_BANDWIDTH must be at least 0.5 and strictly less than ', ...
         'WINDOW_SAMPLES/2 (%.17g).'],windowSamples/2);
end
end

function value = validateFftLength(value,windowSamples,limits)
if ~(isnumeric(value) && ~islogical(value) && isreal(value) && ...
        isscalar(value) && isfinite(value) && value == fix(value) && ...
        value >= windowSamples && mod(value,2) == 0)
    error('Acycle:PowerDecomposition:InvalidFftLength', ...
        ['FFT_LENGTH must be a finite even integer at least as large ', ...
         'as WINDOW_SAMPLES (%d).'],windowSamples);
end
value = double(value);
if value > limits.maximum_fft_length
    error('Acycle:PowerDecomposition:FFTLengthLimitExceeded', ...
        'FFT_LENGTH exceeds the fixed maximum of %d.', ...
        limits.maximum_fft_length);
end
end

function rounded = roundPositiveHalfAway(value)
if ~(isfinite(value) && value >= 0)
    error('Acycle:PowerDecomposition:InvalidLengthRatio', ...
        'A physical length/sample-interval ratio is invalid.');
end
rounded = floor(value+0.5);
end

function value = positiveFiniteScalar(value,name)
if ~(isnumeric(value) && ~islogical(value) && isreal(value) && ...
        isscalar(value) && isfinite(value) && value > 0)
    error('Acycle:PowerDecomposition:InvalidNumericOption', ...
        '%s must be a finite positive real numeric scalar.',upper(name));
end
value = double(value);
end

function [residual,peakMagnitude] = linearDetrendSegment( ...
        segment,inputEpsilon,resolutionMultiplier,windowIndex)
minimumValue = min(segment);
maximumValue = max(segment);
offset = minimumValue/2+maximumValue/2;
centered = segment-offset;
localScale = max(abs(centered));
if ~(isfinite(localScale) && localScale > 0)
    error('Acycle:PowerDecomposition:ConstantWindow', ...
        'Window %d has no finite value variation.',windowIndex);
end
sampleOrdinal = linspace(-1,1,numel(segment))';
design = [ones(numel(segment),1),sampleOrdinal];
scaled = centered/localScale;
residual = (scaled-design*(design\scaled))*localScale;
peakMagnitude = max(abs(residual));
resolutionThreshold = resolutionMultiplier*inputEpsilon* ...
    max(1,max(abs(segment)));
if ~(isfinite(peakMagnitude) && peakMagnitude > resolutionThreshold)
    error('Acycle:PowerDecomposition:UnresolvableDetrendedWindow', ...
        ['Window %d has no detrended variation above the fixed ', ...
         'floating-point resolution threshold %.17g.'], ...
        windowIndex,resolutionThreshold);
end
if any(~isfinite(residual))
    error('Acycle:PowerDecomposition:NonfiniteDetrendedWindow', ...
        'Window %d linear detrending produced a nonfinite value.', ...
        windowIndex);
end
end

function validateMtmSpectrum(power,frequency,fftLength,nyquist,windowIndex)
expectedBins = fftLength/2+1;
if numel(power) ~= expectedBins || numel(frequency) ~= expectedBins
    error('Acycle:PowerDecomposition:UnexpectedPmtmLength', ...
        ['Window %d PMTM returned %d PSD bins and %d frequency bins; ', ...
         '%d were required.'],windowIndex,numel(power), ...
        numel(frequency),expectedBins);
end
if ~isreal(power) || ~isreal(frequency) || ...
        any(~isfinite(power)) || any(~isfinite(frequency)) || ...
        any(power < 0) || any(diff(frequency) <= 0)
    error('Acycle:PowerDecomposition:InvalidPmtmSpectrum', ...
        'Window %d PMTM returned an invalid one-sided PSD.',windowIndex);
end
endpointTolerance = 256*eps(max(1,nyquist));
if abs(frequency(1)) > endpointTolerance || ...
        abs(frequency(end)-nyquist) > endpointTolerance
    error('Acycle:PowerDecomposition:UnexpectedFrequencyEndpoints', ...
        ['Window %d PMTM frequency grid does not span DC through the ', ...
         'physical Nyquist frequency.'],windowIndex);
end
end

function integrated = integratePsdBand(frequency,power,lower,upper)
interior = frequency > lower & frequency < upper;
integrationFrequency = [lower;frequency(interior);upper];
integrationPower = interp1(frequency,power,integrationFrequency,'linear');
if any(~isfinite(integrationPower)) || any(integrationPower < 0)
    error('Acycle:PowerDecomposition:BandInterpolationFailed', ...
        ['Piecewise-linear PSD interpolation failed for band ', ...
         '[%.17g, %.17g].'],lower,upper);
end
integrated = trapz(integrationFrequency,integrationPower);
if ~(isfinite(integrated) && integrated >= 0)
    error('Acycle:PowerDecomposition:BandIntegrationFailed', ...
        'PSD integration failed for band [%.17g, %.17g].',lower,upper);
end
end
