function [result,windows,meta] = acycleDynamicFilter( ...
        data,lowerControlPoints,upperControlPoints,options)
%ACYCLEDYNAMICFILTER Deterministic coordinate-varying Gaussian band-pass.
%   [RESULT,WINDOWS,META] = ACYCLEDYNAMICFILTER(DATA,LOWER,UPPER,OPTIONS)
%   filters a finite real N-by-2 series [coordinate,value] with an explicit
%   coordinate-varying passband. DATA must already be strictly increasing
%   and regularly sampled to the fixed relative spacing tolerance 1e-5;
%   rows are never sorted, merged, removed, or interpolated.
%
%   LOWER and UPPER are finite K-by-2 floating-point matrices whose columns
%   are [coordinate,frequency]. Each coordinate vector must be strictly
%   increasing and lie inside the DATA domain. A one-row control is
%   constant. Otherwise each path is linearly interpolated between control
%   points and held constant beyond its first and last point. The complete
%   piecewise-linear paths must satisfy
%       0 < lower_frequency < upper_frequency < physical_Nyquist.
%
%   OPTIONS is a scalar structure containing exactly these required fields:
%     window_length  positive first-to-last window span in coordinate units
%     step_length    positive displacement between successive window starts
%
%   Physical lengths are divided by MEDIAN(DIFF(DATA(:,1))) and rounded to
%   the nearest sampling interval (positive half ties away from zero).
%   WINDOW_LENGTH then gains one endpoint sample and must contain at least
%   eight samples. STEP_LENGTH must resolve to at least one sample and may
%   not exceed the window sample count, so no coverage gaps are possible.
%   A terminal window ending on the final sample is appended when the
%   regular start grid would otherwise leave an uncovered tail.
%
%   Each window is locally mean-centred, multiplied by the square root of a
%   strictly-positive half-sample-shifted Hann weight, Gaussian filtered in
%   an explicitly zero-padded FFT, multiplied by the same synthesis weight,
%   and overlap-added. The Gaussian lower and upper frequencies are exact
%   half-power (-3 dB) points. The output is divided by the sum of synthesis
%   weights, never by the count of nonzero filtered values.
%
%   RESULT columns are [coordinate,filtered_value,coverage_count,
%   coverage_weight]. WINDOWS columns are [window_center,lower_frequency,
%   upper_frequency,center_frequency,window_start_coordinate,
%   window_end_coordinate,window_start_index,window_end_index]. No files,
%   graphics, dialogs, current-folder/path changes, workspace assignment,
%   or random-number generation occur.
%
%   Algorithm lineage: dynamic filtering by Nicolas Thibault and Giovanni
%   Rizzi (2019), adapted for Acycle Frequency Stabilization by Mingsong Li
%   (June 2020).

narginchk(4,4);
limits = resourceLimits();
contract = validateSeries(data,limits);
options = validateOptions(options);

working = full(double(data));
coordinates = working(:,1);
values = working(:,2);
inputRows = size(working,1);
coordinateStart = coordinates(1);
coordinateEnd = coordinates(end);
coordinateSpan = coordinateEnd-coordinateStart;
nyquist = contract.physical_nyquist;

lowerControlPoints = validateControlPoints( ...
    lowerControlPoints,'lower',coordinateStart,coordinateEnd,limits);
upperControlPoints = validateControlPoints( ...
    upperControlPoints,'upper',coordinateStart,coordinateEnd,limits);
[pathCheckCoordinates,pathCheckLower,pathCheckUpper] = validatePassbandPaths( ...
    lowerControlPoints,upperControlPoints,coordinateStart,coordinateEnd, ...
    nyquist);

[windowIntervals,windowSamples,effectiveWindowLength,windowRatio] = ...
    resolveWindow(options.window_length,contract.sample_interval, ...
    coordinateSpan,inputRows);
[stepSamples,effectiveStepLength,stepRatio] = resolveStep( ...
    options.step_length,contract.sample_interval,windowSamples);

lastStart = inputRows-windowSamples+1;
startIndices = (1:stepSamples:lastStart)';
terminalWindowAppended = startIndices(end) ~= lastStart;
if terminalWindowAppended
    startIndices(end+1,1) = lastStart;
end
endIndices = startIndices+windowSamples-1;
windowCenters = coordinates(startIndices)+ ...
    (coordinates(endIndices)-coordinates(startIndices))/2;
windowCount = numel(startIndices);
if windowCount > limits.maximum_window_count
    error('Acycle:DynamicFilter:WindowCountLimitExceeded', ...
        ['The request produces %d windows; the fixed maximum is %d. ', ...
         'Increase STEP_LENGTH or shorten the input.'], ...
        windowCount,limits.maximum_window_count);
end

lowerFrequency = interpolateClamped( ...
    lowerControlPoints,windowCenters);
upperFrequency = interpolateClamped( ...
    upperControlPoints,windowCenters);
centerFrequency = lowerFrequency+(upperFrequency-lowerFrequency)/2;
if any(~isfinite(centerFrequency))
    error('Acycle:DynamicFilter:UnrepresentableCenterFrequency', ...
        'A passband center is not representable as finite DOUBLE.');
end

minimumFftLength = 2*windowSamples-1;
fftLength = 2^nextpow2(minimumFftLength);
if ~(isfinite(fftLength) && fftLength >= minimumFftLength && ...
        fftLength == fix(fftLength) && mod(fftLength,2) == 0)
    error('Acycle:DynamicFilter:InvalidFftLength', ...
        'The deterministic FFT length is invalid.');
end
if fftLength > limits.maximum_fft_length
    error('Acycle:DynamicFilter:FFTLengthLimitExceeded', ...
        ['The effective window requires FFT length %d; the fixed ', ...
         'maximum is %d.'],fftLength,limits.maximum_fft_length);
end
frequencyResolution = 1/(fftLength*contract.sample_interval);
passbandWidth = upperFrequency-lowerFrequency;
resolutionTolerance = 64*eps(max(1,frequencyResolution));
if any(passbandWidth < frequencyResolution-resolutionTolerance)
    first = find(passbandWidth < ...
        frequencyResolution-resolutionTolerance,1,'first');
    error('Acycle:DynamicFilter:PassbandBelowFrequencyResolution', ...
        ['Window %d has passband width %.17g, below the deterministic ', ...
         'FFT resolution %.17g. Increase WINDOW_LENGTH or widen the ', ...
         'passband.'],first,passbandWidth(first),frequencyResolution);
end

outputElements = double(inputRows)*4+double(windowCount)*8;
if ~isfinite(outputElements) || ...
        outputElements > limits.maximum_output_elements
    error('Acycle:DynamicFilter:OutputElementLimitExceeded', ...
        ['RESULT and WINDOWS would contain %.17g values; the fixed ', ...
         'maximum is %.17g.'],outputElements,limits.maximum_output_elements);
end
fftWorkUnits = double(windowCount)*double(fftLength)* ...
    max(1,ceil(log2(double(fftLength))));
if ~isfinite(fftWorkUnits) || ...
        fftWorkUnits > limits.maximum_fft_work_units
    error('Acycle:DynamicFilter:FFTWorkLimitExceeded', ...
        ['The request requires %.17g fixed FFT work units; the maximum ', ...
         'is %.17g. Increase STEP_LENGTH or reduce WINDOW_LENGTH.'], ...
        fftWorkUnits,limits.maximum_fft_work_units);
end

valueScale = max(abs(values));
if valueScale == 0
    scaledValues = zeros(inputRows,1);
else
    scaledValues = values/valueScale;
end
weight = halfSampleShiftedHann(windowSamples);
analysisWeight = sqrt(weight);
coverageWeight = zeros(inputRows,1);
coverageCount = zeros(inputRows,1);
filteredAccumulator = zeros(inputRows,1);
absoluteBin = min((0:fftLength-1)',(fftLength:-1:1)');
absoluteFrequency = absoluteBin*frequencyResolution;
maximumImaginaryResidual = 0;
maximumImaginaryTolerance = 0;
minimumPeakResponse = Inf;
maximumPeakResponse = 0;

for windowIndex = 1:windowCount
    indices = startIndices(windowIndex):endIndices(windowIndex);
    segment = scaledValues(indices);
    localMean = mean(segment);
    centeredSegment = segment-localMean;
    if any(~isfinite(centeredSegment))
        error('Acycle:DynamicFilter:UnrepresentableCentering', ...
            'Local mean centering failed in window %d.',windowIndex);
    end

    halfBandwidth = passbandWidth(windowIndex)/2;
    normalizedOffset = ...
        (absoluteFrequency-centerFrequency(windowIndex))/halfBandwidth;
    response = exp(-log(sqrt(2))*normalizedOffset.^2);
    if any(~isfinite(response)) || any(response < 0) || any(response > 1)
        error('Acycle:DynamicFilter:InvalidFrequencyResponse', ...
            'Window %d produced an invalid Gaussian response.',windowIndex);
    end
    oneSidedPeak = max(response(1:fftLength/2+1));
    minimumPeakResponse = min(minimumPeakResponse,oneSidedPeak);
    maximumPeakResponse = max(maximumPeakResponse,oneSidedPeak);

    coefficients = fft(centeredSegment.*analysisWeight,fftLength);
    timeDomain = ifft(coefficients.*response);
    imaginaryResidual = max(abs(imag(timeDomain)));
    imaginaryTolerance = 2048*eps(max(1,max(abs(timeDomain))));
    maximumImaginaryResidual = max( ...
        maximumImaginaryResidual,imaginaryResidual);
    maximumImaginaryTolerance = max( ...
        maximumImaginaryTolerance,imaginaryTolerance);
    if imaginaryResidual > imaginaryTolerance
        error('Acycle:DynamicFilter:NonHermitianFilterResult', ...
            ['Window %d inverse FFT has imaginary residual %.17g, ', ...
             'above tolerance %.17g.'], ...
            windowIndex,imaginaryResidual,imaginaryTolerance);
    end
    localFiltered = real(timeDomain(1:windowSamples)).*analysisWeight;
    if any(~isfinite(localFiltered))
        error('Acycle:DynamicFilter:NonfiniteWindowOutput', ...
            'Window %d produced a nonfinite filtered value.',windowIndex);
    end
    filteredAccumulator(indices) = ...
        filteredAccumulator(indices)+localFiltered;
    coverageWeight(indices) = coverageWeight(indices)+weight;
    coverageCount(indices) = coverageCount(indices)+1;
end

if any(~isfinite(coverageWeight)) || any(coverageWeight <= 0) || ...
        any(coverageCount < 1)
    error('Acycle:DynamicFilter:IncompleteCoverage', ...
        ['The deterministic window schedule failed to cover every ', ...
         'input sample with positive synthesis weight.']);
end
filteredNormalized = filteredAccumulator./coverageWeight;
if valueScale == 0
    filtered = zeros(inputRows,1);
else
    filtered = filteredNormalized*valueScale;
end
if any(~isfinite(filtered))
    error('Acycle:DynamicFilter:NonfiniteOutput', ...
        ['The filtered result is not representable as finite DOUBLE. ', ...
         'Rescale extreme input values.']);
end

result = [coordinates,filtered,coverageCount,coverageWeight];
windows = [windowCenters,lowerFrequency,upperFrequency,centerFrequency, ...
    coordinates(startIndices),coordinates(endIndices), ...
    double(startIndices),double(endIndices)];
if ~isequal(size(result),[inputRows,4]) || ...
        ~isequal(size(windows),[windowCount,8]) || ...
        any(~isfinite(result(:))) || any(~isfinite(windows(:)))
    error('Acycle:DynamicFilter:InvalidOutput', ...
        'Dynamic filtering produced an invalid output matrix.');
end

if windowCount > 1
    startSteps = diff(startIndices);
    minimumStartStepSamples = min(startSteps);
    maximumStartStepSamples = max(startSteps);
else
    minimumStartStepSamples = NaN;
    maximumStartStepSamples = NaN;
end
warningIds = cell(0,1);
warningMessages = cell(0,1);
if contract.spacing_departure_above_roundoff
    warningIds{end+1,1} = ...
        'Acycle:DynamicFilter:SpacingDepartureWithinTolerance';
    warningMessages{end+1,1} = sprintf( ...
        ['Coordinate spacing departure %.17g exceeds roundoff but ', ...
         'remains within the accepted relative tolerance %.17g. No ', ...
         'interpolation was performed.'], ...
        contract.maximum_spacing_error,contract.spacing_tolerance);
end

meta = struct( ...
    'version','dynamic-filter-v1', ...
    'method','windowed_overlap_add_gaussian_bandpass', ...
    'input_policy', ...
        'strict_finite_real_full_single_or_double_increasing_near_uniform', ...
    'input_rows',inputRows, ...
    'input_columns',2, ...
    'output_rows',inputRows, ...
    'output_columns',4, ...
    'result_columns',{{'coordinate','filtered_value', ...
        'coverage_count','coverage_weight'}}, ...
    'window_rows',windowCount, ...
    'window_columns',8, ...
    'window_result_columns',{{'window_center','lower_frequency', ...
        'upper_frequency','center_frequency','window_start_coordinate', ...
        'window_end_coordinate','window_start_index','window_end_index'}}, ...
    'coordinate_start',coordinateStart, ...
    'coordinate_end',coordinateEnd, ...
    'coordinate_span',coordinateSpan, ...
    'sample_interval',contract.sample_interval, ...
    'sample_interval_source','median_coordinate_spacing', ...
    'maximum_spacing_error',contract.maximum_spacing_error, ...
    'relative_spacing_departure',contract.relative_spacing_departure, ...
    'spacing_tolerance',contract.spacing_tolerance, ...
    'spacing_roundoff_absolute_tolerance', ...
        contract.roundoff_absolute_tolerance, ...
    'spacing_departure_above_roundoff', ...
        contract.spacing_departure_above_roundoff, ...
    'physical_nyquist',nyquist, ...
    'lower_control_points',lowerControlPoints, ...
    'upper_control_points',upperControlPoints, ...
    'lower_control_point_count',size(lowerControlPoints,1), ...
    'upper_control_point_count',size(upperControlPoints,1), ...
    'control_interpolation','piecewise_linear_with_constant_end_hold', ...
    'passband_validation_coordinates',pathCheckCoordinates, ...
    'passband_validation_lower_frequency',pathCheckLower, ...
    'passband_validation_upper_frequency',pathCheckUpper, ...
    'requested_window_length',options.window_length, ...
    'window_length_interpretation','first_to_last_coordinate_span', ...
    'window_interval_ratio',windowRatio, ...
    'window_interval_rounding','nearest_integer_half_away_from_zero', ...
    'window_intervals',windowIntervals, ...
    'window_samples',windowSamples, ...
    'effective_window_length',effectiveWindowLength, ...
    'window_length_quantization_error', ...
        effectiveWindowLength-options.window_length, ...
    'requested_step_length',options.step_length, ...
    'step_interval_ratio',stepRatio, ...
    'step_interval_rounding','nearest_integer_half_away_from_zero', ...
    'step_samples',stepSamples, ...
    'effective_step_length',effectiveStepLength, ...
    'step_length_quantization_error', ...
        effectiveStepLength-options.step_length, ...
    'terminal_window_appended',terminalWindowAppended, ...
    'terminal_window_policy','append_last_full_window_to_cover_final_sample', ...
    'minimum_start_step_samples',minimumStartStepSamples, ...
    'maximum_start_step_samples',maximumStartStepSamples, ...
    'window_count',windowCount, ...
    'minimum_window_lower_frequency',min(lowerFrequency), ...
    'maximum_window_lower_frequency',max(lowerFrequency), ...
    'minimum_window_upper_frequency',min(upperFrequency), ...
    'maximum_window_upper_frequency',max(upperFrequency), ...
    'minimum_window_passband_width',min(passbandWidth), ...
    'maximum_window_passband_width',max(passbandWidth), ...
    'minimum_passband_width_bins',min(passbandWidth)/frequencyResolution, ...
    'frequency_response','symmetric_gaussian_half_power_edges', ...
    'half_power_gain',1/sqrt(2), ...
    'fft_padding_policy','next_power_of_two_at_least_2_window_samples_minus_1', ...
    'minimum_fft_length',minimumFftLength, ...
    'fft_length',fftLength, ...
    'frequency_resolution',frequencyResolution, ...
    'calculation_frequency_minimum',0, ...
    'calculation_frequency_maximum',nyquist, ...
    'minimum_peak_response_gain',minimumPeakResponse, ...
    'maximum_peak_response_gain',maximumPeakResponse, ...
    'analysis_window','sqrt_half_sample_shifted_hann', ...
    'synthesis_window','sqrt_half_sample_shifted_hann', ...
    'overlap_add_normalization','sum_of_half_sample_shifted_hann_weights', ...
    'local_centering','per_window_arithmetic_mean_after_global_scaling', ...
    'value_scale',valueScale, ...
    'minimum_coverage_count',min(coverageCount), ...
    'maximum_coverage_count',max(coverageCount), ...
    'minimum_coverage_weight',min(coverageWeight), ...
    'maximum_coverage_weight',max(coverageWeight), ...
    'maximum_ifft_imaginary_residual',maximumImaginaryResidual, ...
    'maximum_ifft_imaginary_tolerance',maximumImaginaryTolerance, ...
    'interpolated',false, ...
    'sorted',false, ...
    'removed_rows',0, ...
    'toolbox_dependency','MATLAB_only', ...
    'maximum_input_rows',limits.maximum_input_rows, ...
    'maximum_control_points',limits.maximum_control_points, ...
    'maximum_fft_length',limits.maximum_fft_length, ...
    'maximum_window_count',limits.maximum_window_count, ...
    'maximum_output_elements',limits.maximum_output_elements, ...
    'fft_work_units',fftWorkUnits, ...
    'maximum_fft_work_units',limits.maximum_fft_work_units, ...
    'warning_ids',{warningIds}, ...
    'warnings',{warningMessages}, ...
    'file_io',false, ...
    'graphics',false, ...
    'dialogs',false, ...
    'current_folder_changes',false, ...
    'path_changes',false, ...
    'random_number_generation',false, ...
    'base_workspace_assignment',false, ...
    'side_effect_policy','none');
end

function limits = resourceLimits()
limits = struct( ...
    'maximum_input_rows',1e6, ...
    'maximum_control_points',1e4, ...
    'maximum_fft_length',2^20, ...
    'maximum_window_count',1e4, ...
    'maximum_output_elements',5e6, ...
    'maximum_fft_work_units',1e10);
end

function contract = validateSeries(data,limits)
if ~((isa(data,'double') || isa(data,'single')) && ...
        ~issparse(data) && isreal(data) && ismatrix(data) && ...
        size(data,2) == 2)
    error('Acycle:DynamicFilter:InvalidData', ...
        ['DATA must be a full real SINGLE or DOUBLE N-by-2 matrix ', ...
         '[coordinate,value].']);
end
inputRows = size(data,1);
if inputRows < 8
    error('Acycle:DynamicFilter:TooFewRows', ...
        'Dynamic filtering requires at least eight input rows.');
end
if inputRows > limits.maximum_input_rows
    error('Acycle:DynamicFilter:InputRowLimitExceeded', ...
        'DATA exceeds the fixed maximum of %d rows.', ...
        limits.maximum_input_rows);
end
if any(~isfinite(data(:)))
    error('Acycle:DynamicFilter:NonfiniteData', ...
        'Every DATA coordinate and value must be finite.');
end
coordinates = double(data(:,1));
spacing = diff(coordinates);
if any(~isfinite(spacing))
    error('Acycle:DynamicFilter:UnrepresentableSpacing', ...
        'Every coordinate spacing must be representable as finite DOUBLE.');
end
if any(spacing <= 0)
    error('Acycle:DynamicFilter:CoordinatesNotStrictlyIncreasing', ...
        ['DATA coordinates must already be sorted, unique, and strictly ', ...
         'increasing.']);
end
sampleInterval = median(spacing);
maximumSpacingError = max(abs(spacing-sampleInterval));
relativeSpacingDeparture = maximumSpacingError/sampleInterval;
spacingTolerance = 1e-5;
if ~(isfinite(sampleInterval) && sampleInterval > 0 && ...
        isfinite(relativeSpacingDeparture)) || ...
        relativeSpacingDeparture > spacingTolerance
    error('Acycle:DynamicFilter:UnevenSampling', ...
        ['Relative spacing departure %.17g exceeds the fixed tolerance ', ...
         '%.17g. Interpolate explicitly before dynamic filtering.'], ...
        relativeSpacingDeparture,spacingTolerance);
end
coordinateScale = max([1;abs(coordinates);abs(sampleInterval)]);
roundoffTolerance = 128*eps(coordinateScale);
physicalNyquist = 1/(2*sampleInterval);
if ~(isfinite(physicalNyquist) && physicalNyquist > 0)
    error('Acycle:DynamicFilter:InvalidNyquist', ...
        'The physical Nyquist frequency must be finite and positive.');
end
contract = struct( ...
    'sample_interval',sampleInterval, ...
    'maximum_spacing_error',maximumSpacingError, ...
    'relative_spacing_departure',relativeSpacingDeparture, ...
    'spacing_tolerance',spacingTolerance, ...
    'roundoff_absolute_tolerance',roundoffTolerance, ...
    'spacing_departure_above_roundoff', ...
        maximumSpacingError > roundoffTolerance, ...
    'physical_nyquist',physicalNyquist);
end

function options = validateOptions(options)
if ~isstruct(options) || ~isscalar(options)
    error('Acycle:DynamicFilter:InvalidOptions', ...
        'OPTIONS must be a scalar structure.');
end
allowed = {'window_length','step_length'};
unknown = setdiff(fieldnames(options),allowed);
if ~isempty(unknown)
    error('Acycle:DynamicFilter:UnknownOption', ...
        'Unknown dynamic-filter option: %s.',unknown{1});
end
for index = 1:numel(allowed)
    name = allowed{index};
    if ~isfield(options,name) || isempty(options.(name))
        error('Acycle:DynamicFilter:MissingOption', ...
            'Required option %s is missing.',upper(name));
    end
    options.(name) = positiveFiniteScalar(options.(name),name);
end
end

function points = validateControlPoints( ...
        points,name,coordinateStart,coordinateEnd,limits)
if ~((isa(points,'double') || isa(points,'single')) && ...
        ~issparse(points) && isreal(points) && ismatrix(points) && ...
        size(points,2) == 2)
    error('Acycle:DynamicFilter:InvalidControlPoints', ...
        ['%s control points must be a full real SINGLE or DOUBLE ', ...
         'K-by-2 matrix [coordinate,frequency].'],upper(name));
end
if isempty(points)
    error('Acycle:DynamicFilter:EmptyControlPoints', ...
        '%s control points must contain at least one row.',upper(name));
end
if size(points,1) > limits.maximum_control_points
    error('Acycle:DynamicFilter:ControlPointLimitExceeded', ...
        '%s control points exceed the fixed maximum of %d rows.', ...
        upper(name),limits.maximum_control_points);
end
if any(~isfinite(points(:)))
    error('Acycle:DynamicFilter:NonfiniteControlPoints', ...
        'Every %s control coordinate and frequency must be finite.',name);
end
points = full(double(points));
if size(points,1) > 1 && any(diff(points(:,1)) <= 0)
    error('Acycle:DynamicFilter:ControlCoordinatesNotStrictlyIncreasing', ...
        ['%s control coordinates must already be sorted, unique, and ', ...
         'strictly increasing.'],upper(name));
end
if any(points(:,1) < coordinateStart) || ...
        any(points(:,1) > coordinateEnd)
    error('Acycle:DynamicFilter:ControlCoordinateOutsideData', ...
        ['Every %s control coordinate must lie inside the DATA ', ...
         'coordinate domain [%.17g, %.17g].'], ...
        upper(name),coordinateStart,coordinateEnd);
end
if any(points(:,2) <= 0)
    error('Acycle:DynamicFilter:NonpositiveControlFrequency', ...
        'Every %s control frequency must be strictly positive.',upper(name));
end
end

function [coordinates,lower,upper] = validatePassbandPaths( ...
        lowerPoints,upperPoints,coordinateStart,coordinateEnd,nyquist)
coordinates = unique([coordinateStart;lowerPoints(:,1); ...
    upperPoints(:,1);coordinateEnd]);
lower = interpolateClamped(lowerPoints,coordinates);
upper = interpolateClamped(upperPoints,coordinates);
if any(upper >= nyquist)
    first = find(upper >= nyquist,1,'first');
    error('Acycle:DynamicFilter:FrequencyAtOrAboveNyquist', ...
        ['Upper passband frequency %.17g at coordinate %.17g must be ', ...
         'strictly below the physical Nyquist frequency %.17g.'], ...
        upper(first),coordinates(first),nyquist);
end
if any(lower >= upper)
    first = find(lower >= upper,1,'first');
    error('Acycle:DynamicFilter:InvalidPassbandOrder', ...
        ['Passband paths must satisfy LOWER < UPPER. At coordinate ', ...
         '%.17g they are %.17g and %.17g.'], ...
        coordinates(first),lower(first),upper(first));
end
end

function values = interpolateClamped(points,query)
if size(points,1) == 1
    values = repmat(points(1,2),size(query));
    return
end
values = interp1(points(:,1),points(:,2),query,'linear');
values(query < points(1,1)) = points(1,2);
values(query > points(end,1)) = points(end,2);
if any(~isfinite(values))
    error('Acycle:DynamicFilter:ControlInterpolationFailed', ...
        'Passband control interpolation produced a nonfinite value.');
end
end

function [intervals,samples,effective,ratio] = resolveWindow( ...
        requested,dt,span,inputRows)
if requested > span
    error('Acycle:DynamicFilter:WindowLongerThanSpan', ...
        'WINDOW_LENGTH %.17g exceeds the DATA coordinate span %.17g.', ...
        requested,span);
end
ratio = requested/dt;
intervals = roundPositiveHalfAway(ratio);
samples = intervals+1;
if samples < 8
    error('Acycle:DynamicFilter:WindowTooShort', ...
        ['WINDOW_LENGTH resolves to %d samples; dynamic filtering ', ...
         'requires at least eight.'],samples);
end
if samples > inputRows
    error('Acycle:DynamicFilter:WindowSampleCountTooLarge', ...
        ['WINDOW_LENGTH resolves to %d samples, exceeding the %d ', ...
         'input rows.'],samples,inputRows);
end
effective = intervals*dt;
if ~(isfinite(effective) && effective > 0)
    error('Acycle:DynamicFilter:InvalidEffectiveWindow', ...
        'The effective window length must be finite and positive.');
end
end

function [samples,effective,ratio] = resolveStep(requested,dt,windowSamples)
ratio = requested/dt;
samples = roundPositiveHalfAway(ratio);
if samples < 1
    error('Acycle:DynamicFilter:StepTooShort', ...
        ['STEP_LENGTH resolves to zero samples. Increase it to at least ', ...
         'half the sample interval.']);
end
if samples > windowSamples
    error('Acycle:DynamicFilter:StepCreatesCoverageGaps', ...
        ['STEP_LENGTH resolves to %d samples, greater than the %d-sample ', ...
         'window. This would create uncovered output samples.'], ...
        samples,windowSamples);
end
effective = samples*dt;
if ~(isfinite(effective) && effective > 0)
    error('Acycle:DynamicFilter:InvalidEffectiveStep', ...
        'The effective step length must be finite and positive.');
end
end

function rounded = roundPositiveHalfAway(value)
if ~(isfinite(value) && value >= 0)
    error('Acycle:DynamicFilter:InvalidLengthRatio', ...
        'A physical length/sample-interval ratio is invalid.');
end
rounded = floor(value+0.5);
end

function value = positiveFiniteScalar(value,name)
if ~(isnumeric(value) && ~islogical(value) && isreal(value) && ...
        isscalar(value) && isfinite(value) && value > 0)
    error('Acycle:DynamicFilter:InvalidNumericOption', ...
        '%s must be a finite positive real numeric scalar.',upper(name));
end
value = double(value);
end

function weight = halfSampleShiftedHann(samples)
phase = ((0:samples-1)'+0.5)/samples;
weight = 0.5-0.5*cos(2*pi*phase);
if any(~isfinite(weight)) || any(weight <= 0) || any(weight > 1)
    error('Acycle:DynamicFilter:InvalidOverlapWindow', ...
        'The deterministic overlap-add window is invalid.');
end
end
