function [result,meta] = acycleCoherencePhase(reference,target,options)
%ACYCLECOHERENCEPHASE Deterministic Welch coherence and cross phase.
%   [RESULT,META] = ACYCLECOHERENCEPHASE(REFERENCE,TARGET,OPTIONS) analyzes
%   two finite, real N-by-2 series [coordinate,value] on one exact common,
%   near-uniform grid. Rows are never sorted, removed, merged, or
%   interpolated. The function performs no graphics, file I/O, folder or
%   path changes, randomization, or base-workspace assignment.
%
%   OPTIONS must contain exactly these fields:
%     window_samples   integer >= 4 and <= N
%     overlap_samples  integer in [0,window_samples)
%     nfft             even integer >= window_samples
%     alpha            pointwise false-positive probability in (0,1)
%
%   Each segment is mean-removed and multiplied by a periodic Hamming
%   window. The reviewed cross-spectrum convention is
%       MEAN(CONJ(FFT(reference)).*FFT(target)).
%   Thus positive phase means TARGET has positive Fourier phase relative to
%   REFERENCE (for example cos(w*t+phi) has +phi relative phase). DC is
%   omitted because segment mean removal makes its phase uninformative;
%   physical Nyquist is included because NFFT is required to be even.
%
%   The pointwise zero-coherence threshold is the Beta(1,Keff-1)
%   approximation 1-alpha^(1/(Keff-1)). Keff adjusts the nominal segment
%   count using squared correlations between overlapping Hamming windows.
%   This is a pointwise Gaussian/Welch approximation, not a simultaneous or
%   multiple-testing correction. Phase standard error is calculated at
%   phase-defined bins using sqrt((1-C)/(2*Keff*C)); undefined entries use
%   zero plus an explicit availability mask. Interpretation is most useful
%   at significant, high-coherence bins. This avoids the legacy COHAC error
%   of applying the formula to the dimensioned cross-spectrum power.

narginchk(3,3);
limits = resourceLimits();
[referenceCoordinate,referenceValue,referenceClass,referenceSpacing] = ...
    validateSeries(reference,'REFERENCE',limits);
[targetCoordinate,targetValue,targetClass,targetSpacing] = ...
    validateSeries(target,'TARGET',limits);
if ~isequal(referenceCoordinate,targetCoordinate)
    error('Acycle:Coherence:GridMismatch', ...
        ['REFERENCE and TARGET coordinates must match exactly after ', ...
         'conversion to DOUBLE; alignment and interpolation are explicit ', ...
         'caller responsibilities.']);
end
spacingDifference = abs(referenceSpacing.sample_interval- ...
    targetSpacing.sample_interval);
spacingTolerance = 16*max(eps(abs(referenceSpacing.sample_interval)), ...
    eps(abs(targetSpacing.sample_interval)));
if spacingDifference > spacingTolerance
    error('Acycle:Coherence:InternalSpacingMismatch', ...
        'The exact common grid produced inconsistent sample intervals.');
end
options = validateOptions(options,numel(referenceValue),limits);

[referencePrepared,referencePreparation] = prepareValue( ...
    referenceValue,referenceClass,'REFERENCE');
[targetPrepared,targetPreparation] = prepareValue( ...
    targetValue,targetClass,'TARGET');

windowSamples = options.window_samples;
overlapSamples = options.overlap_samples;
stepSamples = windowSamples-overlapSamples;
segmentStarts = (1:stepSamples:(numel(referencePrepared)-windowSamples+1))';
segmentCount = numel(segmentStarts);
if segmentCount < 2
    error('Acycle:Coherence:InsufficientSegments', ...
        ['WINDOW_SAMPLES and OVERLAP_SAMPLES must retain at least two ', ...
         'complete Welch segments.']);
end
workElements = 2*double(segmentCount)*double(options.nfft);
if ~isfinite(workElements) || workElements > limits.maximum_fft_work_elements
    error('Acycle:Coherence:FFTWorkLimitExceeded', ...
        ['The request requires %.17g fixed FFT work elements; the maximum ', ...
         'is %.17g.'],workElements,limits.maximum_fft_work_elements);
end

sampleInterval = referenceSpacing.sample_interval;
samplingFrequency = 1/sampleInterval;
if ~(isfinite(samplingFrequency) && samplingFrequency > 0)
    error('Acycle:Coherence:UnrepresentableSamplingFrequency', ...
        'The reciprocal sampling interval must be finite and positive.');
end
physicalNyquist = samplingFrequency/2;
if ~isfinite(physicalNyquist)
    error('Acycle:Coherence:UnrepresentableNyquist', ...
        'Physical Nyquist must be representable as a finite DOUBLE.');
end

window = periodicHamming(windowSamples);
windowEnergy = sum(window.^2);
if ~(isfinite(windowEnergy) && windowEnergy > 0)
    error('Acycle:Coherence:InvalidWindow', ...
        'The periodic Hamming window has invalid energy.');
end

positiveBinCount = options.nfft/2;
referencePower = zeros(positiveBinCount,1);
targetPower = zeros(positiveBinCount,1);
crossSpectrum = complex(zeros(positiveBinCount,1));
for segmentIndex = 1:segmentCount
    indices = segmentStarts(segmentIndex): ...
        segmentStarts(segmentIndex)+windowSamples-1;
    referenceSegment = referencePrepared(indices);
    targetSegment = targetPrepared(indices);
    referenceSegment = referenceSegment-mean(referenceSegment);
    targetSegment = targetSegment-mean(targetSegment);
    referenceTransform = fft(referenceSegment.*window,options.nfft);
    targetTransform = fft(targetSegment.*window,options.nfft);
    % Bin one is DC and is intentionally excluded.
    referenceTransform = referenceTransform(2:positiveBinCount+1);
    targetTransform = targetTransform(2:positiveBinCount+1);
    referencePower = referencePower+abs(referenceTransform).^2;
    targetPower = targetPower+abs(targetTransform).^2;
    crossSpectrum = crossSpectrum+ ...
        conj(referenceTransform).*targetTransform;
end
if any(~isfinite(referencePower)) || any(~isfinite(targetPower)) || ...
        any(~isfinite(real(crossSpectrum))) || ...
        any(~isfinite(imag(crossSpectrum)))
    error('Acycle:Coherence:NonfiniteSpectrum', ...
        'Welch accumulation produced a nonfinite spectral value.');
end

frequency = (1:positiveBinCount)'*samplingFrequency/options.nfft;
frequency(end) = physicalNyquist;
if any(~isfinite(frequency)) || any(diff(frequency) <= 0) || ...
        frequency(end) ~= physicalNyquist
    error('Acycle:Coherence:InvalidFrequencyGrid', ...
        ['The one-sided positive-frequency grid must be finite, strictly ', ...
         'increasing, and end at physical Nyquist.']);
end

validPower = referencePower > 0 & targetPower > 0;
coherence = zeros(positiveBinCount,1);
rawCoherence = zeros(positiveBinCount,1);
rawCoherence(validPower) = abs(crossSpectrum(validPower)).^2 ./ ...
    (referencePower(validPower).*targetPower(validPower));
if any(~isfinite(rawCoherence(validPower))) || ...
        any(rawCoherence(validPower) < 0)
    error('Acycle:Coherence:InvalidCoherence', ...
        'Magnitude-squared coherence must be finite and nonnegative.');
end
coherenceBoundTolerance = 2048*eps*max(1,segmentCount);
maximumRawCoherence = max(rawCoherence);
maximumBoundOvershoot = max(0,maximumRawCoherence-1);
if maximumBoundOvershoot > coherenceBoundTolerance
    error('Acycle:Coherence:CoherenceBoundViolation', ...
        ['Welch coherence exceeded its Cauchy-Schwarz bound by %.17g, ', ...
         'larger than tolerance %.17g.'], ...
        maximumBoundOvershoot,coherenceBoundTolerance);
end
coherence(validPower) = min(rawCoherence(validPower),1);

crossScale = sqrt(referencePower.*targetPower);
phaseResolution = 64*eps;
phaseDefined = validPower & abs(crossSpectrum) > ...
    phaseResolution*crossScale;
phaseRadians = zeros(positiveBinCount,1);
phaseRadians(phaseDefined) = angle(crossSpectrum(phaseDefined));
phaseDegrees = phaseRadians*(180/pi);
if any(~isfinite(phaseDegrees))
    error('Acycle:Coherence:InvalidPhase', ...
        'Cross phase must use finite degrees, with zero only as undefined fill.');
end

[equivalentAverages,overlapCorrection,windowCorrelations] = ...
    equivalentIndependentAverages(window,stepSamples,segmentCount);
if ~(isfinite(equivalentAverages) && equivalentAverages > 1)
    error('Acycle:Coherence:InsufficientEquivalentAverages', ...
        ['The selected overlap leaves no more than one equivalent ', ...
         'independent Welch average.']);
end
criticalCoherence = -expm1(log(options.alpha)/(equivalentAverages-1));
if ~(isfinite(criticalCoherence) && criticalCoherence >= 0 && ...
        criticalCoherence <= 1)
    error('Acycle:Coherence:InvalidCriticalCoherence', ...
        'The pointwise coherence threshold is not finite in [0,1].');
end

significant = validPower & phaseDefined & coherence > criticalCoherence;
phaseStandardErrorDegrees = zeros(positiveBinCount,1);
phaseStandardErrorAvailable = phaseDefined;
phaseStandardErrorRadians = sqrt((1-coherence(phaseDefined)) ./ ...
    (2*equivalentAverages*coherence(phaseDefined)));
phaseStandardErrorDegrees(phaseDefined) = ...
    phaseStandardErrorRadians*(180/pi);
if any(~isfinite(phaseStandardErrorDegrees)) || ...
        any(phaseStandardErrorDegrees < 0)
    error('Acycle:Coherence:InvalidPhaseStandardError', ...
        'Available phase standard errors must be finite and nonnegative.');
end

result = struct( ...
    'frequency',frequency, ...
    'magnitude_squared_coherence',coherence, ...
    'cross_phase_degrees',phaseDegrees, ...
    'phase_defined',phaseDefined, ...
    'pointwise_significant',significant, ...
    'phase_standard_error_degrees',phaseStandardErrorDegrees, ...
    'phase_standard_error_available',phaseStandardErrorAvailable, ...
    'spectrum',[frequency,coherence,phaseDegrees,double(significant)]);

meta = struct( ...
    'version','coherence-phase-v1', ...
    'method','welch_magnitude_squared_coherence_and_cross_phase', ...
    'reviewed_subset','two_series_exact_common_grid_deterministic_welch', ...
    'input_policy', ...
        'strict_finite_real_full_single_or_double_n_by_2_exact_common_increasing_near_uniform', ...
    'alignment_policy','exact_common_coordinate_grid_no_interpolation', ...
    'reference_input_class',referenceClass, ...
    'target_input_class',targetClass, ...
    'input_rows',numel(referenceValue), ...
    'input_columns_per_series',2, ...
    'coordinate_start',referenceCoordinate(1), ...
    'coordinate_end',referenceCoordinate(end), ...
    'sample_interval',sampleInterval, ...
    'sampling_frequency',samplingFrequency, ...
    'physical_nyquist',physicalNyquist, ...
    'maximum_spacing_error',referenceSpacing.maximum_spacing_error, ...
    'relative_spacing_departure', ...
        referenceSpacing.relative_spacing_departure, ...
    'spacing_tolerance',referenceSpacing.spacing_tolerance, ...
    'value_preparation','global_mean_remove_and_peak_scale_then_segment_mean_remove', ...
    'reference_global_scale',referencePreparation.input_amplitude_scale, ...
    'reference_centered_peak',referencePreparation.centered_peak, ...
    'target_global_scale',targetPreparation.input_amplitude_scale, ...
    'target_centered_peak',targetPreparation.centered_peak, ...
    'window','periodic_hamming', ...
    'window_samples',windowSamples, ...
    'window_energy',windowEnergy, ...
    'overlap_samples',overlapSamples, ...
    'step_samples',stepSamples, ...
    'segment_count',segmentCount, ...
    'first_segment_start_index',segmentStarts(1), ...
    'last_segment_start_index',segmentStarts(end), ...
    'unused_trailing_samples',numel(referenceValue)- ...
        (segmentStarts(end)+windowSamples-1), ...
    'nfft',options.nfft, ...
    'nfft_policy','explicit_even_at_least_window_samples', ...
    'output_frequency_bins',positiveBinCount, ...
    'dc_included',false, ...
    'nyquist_included',true, ...
    'cross_spectrum_convention','conj_fft_reference_times_fft_target', ...
    'phase_sign', ...
        'positive_means_target_has_positive_fourier_phase_relative_to_reference', ...
    'undefined_phase_fill_degrees',0, ...
    'undefined_phase_bin_count',sum(~phaseDefined), ...
    'invalid_power_bin_count',sum(~validPower), ...
    'coherence_minimum',min(coherence), ...
    'coherence_maximum',max(coherence), ...
    'maximum_raw_coherence',maximumRawCoherence, ...
    'maximum_coherence_bound_overshoot',maximumBoundOvershoot, ...
    'coherence_bound_tolerance',coherenceBoundTolerance, ...
    'alpha',options.alpha, ...
    'confidence_level',1-options.alpha, ...
    'nominal_segment_averages',segmentCount, ...
    'overlap_correction_factor',overlapCorrection, ...
    'equivalent_independent_averages',equivalentAverages, ...
    'equivalent_degrees_of_freedom',2*equivalentAverages, ...
    'window_overlap_correlations',windowCorrelations, ...
    'critical_coherence',criticalCoherence, ...
    'critical_coherence_formula','1_minus_alpha_power_1_over_keff_minus_1', ...
    'significance_scope','pointwise_gaussian_welch_approximation', ...
    'multiple_testing_correction','none', ...
    'significant_comparison','coherence_strictly_greater_than_threshold', ...
    'significant_bin_count',sum(significant), ...
    'phase_standard_error_formula','sqrt_1_minus_c_over_2_keff_c', ...
    'phase_standard_error_scope','all_phase_defined_bins_interpret_significant_bins', ...
    'unavailable_phase_standard_error_fill_degrees',0, ...
    'maximum_fft_work_elements',limits.maximum_fft_work_elements, ...
    'randomization','none');
end

function limits = resourceLimits()
limits = struct( ...
    'minimum_rows',8, ...
    'maximum_rows',1e6, ...
    'maximum_nfft',1048576, ...
    'maximum_fft_work_elements',5e7, ...
    'spacing_tolerance',1e-5);
end

function [coordinates,values,inputClass,spacing] = validateSeries( ...
        data,inputName,limits)
if ~(isa(data,'double') || isa(data,'single')) || ~isreal(data) || ...
        ~ismatrix(data) || issparse(data) || size(data,2) ~= 2
    error('Acycle:Coherence:InvalidData', ...
        ['%s must be a finite real full SINGLE or DOUBLE N-by-2 matrix ', ...
         '[coordinate,value].'],inputName);
end
rowCount = size(data,1);
if rowCount < limits.minimum_rows
    error('Acycle:Coherence:InsufficientRows', ...
        '%s must contain at least %d rows.',inputName,limits.minimum_rows);
end
if rowCount > limits.maximum_rows
    error('Acycle:Coherence:InputLimitExceeded', ...
        '%s exceeds the fixed maximum of %d rows.', ...
        inputName,limits.maximum_rows);
end
if any(~isfinite(data(:)))
    error('Acycle:Coherence:NonfiniteData', ...
        '%s must be finite; rows are never removed.',inputName);
end

inputClass = class(data);
working = full(double(data));
coordinates = working(:,1);
values = working(:,2);
coordinateSpacing = diff(coordinates);
if any(coordinateSpacing <= 0)
    error('Acycle:Coherence:InvalidCoordinate', ...
        ['%s coordinates must already be sorted, unique, and strictly ', ...
         'increasing.'],inputName);
end
sampleInterval = median(coordinateSpacing);
if ~(isfinite(sampleInterval) && sampleInterval > 0)
    error('Acycle:Coherence:InvalidSpacing', ...
        '%s median coordinate spacing must be finite and positive.',inputName);
end
maximumSpacingError = max(abs(coordinateSpacing-sampleInterval));
relativeSpacingDeparture = maximumSpacingError/sampleInterval;
if ~(isfinite(relativeSpacingDeparture) && ...
        relativeSpacingDeparture <= limits.spacing_tolerance)
    error('Acycle:Coherence:UnevenSampling', ...
        ['%s coordinate spacing must be uniform within relative tolerance ', ...
         '%.17g; no interpolation is performed.'], ...
        inputName,limits.spacing_tolerance);
end
spacing = struct( ...
    'sample_interval',sampleInterval, ...
    'maximum_spacing_error',maximumSpacingError, ...
    'relative_spacing_departure',relativeSpacingDeparture, ...
    'spacing_tolerance',limits.spacing_tolerance);
end

function options = validateOptions(options,rowCount,limits)
requiredFields = {'window_samples','overlap_samples','nfft','alpha'};
if ~(isstruct(options) && isscalar(options))
    error('Acycle:Coherence:InvalidOptions', ...
        'OPTIONS must be a scalar structure.');
end
actualFields = fieldnames(options);
missingFields = setdiff(requiredFields,actualFields);
unknownFields = setdiff(actualFields,requiredFields);
if ~isempty(missingFields)
    error('Acycle:Coherence:MissingOption', ...
        'Missing required option: %s.',missingFields{1});
end
if ~isempty(unknownFields)
    error('Acycle:Coherence:UnknownOption', ...
        'Unknown option: %s.',unknownFields{1});
end
if ~isPositiveInteger(options.window_samples) || ...
        options.window_samples < 4 || options.window_samples > rowCount
    error('Acycle:Coherence:InvalidWindowSamples', ...
        'WINDOW_SAMPLES must be an integer from 4 through the input row count.');
end
if ~isNonnegativeInteger(options.overlap_samples) || ...
        options.overlap_samples >= options.window_samples
    error('Acycle:Coherence:InvalidOverlapSamples', ...
        'OVERLAP_SAMPLES must be an integer in [0,WINDOW_SAMPLES).');
end
if ~isPositiveInteger(options.nfft) || mod(options.nfft,2) ~= 0 || ...
        options.nfft < options.window_samples || ...
        options.nfft > limits.maximum_nfft
    error('Acycle:Coherence:InvalidNfft', ...
        ['NFFT must be an even integer at least WINDOW_SAMPLES and no ', ...
         'larger than %d.'],limits.maximum_nfft);
end
if ~(isnumeric(options.alpha) && isscalar(options.alpha) && ...
        isreal(options.alpha) && isfinite(options.alpha) && ...
        options.alpha > 0 && options.alpha < 1)
    error('Acycle:Coherence:InvalidAlpha', ...
        'ALPHA must be a finite real numeric scalar strictly between zero and one.');
end
options.window_samples = double(options.window_samples);
options.overlap_samples = double(options.overlap_samples);
options.nfft = double(options.nfft);
options.alpha = double(options.alpha);
end

function tf = isNonnegativeInteger(value)
tf = isnumeric(value) && isscalar(value) && isreal(value) && ...
    isfinite(value) && value >= 0 && value == fix(value);
end

function tf = isPositiveInteger(value)
tf = isnumeric(value) && isscalar(value) && isreal(value) && ...
    isfinite(value) && value > 0 && value == fix(value);
end

function [prepared,diagnostic] = prepareValue(values,inputClass,inputName)
inputAmplitudeScale = max(abs(values));
if ~(isfinite(inputAmplitudeScale) && inputAmplitudeScale > 0)
    error('Acycle:Coherence:ConstantSeries', ...
        '%s is constant and has no resolvable spectral power.',inputName);
end
scaled = values/inputAmplitudeScale;
centered = scaled-mean(scaled);
centeredPeak = max(abs(centered));
resolution = 32*double(eps(inputClass));
if ~(isfinite(centeredPeak) && centeredPeak > resolution)
    error('Acycle:Coherence:UnresolvableSeriesVariation', ...
        ['%s variation is constant or not resolvable at the input ', ...
         'precision after centering.'],inputName);
end
prepared = centered/centeredPeak;
if any(~isfinite(prepared))
    error('Acycle:Coherence:InvalidValuePreparation', ...
        '%s normalization produced a nonfinite value.',inputName);
end
diagnostic = struct( ...
    'input_amplitude_scale',inputAmplitudeScale, ...
    'centered_peak',centeredPeak, ...
    'input_epsilon',double(eps(inputClass)), ...
    'resolution_multiplier',32);
end

function window = periodicHamming(windowSamples)
sampleIndex = (0:windowSamples-1)';
window = 0.54-0.46*cos(2*pi*sampleIndex/windowSamples);
end

function [equivalentAverages,correction,correlations] = ...
        equivalentIndependentAverages(window,stepSamples,segmentCount)
windowSamples = numel(window);
windowEnergy = sum(window.^2);
maximumLag = min(segmentCount-1,floor((windowSamples-1)/stepSamples));
correlations = zeros(maximumLag,1);
correction = 1;
for lagIndex = 1:maximumLag
    shift = lagIndex*stepSamples;
    correlations(lagIndex) = sum( ...
        window(1:windowSamples-shift).*window(shift+1:windowSamples)) / ...
        windowEnergy;
    correction = correction+2*(1-lagIndex/segmentCount)* ...
        correlations(lagIndex)^2;
end
equivalentAverages = segmentCount/correction;
end
