function [result,meta] = acycleCircularSpectrum( ...
        eventCoordinates,periodMinimum,periodMaximum,periodCount,gridMode)
%ACYCLECIRCULARSPECTRUM Deterministic circular vector-strength spectrum.
%   [RESULT,META] = ACYCLECIRCULARSPECTRUM(EVENTCOORDINATES,PERIODMINIMUM,
%   PERIODMAXIMUM,PERIODCOUNT,GRIDMODE) evaluates event-coordinate phase
%   concentration on one explicit period grid. EVENTCOORDINATES must be a
%   finite real SINGLE or DOUBLE vector containing at least two unique,
%   strictly increasing values. No rows are sorted, removed, or merged.
%
%   PERIODMINIMUM and PERIODMAXIMUM are finite positive scalars with
%   PERIODMINIMUM < PERIODMAXIMUM. PERIODCOUNT is an integer of at least
%   two. GRIDMODE is 'linear' or 'log'. For each period p,
%
%       C = mean(cos(2*pi*mod(x,p)/p))
%       S = mean(sin(2*pi*mod(x,p)/p))
%       vector_strength = hypot(C,S).
%
%   The phase coordinate is p*mod(atan2(S,C),2*pi)/(2*pi), in [0,p).
%   Phase is undefined when the resultant vector is numerically zero; the
%   saved phase coordinate is then fixed to zero and META reports the
%   affected count and threshold. RESULT columns are
%   [period,vector_strength,phase_coordinate]. Vector strength is not a
%   Fourier power or a significance probability.
%
%   This deterministic core performs no Monte Carlo inference, plotting,
%   file I/O, random-number generation, workspace access, or session-state
%   changes.

narginchk(5,5);

maximumInputRows = 1e6;
maximumPeriodCount = 1e6;
maximumWorkUnits = 1e7;
if ~((isa(eventCoordinates,'double') || ...
        isa(eventCoordinates,'single')) && ...
        ~issparse(eventCoordinates) && isreal(eventCoordinates) && ...
        isvector(eventCoordinates))
    error('Acycle:CircularSpectrum:InvalidEvents', ...
        ['EVENTCOORDINATES must be a full, real SINGLE or DOUBLE ', ...
         'vector.']);
end
events = double(eventCoordinates(:));
inputRows = numel(events);
if inputRows < 2
    error('Acycle:CircularSpectrum:TooFewEvents', ...
        'EVENTCOORDINATES must contain at least two values.');
end
if inputRows > maximumInputRows
    error('Acycle:CircularSpectrum:InputRowLimitExceeded', ...
        'EVENTCOORDINATES exceeds the fixed limit of 1000000 values.');
end
if any(~isfinite(events))
    error('Acycle:CircularSpectrum:NonfiniteEvents', ...
        'Every event coordinate must be finite.');
end
eventSpacing = diff(events);
if any(~isfinite(eventSpacing))
    error('Acycle:CircularSpectrum:UnrepresentableSpacing', ...
        'Every event-coordinate spacing must be finite DOUBLE.');
end
if any(eventSpacing <= 0)
    error('Acycle:CircularSpectrum:EventsNotStrictlyIncreasing', ...
        ['EVENTCOORDINATES must already be unique and strictly ', ...
         'increasing; the core never sorts or merges events.']);
end
coordinateSpan = events(end)-events(1);
if ~(isfinite(coordinateSpan) && coordinateSpan > 0)
    error('Acycle:CircularSpectrum:UnrepresentableSpan', ...
        'The event-coordinate span must be finite and positive.');
end

periodMinimum = positiveFiniteScalar(periodMinimum,'PERIODMINIMUM');
periodMaximum = positiveFiniteScalar(periodMaximum,'PERIODMAXIMUM');
if periodMinimum >= periodMaximum
    error('Acycle:CircularSpectrum:InvalidPeriodRange', ...
        'PERIODMINIMUM must be strictly less than PERIODMAXIMUM.');
end
if ~(isnumeric(periodCount) && ~islogical(periodCount) && ...
        isreal(periodCount) && isscalar(periodCount) && ...
        isfinite(periodCount) && periodCount == fix(periodCount) && ...
        periodCount >= 2)
    error('Acycle:CircularSpectrum:InvalidPeriodCount', ...
        'PERIODCOUNT must be a finite integer of at least two.');
end
periodCount = double(periodCount);
if periodCount > maximumPeriodCount
    error('Acycle:CircularSpectrum:PeriodCountLimitExceeded', ...
        'PERIODCOUNT exceeds the fixed limit of 1000000.');
end
gridMode = textChoice(gridMode,{'linear','log'});

workUnits = inputRows*periodCount;
if ~isfinite(workUnits) || workUnits > maximumWorkUnits
    error('Acycle:CircularSpectrum:WorkLimitExceeded', ...
        ['event_count times period_count must not exceed the fixed ', ...
         'limit of 10000000.']);
end
if strcmp(gridMode,'linear')
    periods = linspace(periodMinimum,periodMaximum,periodCount).';
else
    periods = logspace( ...
        log10(periodMinimum),log10(periodMaximum),periodCount).';
end
if any(~isfinite(periods)) || any(periods <= 0) || ...
        any(diff(periods) <= 0)
    error('Acycle:CircularSpectrum:InvalidPeriodGrid', ...
        'The requested period grid is not finite and strictly increasing.');
end

vectorStrength = zeros(periodCount,1);
phaseCoordinate = zeros(periodCount,1);
phaseDefined = true(periodCount,1);
phaseUndefinedThreshold = 64*eps(1);
maximumStrengthOvershoot = 64*eps(1);
for index = 1:periodCount
    period = periods(index);
    reducedCoordinate = mod(events,period);
    angle = (2*pi/period)*reducedCoordinate;
    sineMean = sum(sin(angle))/inputRows;
    cosineMean = sum(cos(angle))/inputRows;
    strength = hypot(sineMean,cosineMean);
    if ~(isfinite(sineMean) && isfinite(cosineMean) && ...
            isfinite(strength) && strength >= 0 && ...
            strength <= 1+maximumStrengthOvershoot)
        error('Acycle:CircularSpectrum:InvalidResultantVector', ...
            'Period-grid row %d produced an invalid resultant vector.', ...
            index);
    end
    vectorStrength(index) = min(1,strength);
    if strength <= phaseUndefinedThreshold
        phaseDefined(index) = false;
        phaseCoordinate(index) = 0;
    else
        phase = period*mod(atan2(sineMean,cosineMean),2*pi)/(2*pi);
        boundaryTolerance = 64*eps(abs(period));
        if phase <= boundaryTolerance || ...
                period-phase <= boundaryTolerance
            phase = 0;
        end
        if ~(isfinite(phase) && phase >= 0 && phase < period)
            error('Acycle:CircularSpectrum:InvalidPhase', ...
                'Period-grid row %d produced an invalid phase.',index);
        end
        phaseCoordinate(index) = phase;
    end
end

result = [periods,vectorStrength,phaseCoordinate];
if ~(isa(result,'double') && isreal(result) && ...
        isequal(size(result),[periodCount,3]) && ...
        all(isfinite(result),'all') && all(diff(result(:,1)) > 0) && ...
        all(result(:,2) >= 0 & result(:,2) <= 1) && ...
        all(result(:,3) >= 0 & result(:,3) < result(:,1)))
    error('Acycle:CircularSpectrum:InvalidOutput', ...
        'The circular spectrum failed its finite output contract.');
end

meta = struct( ...
    'version','circular-spectrum-v1', ...
    'analysis_scope','deterministic-vector-strength-only', ...
    'input_policy','strict-finite-real-vector-unique-increasing', ...
    'input_class',class(eventCoordinates), ...
    'input_rows',inputRows, ...
    'coordinate_start',events(1), ...
    'coordinate_end',events(end), ...
    'coordinate_span',coordinateSpan, ...
    'spacing_minimum',min(eventSpacing), ...
    'spacing_median',median(eventSpacing), ...
    'spacing_maximum',max(eventSpacing), ...
    'period_minimum',periods(1), ...
    'period_maximum',periods(end), ...
    'period_count',periodCount, ...
    'period_grid',gridMode, ...
    'result_columns',{{ ...
        'period','vector_strength','phase_coordinate'}}, ...
    'strength_name','mean-resultant-vector-length', ...
    'strength_formula','hypot(mean(cos(theta)),mean(sin(theta)))', ...
    'strength_is_fourier_power',false, ...
    'strength_is_probability',false, ...
    'coordinate_reduction','mod(event_coordinate,period)', ...
    'phase_formula', ...
        'period*mod(atan2(mean(sin),mean(cos)),2*pi)/(2*pi)', ...
    'phase_range','zero-inclusive-period-exclusive', ...
    'phase_undefined_threshold',phaseUndefinedThreshold, ...
    'phase_undefined_count',sum(~phaseDefined), ...
    'phase_undefined_output','zero', ...
    'vector_strength_minimum',min(vectorStrength), ...
    'vector_strength_maximum',max(vectorStrength), ...
    'maximum_input_rows',maximumInputRows, ...
    'maximum_period_count',maximumPeriodCount, ...
    'maximum_work_units',maximumWorkUnits, ...
    'work_units',workUnits, ...
    'monte_carlo',false, ...
    'significance',false, ...
    'sorted',false, ...
    'removed_events',0, ...
    'file_io',false, ...
    'graphics',false, ...
    'dialogs',false, ...
    'random_number_generation',false, ...
    'side_effect_policy','none');
end

function value = positiveFiniteScalar(value,label)
if ~(isnumeric(value) && ~islogical(value) && isreal(value) && ...
        isscalar(value) && isfinite(value) && value > 0)
    error('Acycle:CircularSpectrum:InvalidPositiveScalar', ...
        '%s must be a finite positive real numeric scalar.',label);
end
value = double(value);
end

function value = textChoice(value,choices)
if isstring(value) && isscalar(value)
    value = char(value);
end
if ~(ischar(value) && isrow(value) && ~isempty(strtrim(value)))
    error('Acycle:CircularSpectrum:InvalidGridMode', ...
        'GRIDMODE must be linear or log.');
end
value = lower(strtrim(value));
if ~any(strcmp(value,choices))
    error('Acycle:CircularSpectrum:InvalidGridMode', ...
        'GRIDMODE must be linear or log.');
end
end
