function [interpolated,meta] = acycleInterpolateSeries( ...
        data,samplingInterval,varargin)
%ACYCLEINTERPOLATESERIES Linearly interpolate a strict preprocessed series.
%   [INTERPOLATED,META] = ACYCLEINTERPOLATESERIES(DATA,SAMPLINGINTERVAL)
%   resamples columns 2-N of DATA on a uniform, integer-index grid anchored
%   at DATA(1,1). DATA must be a finite real SINGLE or DOUBLE matrix whose
%   first column is strictly increasing. SAMPLINGINTERVAL must be a finite
%   positive scalar no larger than the coordinate span.
%
%   The interpolation method is deliberately fixed to LINEAR. The function
%   does not extrapolate, fill gaps with zero, detrend, standardize, or apply
%   an anti-alias filter. The final input coordinate is included only when
%   it is an integer number of target intervals from the first coordinate,
%   allowing a small ULP-scale tolerance. Otherwise the short trailing
%   remainder is reported in META and is not filled with a nonuniform point.
%
%   Two undocumented, lowering-only name-value limits are available for
%   boundary tests: MaximumPoints and MaximumElements. Production callers
%   should use the fixed defaults of 1,000,000 rows and 16,000,000 elements.

narginchk(2,6);

hardMaximumPoints = 1e6;
hardMaximumElements = 16e6;
[maximumPoints,maximumElements] = parseResourceLimits( ...
    hardMaximumPoints,hardMaximumElements,varargin{:});

if ~(isa(data,'double') || isa(data,'single')) || ~isreal(data) || ...
        ~ismatrix(data) || size(data,2) < 2
    error('Acycle:Interpolate:InvalidData', ...
        ['DATA must be a real floating-point two-dimensional matrix with ', ...
         'coordinate in column 1 and at least one value column.']);
end
if size(data,1) < 2
    error('Acycle:Interpolate:TooFewRows', ...
        'DATA must contain at least two rows.');
end
if any(~isfinite(data(:)))
    error('Acycle:Interpolate:NonfiniteData', ...
        ['DATA must already be preprocessed: every coordinate and value ', ...
         'must be finite.']);
end
if ~(isnumeric(samplingInterval) && isscalar(samplingInterval) && ...
        isreal(samplingInterval) && isfinite(samplingInterval) && ...
        samplingInterval > 0)
    error('Acycle:Interpolate:InvalidSamplingInterval', ...
        'SAMPLINGINTERVAL must be a finite positive real numeric scalar.');
end

working = double(data);
coordinates = working(:,1);
if any(coordinates(2:end) <= coordinates(1:end-1))
    error('Acycle:Interpolate:CoordinatesNotStrictlyIncreasing', ...
        ['DATA(:,1) must already be sorted, contain no duplicates, and be ', ...
         'strictly increasing.']);
end

inputSpacing = diff(coordinates);
if any(~isfinite(inputSpacing))
    error('Acycle:Interpolate:NonfiniteCoordinateSpacing', ...
        'At least one coordinate spacing is not representable as a DOUBLE.');
end
coordinateStart = coordinates(1);
coordinateEnd = coordinates(end);
coordinateSpan = coordinateEnd-coordinateStart;
if ~isfinite(coordinateSpan) || coordinateSpan <= 0
    error('Acycle:Interpolate:NonfiniteCoordinateSpan', ...
        'The input coordinate span must be finite and positive.');
end

targetSpacing = double(samplingInterval);
if targetSpacing > coordinateSpan
    error('Acycle:Interpolate:SamplingIntervalExceedsSpan', ...
        'SAMPLINGINTERVAL must not exceed the input coordinate span.');
end

rawIntervalCount = coordinateSpan/targetSpacing;
if ~isfinite(rawIntervalCount) || rawIntervalCount > maximumPoints
    error('Acycle:Interpolate:OutputGridTooLarge', ...
        ['The requested sampling interval would exceed the configured ', ...
         'maximum output point count.']);
end

nearestIntervalCount = round(rawIntervalCount);
countTolerance = 8*eps(max(1,abs(rawIntervalCount)));
endpointIsNearGrid = abs(rawIntervalCount-nearestIntervalCount) <= ...
    countTolerance;
if endpointIsNearGrid
    intervalCount = nearestIntervalCount;
else
    intervalCount = floor(rawIntervalCount);
end
if intervalCount < 1
    error('Acycle:Interpolate:InternalIntervalCount', ...
        'A positive output interval count could not be constructed.');
end

outputRows = intervalCount+1;
inputColumns = size(working,2);
if outputRows > maximumPoints
    error('Acycle:Interpolate:OutputGridTooLarge', ...
        ['The requested sampling interval would create %g points; the ', ...
         'configured maximum is %g.'],outputRows,maximumPoints);
end
if inputColumns > floor(maximumElements/outputRows)
    error('Acycle:Interpolate:OutputElementLimitExceeded', ...
        ['The requested output would exceed the configured maximum of ', ...
         '%g numeric elements.'],maximumElements);
end

integerIndex = (0:intervalCount)';
grid = coordinateStart+integerIndex*targetSpacing;
if any(~isfinite(grid)) || any(diff(grid) <= 0)
    error('Acycle:Interpolate:UnrepresentableGrid', ...
        ['The requested grid is not representable as finite, strictly ', ...
         'increasing DOUBLE coordinates at this coordinate magnitude.']);
end

endpointTolerance = 16*max([ ...
    eps(abs(coordinateStart)),eps(abs(coordinateEnd)), ...
    eps(abs(coordinateSpan)),eps(abs(grid(end))), ...
    eps(abs(intervalCount*targetSpacing))]);
if endpointIsNearGrid
    if abs(grid(end)-coordinateEnd) > endpointTolerance
        error('Acycle:Interpolate:InternalEndpointMismatch', ...
            ['The near-grid endpoint could not be reconciled within the ', ...
             'ULP-scale coordinate tolerance.']);
    end
    grid(end) = coordinateEnd;
end
if grid(1) < coordinateStart || grid(end) > coordinateEnd
    error('Acycle:Interpolate:InternalGridOutsideDomain', ...
        'The generated interpolation grid extends outside the input domain.');
end
if any(diff(grid) <= 0)
    error('Acycle:Interpolate:UnrepresentableGrid', ...
        'Endpoint reconciliation produced a non-increasing output grid.');
end
actualGridSpacing = diff(grid);
representabilityTolerance = 1e-8*targetSpacing;
if max(abs(actualGridSpacing-targetSpacing)) > ...
        representabilityTolerance
    error('Acycle:Interpolate:UnrepresentableGrid', ...
        ['Floating-point coordinate quantization changes the actual grid ', ...
         'spacing by more than 1e-8 of SAMPLINGINTERVAL.']);
end

gridChanged = ~(numel(grid) == numel(coordinates) && ...
    all(grid == coordinates));
if gridChanged
    values = interp1(coordinates,working(:,2:end),grid,'linear');
else
    % Preserve exact values when the requested grid is already present.
    values = working(:,2:end);
end
interpolated = [grid,values];
if any(~isfinite(interpolated(:)))
    error('Acycle:Interpolate:NonfiniteOutput', ...
        ['Linear interpolation produced a nonfinite result; no partial ', ...
         'output is returned.']);
end

outputSpacing = actualGridSpacing;
if any(~isfinite(outputSpacing)) || any(outputSpacing <= 0)
    error('Acycle:Interpolate:InvalidOutputSpacing', ...
        'The output coordinate spacing must be finite and positive.');
end

inputSpacingMinimum = min(inputSpacing);
inputSpacingMedian = median(inputSpacing);
inputSpacingMaximum = max(inputSpacing);
maximumGapToMedianRatio = inputSpacingMaximum/inputSpacingMedian;
maximumGapToTargetRatio = inputSpacingMaximum/targetSpacing;
if ~isfinite(maximumGapToMedianRatio) || ...
        ~isfinite(maximumGapToTargetRatio)
    error('Acycle:Interpolate:NonfiniteDiagnostic', ...
        'A required spacing ratio is not representable as a finite DOUBLE.');
end

longGapThresholdMultiple = 10;
gapRatioTolerance = 8*eps(longGapThresholdMultiple);
longGapCount = sum(inputSpacing/inputSpacingMedian > ...
    longGapThresholdMultiple+gapRatioTolerance);
downsampling = targetSpacing > inputSpacingMedian+ ...
    ulpTolerance(targetSpacing,inputSpacingMedian);
oversamplingBoundary = 0.5*inputSpacingMedian;
substantialOversampling = targetSpacing < oversamplingBoundary- ...
    ulpTolerance(targetSpacing,oversamplingBoundary);

endpointIncluded = (grid(end) == coordinateEnd);
unfilledTail = coordinateEnd-grid(end);
if endpointIncluded
    unfilledTail = 0;
end

meta = struct( ...
    'InputRows',size(working,1), ...
    'InputColumns',inputColumns, ...
    'OutputRows',size(interpolated,1), ...
    'OutputColumns',size(interpolated,2), ...
    'InputCoordinateStart',coordinateStart, ...
    'InputCoordinateEnd',coordinateEnd, ...
    'OutputCoordinateStart',grid(1), ...
    'OutputCoordinateEnd',grid(end), ...
    'InputSpacingMinimum',inputSpacingMinimum, ...
    'InputSpacingMedian',inputSpacingMedian, ...
    'InputSpacingMaximum',inputSpacingMaximum, ...
    'OutputSpacingMinimum',min(outputSpacing), ...
    'OutputSpacingMedian',median(outputSpacing), ...
    'OutputSpacingMaximum',max(outputSpacing), ...
    'SamplingInterval',targetSpacing, ...
    'UnfilledTail',unfilledTail, ...
    'EndpointIncluded',endpointIncluded, ...
    'GridChanged',gridChanged, ...
    'Method','linear', ...
    'InputPolicy','strict-preprocessed-series', ...
    'GridOriginPolicy','first-input-coordinate', ...
    'EndpointPolicy','include-only-on-regular-grid', ...
    'GapPolicy','linear-across-gaps-no-zero-fill', ...
    'LongGapThresholdMultiple',longGapThresholdMultiple, ...
    'LongGapCount',longGapCount, ...
    'MaximumGapToMedianRatio',maximumGapToMedianRatio, ...
    'MaximumGapToTargetRatio',maximumGapToTargetRatio, ...
    'Downsampling',downsampling, ...
    'SubstantialOversampling',substantialOversampling, ...
    'Extrapolated',false, ...
    'PreserveAllColumns',true, ...
    'AntiAliasFilter','none', ...
    'WholeRecordDetrend','none', ...
    'Standardized',false, ...
    'MaximumOutputPoints',maximumPoints, ...
    'MaximumOutputElements',maximumElements);
end

function tolerance = ulpTolerance(first,second)
tolerance = 8*max(eps(abs(double(first))),eps(abs(double(second))));
end

function [maximumPoints,maximumElements] = parseResourceLimits( ...
        hardMaximumPoints,hardMaximumElements,varargin)
maximumPoints = hardMaximumPoints;
maximumElements = hardMaximumElements;
if mod(numel(varargin),2) ~= 0
    error('Acycle:Interpolate:InvalidOptions', ...
        'Optional resource limits must be supplied as name-value pairs.');
end
for index = 1:2:numel(varargin)
    name = varargin{index};
    if isstring(name) && isscalar(name)
        name = char(name);
    end
    if ~(ischar(name) && isrow(name))
        error('Acycle:Interpolate:InvalidOptions', ...
            'Every optional resource-limit name must be text.');
    end
    value = varargin{index+1};
    if ~(isnumeric(value) && isscalar(value) && isreal(value) && ...
            isfinite(value) && value >= 1 && value == fix(value))
        error('Acycle:Interpolate:InvalidOptions', ...
            'Every optional resource limit must be a positive finite integer.');
    end
    value = double(value);
    switch name
        case 'MaximumPoints'
            if value > hardMaximumPoints
                error('Acycle:Interpolate:InvalidOptions', ...
                    'MaximumPoints may lower but may not raise the fixed limit.');
            end
            maximumPoints = value;
        case 'MaximumElements'
            if value > hardMaximumElements
                error('Acycle:Interpolate:InvalidOptions', ...
                    'MaximumElements may lower but may not raise the fixed limit.');
            end
            maximumElements = value;
        otherwise
            error('Acycle:Interpolate:InvalidOptions', ...
                'Unknown optional resource-limit name: %s.',name);
    end
end
end
