function [result,meta] = acycleEmpiricalModeDecomposition(data,options)
%ACYCLEEMPIRICALMODEDECOMPOSITION Reusable EMD and EEMD numerical core.
%   [RESULT,META] = ACYCLEEMPIRICALMODEDECOMPOSITION(DATA,OPTIONS)
%   decomposes a finite, real N-by-2 [coordinate,value] series without
%   opening dialogs or figures, reading or writing files, changing folders,
%   or changing the caller's global random-number state.
%
%   OPTIONS.method is 'emd' (the default) or 'eemd'. Common option:
%       max_num_imf       positive integer, default 10
%
%   EMD-only options:
%       max_num_extrema   nonnegative integer, default 1
%       interpolation     'pchip' or 'spline', default 'pchip'
%
%   EEMD-only options:
%       ensemble_count    positive integer, default 100
%       noise_amplitude   noise standard deviation divided by the input
%                         sample standard deviation, default 0.2
%       random_seed       integer in [0,2^32-1], default 0
%       progress_fcn      optional FCN(fraction,message)
%       cancel_fcn        optional zero-input function returning true to
%                         cancel during an ensemble decomposition
%
%   Unknown fields and fields inactive for the chosen method are rejected.
%   DATA must be full SINGLE or DOUBLE, have at least four rows, and already
%   have unique, strictly increasing, near-uniform coordinates. The fixed
%   relative spacing tolerance is 1e-5. Rows are never sorted, removed,
%   merged, or interpolated.
%
%   RESULT is a scalar structure with coordinate, input, imfs, residual,
%   reconstruction, component_variance, and component_variance_percent.
%   EEMD uses a private MT19937 stream and a positive/negative noise pair
%   for every ensemble member, including ensemble_count=1. User callbacks
%   are invoked with the caller's global RNG state isolated.

narginchk(1,2);
if nargin < 2
    options = struct();
end

limits = struct( ...
    'maximum_input_rows',1e6, ...
    'maximum_num_imf',128, ...
    'maximum_ensemble_count',1000, ...
    'maximum_output_elements',16e6, ...
    'maximum_peak_elements',64e6, ...
    'maximum_work_units',2e9);
options = validateOptions(options,limits);
[working,sampling] = validateData(data,limits);

inputRows = size(working,1);
requestedComponents = options.max_num_imf+5;
outputElements = inputRows*requestedComponents;
if ~isfinite(outputElements) || ...
        outputElements > limits.maximum_output_elements
    error('Acycle:EMD:OutputLimitExceeded', ...
        ['input_rows times (max_num_imf + 5) must not exceed the ', ...
         'fixed output-element limit of %.17g.'], ...
        limits.maximum_output_elements);
end

if strcmp(options.method,'eemd')
    estimatedPeakElements = inputRows*(4*options.max_num_imf+10);
else
    estimatedPeakElements = inputRows*(options.max_num_imf+5);
end
if ~isfinite(estimatedPeakElements) || ...
        estimatedPeakElements > limits.maximum_peak_elements
    error('Acycle:EMD:PeakMemoryLimitExceeded', ...
        ['The estimated peak working set must not exceed the fixed ', ...
         'limit of %.17g DOUBLE elements.'], ...
        limits.maximum_peak_elements);
end

if strcmp(options.method,'eemd')
    requestedDecompositions = 2*options.ensemble_count;
    estimatedSiftingIterations = ceil(sqrt(inputRows));
else
    requestedDecompositions = 1;
    estimatedSiftingIterations = 1;
end
workUnits = inputRows*options.max_num_imf* ...
    estimatedSiftingIterations*requestedDecompositions;
if ~isfinite(workUnits) || workUnits > limits.maximum_work_units
    error('Acycle:EMD:WorkLimitExceeded', ...
        ['input_rows times max_num_imf times estimated sifting ', ...
         'iterations times the requested decomposition count must ', ...
         'not exceed %.17g.'], ...
        limits.maximum_work_units);
end

coordinate = working(:,1);
values = working(:,2);
[rawStandardDeviation,rawVariance,rawVarianceUnderflow, ...
    rawVarianceOverflow] = stableStandardDeviation(values);
if ~isfinite(rawStandardDeviation)
    error('Acycle:EMD:UnrepresentableVariance', ...
        ['The input sample standard deviation must be representable ', ...
         'as finite DOUBLE.']);
end

switch options.method
    case 'emd'
        [imfs,residual,algorithmInfo] = runEmd(values,options);
        actualDecompositionCount = 1;
        ensemblePairsCompleted = 0;
    case 'eemd'
        [imfs,residual] = runEemd( ...
            values,rawStandardDeviation,options);
        imfs = trimTrailingZeroImfs(imfs);
        algorithmInfo = struct();
        actualDecompositionCount = 2*options.ensemble_count;
        ensemblePairsCompleted = options.ensemble_count;
    otherwise
        error('Acycle:EMD:InternalMethod', ...
            'The validated decomposition method was not recognized.');
end

imfs = full(double(imfs));
residual = full(double(residual(:)));
if size(imfs,1) ~= inputRows || size(imfs,2) > options.max_num_imf || ...
        ~isequal(size(residual),[inputRows,1]) || ~isreal(imfs) || ...
        ~isreal(residual) || any(~isfinite(imfs(:))) || ...
        any(~isfinite(residual))
    error('Acycle:EMD:InvalidDecompositionOutput', ...
        'The decomposition did not produce finite, real components.');
end

components = [imfs,residual];
reconstruction = sum(components,2);
if any(~isfinite(reconstruction))
    error('Acycle:EMD:NonfiniteReconstruction', ...
        'The component reconstruction is not representable as finite DOUBLE.');
end
reconstructionError = reconstruction-values;
maximumAbsoluteError = max(abs(reconstructionError));
inputScale = max(abs(values));
if inputScale == 0
    relativeError = maximumAbsoluteError;
else
    relativeError = maximumAbsoluteError/inputScale;
end
if ~(isfinite(relativeError) && relativeError <= 1e-8)
    error('Acycle:EMD:ReconstructionFailed', ...
        ['The relative maximum reconstruction error %.17g exceeds the ', ...
         'fixed tolerance 1e-8.'],relativeError);
end

[componentStandardDeviation,componentVariance, ...
    componentVarianceUnderflow,componentVarianceOverflow] = ...
    stableStandardDeviation(components);
componentVarianceSum = sum(componentVariance);
if any(componentVarianceOverflow) || ...
        any(componentVarianceUnderflow) || ...
        ~isfinite(componentVarianceSum)
    if any(componentVarianceOverflow) || ~isfinite(componentVarianceSum)
        componentVarianceSum = Inf;
    end
    componentVariancePercent = ...
        100*normalizedSquares(componentStandardDeviation);
    componentVariancePercentDenominator = ...
        'scaled_component_standard_deviation_squares';
elseif componentVarianceSum == 0
    componentVariancePercent = zeros(size(componentVariance));
    componentVariancePercentDenominator = ...
        'component_variance_sum';
else
    componentVariancePercent = ...
        100*(componentVariance/componentVarianceSum);
    componentVariancePercentDenominator = ...
        'component_variance_sum';
end
componentVarianceRepresentable = ...
    ~(componentVarianceUnderflow | componentVarianceOverflow);
componentVarianceSumRepresentable = ...
    all(componentVarianceRepresentable) && isfinite(componentVarianceSum);
if isfinite(rawVariance) && isfinite(componentVarianceSum) && ...
        ~rawVarianceUnderflow && ~any(componentVarianceUnderflow)
    covarianceGap = rawVariance-componentVarianceSum;
    covarianceGapDefined = true;
else
    covarianceGap = NaN;
    covarianceGapDefined = false;
end
if rawVariance == 0 || rawVarianceOverflow || rawVarianceUnderflow || ...
        any(componentVarianceUnderflow) || ...
        ~isfinite(componentVarianceSum)
    varianceRatio = 0;
    varianceRatioDefined = false;
else
    varianceRatio = componentVarianceSum/rawVariance;
    varianceRatioDefined = true;
end

result = struct( ...
    'coordinate',coordinate, ...
    'input',values, ...
    'imfs',imfs, ...
    'residual',residual, ...
    'reconstruction',reconstruction, ...
    'component_variance',componentVariance, ...
    'component_variance_percent',componentVariancePercent);

parameters = publicParameters(options);
meta = struct( ...
    'version','empirical-mode-decomposition-v1', ...
    'method',options.method, ...
    'parameters',parameters, ...
    'input_policy', ...
        'strict-finite-real-two-column-increasing-near-uniform', ...
    'input_class',class(data), ...
    'input_rows',inputRows, ...
    'input_columns',2, ...
    'coordinate_start',coordinate(1), ...
    'coordinate_end',coordinate(end), ...
    'sample_interval',sampling.MedianSpacing, ...
    'spacing_minimum',sampling.SpacingMinimum, ...
    'spacing_maximum',sampling.SpacingMaximum, ...
    'maximum_spacing_error',sampling.MaximumSpacingError, ...
    'relative_spacing_error',sampling.RelativeSpacingError, ...
    'spacing_tolerance',sampling.RelativeTolerance, ...
    'requested_num_imf',options.max_num_imf, ...
    'actual_num_imf',size(imfs,2), ...
    'actual_decomposition_count',actualDecompositionCount, ...
    'ensemble_pairs_completed',ensemblePairsCompleted, ...
    'algorithm_info',algorithmInfo, ...
    'raw_standard_deviation',rawStandardDeviation, ...
    'raw_variance',rawVariance, ...
    'raw_variance_underflow',rawVarianceUnderflow, ...
    'raw_variance_overflow',rawVarianceOverflow, ...
    'raw_variance_representable', ...
        ~(rawVarianceOverflow || rawVarianceUnderflow), ...
    'component_standard_deviation',componentStandardDeviation, ...
    'component_variance',componentVariance, ...
    'component_variance_underflow',componentVarianceUnderflow, ...
    'component_variance_overflow',componentVarianceOverflow, ...
    'component_variance_representable', ...
        componentVarianceRepresentable, ...
    'component_variance_percent',componentVariancePercent, ...
    'component_variance_percent_denominator', ...
        componentVariancePercentDenominator, ...
    'component_variance_sum',componentVarianceSum, ...
    'component_variance_sum_representable', ...
        componentVarianceSumRepresentable, ...
    'component_variance_sum_over_raw_variance',varianceRatio, ...
    'variance_ratio_defined',varianceRatioDefined, ...
    'covariance_gap',covarianceGap, ...
    'covariance_gap_defined',covarianceGapDefined, ...
    'covariance_gap_formula', ...
        'raw_variance-component_variance_sum', ...
    'reconstruction_maximum_absolute_error',maximumAbsoluteError, ...
    'reconstruction_relative_error',relativeError, ...
    'reconstruction_relative_tolerance',1e-8, ...
    'maximum_input_rows',limits.maximum_input_rows, ...
    'maximum_num_imf',limits.maximum_num_imf, ...
    'maximum_ensemble_count',limits.maximum_ensemble_count, ...
    'maximum_output_elements',limits.maximum_output_elements, ...
    'maximum_peak_elements',limits.maximum_peak_elements, ...
    'maximum_work_units',limits.maximum_work_units, ...
    'estimated_output_elements',outputElements, ...
    'estimated_peak_elements',estimatedPeakElements, ...
    'estimated_sifting_iterations_per_imf', ...
        estimatedSiftingIterations, ...
    'estimated_work_units',workUnits, ...
    'sorted',false, ...
    'removed_rows',0, ...
    'interpolated',false, ...
    'file_io',false, ...
    'graphics',false, ...
    'dialogs',false, ...
    'current_folder_modified',false, ...
    'global_random_state_modified',false, ...
    'random_number_generation',strcmp(options.method,'eemd'), ...
    'random_stream',randomStreamName(options), ...
    'side_effect_policy','none_except_user_callbacks');
end

function options = validateOptions(options,limits)
if ~(isstruct(options) && isscalar(options))
    error('Acycle:EMD:InvalidOptions', ...
        'OPTIONS must be one scalar structure.');
end

knownFields = {'method','max_num_imf','max_num_extrema', ...
    'interpolation','ensemble_count','noise_amplitude','random_seed', ...
    'progress_fcn','cancel_fcn'};
fields = fieldnames(options);
unknown = setdiff(fields,knownFields);
if ~isempty(unknown)
    error('Acycle:EMD:UnknownOption', ...
        'Unknown OPTIONS field: %s.',strjoin(unknown,', '));
end
if ~isfield(options,'method')
    options.method = 'emd';
end
options.method = textChoice(options.method,{'emd','eemd'},'method');

if strcmp(options.method,'emd')
    activeFields = {'method','max_num_imf','max_num_extrema', ...
        'interpolation'};
else
    activeFields = {'method','max_num_imf','ensemble_count', ...
        'noise_amplitude','random_seed','progress_fcn','cancel_fcn'};
end
inactive = setdiff(fields,activeFields);
if ~isempty(inactive)
    error('Acycle:EMD:InactiveOption', ...
        'OPTIONS field is inactive for method %s: %s.', ...
        options.method,strjoin(inactive,', '));
end

if ~isfield(options,'max_num_imf')
    options.max_num_imf = 10;
end
options.max_num_imf = finiteInteger(options.max_num_imf,1, ...
    limits.maximum_num_imf,'max_num_imf');

if strcmp(options.method,'emd')
    if ~isfield(options,'max_num_extrema')
        options.max_num_extrema = 1;
    end
    options.max_num_extrema = finiteInteger( ...
        options.max_num_extrema,0,realmax('double'),'max_num_extrema');
    if ~isfield(options,'interpolation')
        options.interpolation = 'pchip';
    end
    options.interpolation = textChoice( ...
        options.interpolation,{'pchip','spline'},'interpolation');
else
    if ~isfield(options,'ensemble_count')
        options.ensemble_count = 100;
    end
    options.ensemble_count = finiteInteger(options.ensemble_count,1, ...
        limits.maximum_ensemble_count,'ensemble_count');
    if ~isfield(options,'noise_amplitude')
        options.noise_amplitude = 0.2;
    end
    options.noise_amplitude = nonnegativeFiniteScalar( ...
        options.noise_amplitude,'noise_amplitude');
    if ~isfield(options,'random_seed')
        options.random_seed = 0;
    end
    options.random_seed = finiteInteger( ...
        options.random_seed,0,2^32-1,'random_seed');
    if ~isfield(options,'progress_fcn')
        options.progress_fcn = [];
    end
    if ~isfield(options,'cancel_fcn')
        options.cancel_fcn = [];
    end
    validateCallback(options.progress_fcn,'progress_fcn');
    validateCallback(options.cancel_fcn,'cancel_fcn');
end
end

function [working,sampling] = validateData(data,limits)
if ~((isa(data,'double') || isa(data,'single')) && ...
        ~issparse(data) && isreal(data) && ismatrix(data) && ...
        size(data,2) == 2)
    error('Acycle:EMD:InvalidData', ...
        ['DATA must be a full, real SINGLE or DOUBLE N-by-2 matrix ', ...
         '[coordinate,value].']);
end
inputRows = size(data,1);
if inputRows < 4
    error('Acycle:EMD:TooFewRows', ...
        'DATA must contain at least four rows.');
end
if inputRows > limits.maximum_input_rows
    error('Acycle:EMD:InputRowLimitExceeded', ...
        'DATA exceeds the fixed maximum of %.17g rows.', ...
        limits.maximum_input_rows);
end
if any(~isfinite(data(:)))
    error('Acycle:EMD:NonfiniteData', ...
        'Every DATA coordinate and value must be finite.');
end

working = full(double(data));
coordinate = working(:,1);
spacing = diff(coordinate);
if any(~isfinite(spacing)) || any(spacing <= 0)
    error('Acycle:EMD:CoordinatesNotStrictlyIncreasing', ...
        ['DATA coordinates must already be unique and strictly ', ...
         'increasing.']);
end
[isUneven,spacingInfo] = acycleSamplingIsUneven(coordinate,1e-5);
if isUneven
    error('Acycle:EMD:UnevenSampling', ...
        ['Relative spacing error %.17g exceeds the fixed near-uniform ', ...
         'tolerance %.17g.'], ...
        spacingInfo.RelativeSpacingError,spacingInfo.RelativeTolerance);
end
sampling = spacingInfo;
sampling.SpacingMinimum = min(spacing);
sampling.SpacingMaximum = max(spacing);
end

function [imfs,residual,info] = runEmd(values,options)
if exist('emd','file') ~= 2
    error('Acycle:EMD:MissingEmdFunction', ...
        ['EMD requires MATLAB''s Signal Processing Toolbox EMD ', ...
         'function.']);
end
[imfs,residual,info] = emd(values, ...
    'MaxNumIMF',options.max_num_imf, ...
    'MaxNumExtrema',options.max_num_extrema, ...
    'Interpolation',options.interpolation, ...
    'Display',false);
end

function [imfs,residual] = runEemd(values,rawStandardDeviation,options)
pointCount = numel(values);
modeCount = options.max_num_imf+1;
averagedModes = zeros(modeCount,pointCount);
noiseScale = rawStandardDeviation*options.noise_amplitude;
if ~(isfinite(noiseScale) && noiseScale >= 0)
    error('Acycle:EMD:UnrepresentableNoiseScale', ...
        ['noise_amplitude times the input sample standard deviation ', ...
         'must be representable as finite DOUBLE.']);
end
if rawStandardDeviation > 0 && options.noise_amplitude > 0 && ...
        noiseScale == 0
    error('Acycle:EMD:UnrepresentableNoiseScale', ...
        ['The requested nonzero EEMD noise scale underflows the ', ...
         'DOUBLE representation.']);
end

stream = RandStream('mt19937ar','Seed',options.random_seed);
throwIfCanceled(options.cancel_fcn);
notifyProgress(options.progress_fcn,0,'EEMD: starting ensemble pairs');
pollFcn = @()throwIfCanceled(options.cancel_fcn);
for ensembleIndex = 1:options.ensemble_count
    noise = noiseScale*randn(stream,1,pointCount);
    if any(~isfinite(noise))
        error('Acycle:EMD:NonfiniteNoise', ...
            'The requested EEMD noise is not representable as finite DOUBLE.');
    end
    positiveModes = emdNL( ...
        values.'+noise,options.max_num_imf,pollFcn);
    throwIfCanceled(options.cancel_fcn);
    negativeModes = emdNL( ...
        values.'-noise,options.max_num_imf,pollFcn);
    if ~isequal(size(positiveModes),[modeCount,pointCount]) || ...
            ~isequal(size(negativeModes),[modeCount,pointCount]) || ...
            any(~isfinite(positiveModes(:))) || ...
            any(~isfinite(negativeModes(:)))
        error('Acycle:EMD:InvalidEnsembleMember', ...
            'An EEMD noise pair produced invalid component dimensions.');
    end
    positiveModes = 0.5*positiveModes+0.5*negativeModes;
    averagedModes = averagedModes+ ...
        (positiveModes-averagedModes)/ensembleIndex;
    if any(~isfinite(averagedModes(:)))
        error('Acycle:EMD:NonfiniteEnsembleAverage', ...
            'The EEMD ensemble average is not representable as finite DOUBLE.');
    end
    if ensembleIndex < options.ensemble_count
        throwIfCanceled(options.cancel_fcn);
    end
    notifyProgress(options.progress_fcn, ...
        ensembleIndex/options.ensemble_count,sprintf( ...
        'EEMD: completed ensemble pair %d of %d', ...
        ensembleIndex,options.ensemble_count));
end
imfs = averagedModes(1:end-1,:).';
residual = averagedModes(end,:).';
end

function [standardDeviation,variance,varianceUnderflow, ...
        varianceOverflow] = ...
        stableStandardDeviation(values)
columnScale = max(abs(values),[],1);
standardDeviation = zeros(size(columnScale));
nonzero = columnScale > 0;
if any(nonzero)
    scaledValues = values(:,nonzero)./columnScale(nonzero);
    scaledVariance = var(scaledValues,0,1);
    standardDeviation(nonzero) = ...
        columnScale(nonzero).*sqrt(scaledVariance);
end
variance = standardDeviation.*standardDeviation;
varianceUnderflow = standardDeviation > 0 & variance == 0;
varianceOverflow = isfinite(standardDeviation) & isinf(variance);
end

function proportions = normalizedSquares(values)
scale = max(values);
if scale == 0
    proportions = zeros(size(values));
    return
end
scaled = values/scale;
denominator = sum(scaled.*scaled);
if denominator == 0
    proportions = zeros(size(values));
else
    proportions = (scaled.*scaled)/denominator;
end
end


function imfs = trimTrailingZeroImfs(imfs)
lastNonzero = find(any(imfs ~= 0,1),1,'last');
if isempty(lastNonzero)
    imfs = zeros(size(imfs,1),0);
else
    imfs = imfs(:,1:lastNonzero);
end
end

function notifyProgress(callback,fraction,message)
if isempty(callback)
    return
end
randomState = rng;
restoreRandomState = onCleanup(@()rng(randomState));
try
    callback(max(0,min(1,fraction)),message);
catch exception
    callbackError = MException('Acycle:EMD:ProgressCallbackFailed', ...
        'The EMD progress callback failed: %s',exception.message);
    callbackError = addCause(callbackError,exception);
    throw(callbackError);
end
clear restoreRandomState
end

function throwIfCanceled(callback)
if isempty(callback)
    return
end
randomState = rng;
restoreRandomState = onCleanup(@()rng(randomState));
try
    canceled = callback();
catch exception
    callbackError = MException('Acycle:EMD:CancelCallbackFailed', ...
        'The EMD cancel callback failed: %s',exception.message);
    callbackError = addCause(callbackError,exception);
    throw(callbackError);
end
clear restoreRandomState
if ~((islogical(canceled) || isnumeric(canceled)) && ...
        isreal(canceled) && isscalar(canceled) && isfinite(canceled) && ...
        (canceled == 0 || canceled == 1))
    error('Acycle:EMD:InvalidCancelResult', ...
        'cancel_fcn must return one logical value.');
end
if logical(canceled)
    error('Acycle:EMD:Canceled','EMD analysis canceled by user.');
end
end

function parameters = publicParameters(options)
parameters = struct( ...
    'method',options.method, ...
    'max_num_imf',options.max_num_imf);
if strcmp(options.method,'emd')
    parameters.max_num_extrema = options.max_num_extrema;
    parameters.interpolation = options.interpolation;
else
    parameters.ensemble_count = options.ensemble_count;
    parameters.noise_amplitude = options.noise_amplitude;
    parameters.random_seed = options.random_seed;
    parameters.progress_callback_installed = ...
        ~isempty(options.progress_fcn);
    parameters.cancel_callback_installed = ...
        ~isempty(options.cancel_fcn);
end
end

function name = randomStreamName(options)
if strcmp(options.method,'eemd')
    name = 'private-mt19937ar';
else
    name = 'none';
end
end

function value = finiteInteger(value,minimum,maximum,label)
if ~(isnumeric(value) && ~islogical(value) && isreal(value) && ...
        isscalar(value) && isfinite(value) && value == fix(value) && ...
        value >= minimum && value <= maximum)
    error('Acycle:EMD:InvalidIntegerOption', ...
        '%s must be an integer in [%.17g,%.17g].', ...
        label,minimum,maximum);
end
value = double(value);
end

function value = nonnegativeFiniteScalar(value,label)
if ~(isnumeric(value) && ~islogical(value) && isreal(value) && ...
        isscalar(value) && isfinite(value) && value >= 0)
    error('Acycle:EMD:InvalidNonnegativeOption', ...
        '%s must be one finite nonnegative real scalar.',label);
end
value = double(value);
end

function value = textChoice(value,choices,label)
if isstring(value) && isscalar(value)
    value = char(value);
end
if ~(ischar(value) && isrow(value) && ~isempty(strtrim(value)))
    error('Acycle:EMD:InvalidTextOption', ...
        '%s must be one of: %s.',label,strjoin(choices,', '));
end
value = lower(strtrim(value));
if ~any(strcmp(value,choices))
    error('Acycle:EMD:InvalidTextOption', ...
        '%s must be one of: %s.',label,strjoin(choices,', '));
end
end

function validateCallback(value,label)
if ~(isempty(value) || isa(value,'function_handle'))
    error('Acycle:EMD:InvalidCallback', ...
        '%s must be empty or a function handle.',label);
end
end
