function [result,meta] = acycleLeadLagRmse( ...
        reference,target,maximumLag,lagStep,coordinateDirection)
%ACYCLELEADLAGRMSE Deterministic standardized-RMSE lead/lag analysis.
%   [RESULT,META] = ACYCLELEADLAGRMSE(REFERENCE,TARGET,MAXIMUMLAG,
%   LAGSTEP,COORDINATEDIRECTION) compares two strict N-by-2 series. Both
%   inputs must be full, finite, real SINGLE or DOUBLE matrices with at
%   least three rows and unique, strictly increasing coordinates. The core
%   never sorts, merges, deletes, fills, or otherwise preprocesses rows.
%
%   Lag has one fixed numerical definition:
%
%       shifted_target_coordinate = target_coordinate + lag
%
%   The candidate grid is the symmetric integer-multiple grid
%
%       (-floor(MAXIMUMLAG/LAGSTEP):floor(...)) * LAGSTEP
%
%   after ULP-scale reconciliation of a quotient that is numerically next
%   to an integer and guarding against floating-point overshoot. It always
%   contains -LAGSTEP, zero, and +LAGSTEP. META reports the requested and
%   actual maximum lag and their nonnegative quantization difference.
%
%   REFERENCE and TARGET values are each standardized exactly once over
%   their complete input record using their sample mean and sample standard
%   deviation (N-1 normalization). Constant or numerically degenerate value
%   columns are rejected. For each lag, the complete shifted TARGET is
%   linearly interpolated at REFERENCE coordinates inside shifted TARGET
%   support; extrapolation is never used. Candidates with fewer than three
%   matched REFERENCE coordinates are explicitly omitted. Zero lag must be
%   eligible, and at least one finite result must exist, or the call fails
%   atomically.
%
%   RESULT columns are:
%     [lag, standardized_rmse, matched_count, overlap_start, overlap_end]
%
%   OVERLAP_START and OVERLAP_END are the first and last matched REFERENCE
%   coordinates actually used for that row. The best lag is the exact
%   minimum RMSE; exact ties are resolved by minimum ABS(LAG), then by the
%   smaller signed lag. Tie count and all tied lags are retained in META.
%
%   COORDINATEDIRECTION is 'small_is_young' or 'small_is_old'. It changes
%   only the textual interpretation of lag sign in META, never the grid or
%   calculation. This is a descriptive standardized-RMSE metric: it is not
%   correlation, a significance test, or a confidence interval.
%
%   The fixed limits are 100001 lag candidates and 10000000 interpolated
%   matched values. The function performs no plotting, file or dialog I/O,
%   working-directory or path changes, random-number generation, base-
%   workspace access, or graphics-root mutation.

narginchk(5,5);

maximumLagCandidates = 100001;
maximumInterpolationWork = 1e7;
minimumMatchedCount = 3;

[reference,referenceInfo] = validateSeries(reference,'REFERENCE');
[target,targetInfo] = validateSeries(target,'TARGET');
maximumLag = positiveScalar(maximumLag,'MAXIMUMLAG');
lagStep = positiveScalar(lagStep,'LAGSTEP');
coordinateDirection = directionChoice(coordinateDirection);

rawHalfCount = maximumLag/lagStep;
if ~isfinite(rawHalfCount)
    error('Acycle:LeadLagRmse:UnrepresentableLagRatio', ...
        'MAXIMUMLAG/LAGSTEP must be representable as a finite DOUBLE.');
end
nearestHalfCount = round(rawHalfCount);
halfCountTolerance = 8*eps(max(1,abs(rawHalfCount)));
if abs(rawHalfCount-nearestHalfCount) <= halfCountTolerance
    halfCount = nearestHalfCount;
else
    halfCount = floor(rawHalfCount);
end
if halfCount < 1
    error('Acycle:LeadLagRmse:LagGridTooSmall', ...
        ['MAXIMUMLAG must admit at least one full LAGSTEP on each side ', ...
         'of zero.']);
end
unreconciledMaximumLag = halfCount*lagStep;
endpointTolerance = 16*max([ ...
    eps(abs(maximumLag)),eps(abs(unreconciledMaximumLag)), ...
    eps(abs(lagStep))]);
endpointNearRequestedMaximum = ...
    abs(unreconciledMaximumLag-maximumLag) <= endpointTolerance;
lagEndpointReconciled = endpointNearRequestedMaximum && ...
    unreconciledMaximumLag ~= maximumLag;
while halfCount >= 1 && unreconciledMaximumLag > maximumLag && ...
        ~endpointNearRequestedMaximum
    % A genuinely larger integer multiple must never exceed the request.
    halfCount = halfCount-1;
    unreconciledMaximumLag = halfCount*lagStep;
end
if halfCount < 1
    error('Acycle:LeadLagRmse:LagGridTooSmall', ...
        ['MAXIMUMLAG must admit at least one full LAGSTEP on each side ', ...
         'of zero.']);
end
maximumHalfCount = (maximumLagCandidates-1)/2;
if halfCount > maximumHalfCount
    error('Acycle:LeadLagRmse:LagCandidateLimitExceeded', ...
        ['The symmetric lag grid would exceed the fixed maximum of ', ...
         '%d candidates.'],maximumLagCandidates);
end

lagGrid = (-halfCount:halfCount)'*lagStep;
zeroIndex = halfCount+1;
lagGrid(zeroIndex) = 0;
if endpointNearRequestedMaximum
    lagGrid(1) = -maximumLag;
    lagGrid(end) = maximumLag;
end
if any(~isfinite(lagGrid)) || any(diff(lagGrid) <= 0) || ...
        lagGrid(1) ~= -lagGrid(end)
    error('Acycle:LeadLagRmse:UnrepresentableLagGrid', ...
        ['The requested lag grid cannot be represented as a finite, ', ...
         'strictly increasing symmetric DOUBLE vector.']);
end
candidateCount = numel(lagGrid);
actualMaximumLag = lagGrid(end);
maximumLagQuantizationError = maximumLag-actualMaximumLag;
if ~(isfinite(maximumLagQuantizationError) && ...
        maximumLagQuantizationError >= 0)
    error('Acycle:LeadLagRmse:InvalidLagQuantization', ...
        'The lag-grid quantization difference must be finite and nonnegative.');
end

referenceCoordinate = reference(:,1);
targetCoordinate = target(:,1);
referenceRows = size(reference,1);

% Zero lag is a mandatory anchor. Check it before resource accounting so a
% request with no scientifically usable zero-lag comparison fails for the
% direct contract reason.
[~,~,~,~,zeroMatchedCount] = supportAtLag( ...
    referenceCoordinate,targetCoordinate,0);
if zeroMatchedCount < minimumMatchedCount
    error('Acycle:LeadLagRmse:ZeroLagInsufficientSupport', ...
        ['Zero lag has only %d matched REFERENCE coordinates; at least ', ...
         '%d are required.'],zeroMatchedCount,minimumMatchedCount);
end

matchedCounts = zeros(candidateCount,1);
firstMatchedIndex = zeros(candidateCount,1);
lastMatchedIndex = zeros(candidateCount,1);
supportIntersectionStart = zeros(candidateCount,1);
supportIntersectionEnd = zeros(candidateCount,1);
interpolationWork = 0;
for candidateIndex = 1:candidateCount
    [supportIntersectionStart(candidateIndex), ...
        supportIntersectionEnd(candidateIndex), ...
        firstMatchedIndex(candidateIndex), ...
        lastMatchedIndex(candidateIndex), ...
        matchedCounts(candidateIndex)] = supportAtLag( ...
            referenceCoordinate,targetCoordinate,lagGrid(candidateIndex));
    if matchedCounts(candidateIndex) >= minimumMatchedCount
        interpolationWork = interpolationWork+matchedCounts(candidateIndex);
        if interpolationWork > maximumInterpolationWork
            error('Acycle:LeadLagRmse:InterpolationWorkLimitExceeded', ...
                ['Eligible lag candidates would require more than the ', ...
                 'fixed maximum of %.0f interpolated matched values.'], ...
                maximumInterpolationWork);
        end
    end
end

eligibleMask = matchedCounts >= minimumMatchedCount;
if ~any(eligibleMask)
    error('Acycle:LeadLagRmse:NoEligibleLag', ...
        ['No lag candidate has the required minimum of %d matched ', ...
         'REFERENCE coordinates.'],minimumMatchedCount);
end

referenceStandardized = standardizeWholeRecord( ...
    reference(:,2),'REFERENCE');
targetStandardized = standardizeWholeRecord(target(:,2),'TARGET');

eligibleIndices = find(eligibleMask);
resultRows = numel(eligibleIndices);
result = zeros(resultRows,5);
for outputIndex = 1:resultRows
    candidateIndex = eligibleIndices(outputIndex);
    lag = lagGrid(candidateIndex);
    shiftedTargetCoordinate = targetCoordinate+lag;
    if any(~isfinite(shiftedTargetCoordinate)) || ...
            any(diff(shiftedTargetCoordinate) <= 0)
        error('Acycle:LeadLagRmse:UnrepresentableShiftedTarget', ...
            ['TARGET coordinates shifted by lag %.17g are not finite ', ...
             'and strictly increasing in DOUBLE precision.'],lag);
    end

    firstIndex = firstMatchedIndex(candidateIndex);
    lastIndex = lastMatchedIndex(candidateIndex);
    referenceIndex = firstIndex:lastIndex;
    matchedReferenceCoordinate = referenceCoordinate(referenceIndex);
    interpolatedTarget = interp1( ...
        shiftedTargetCoordinate,targetStandardized, ...
        matchedReferenceCoordinate,'linear');
    if any(~isfinite(interpolatedTarget))
        error('Acycle:LeadLagRmse:NonfiniteInterpolation', ...
            ['Linear interpolation produced a nonfinite value at lag ', ...
             '%.17g; no partial result is returned.'],lag);
    end
    difference = interpolatedTarget-referenceStandardized(referenceIndex);
    standardizedRmse = sqrt(mean(difference.^2));
    if ~(isfinite(standardizedRmse) && standardizedRmse >= 0)
        error('Acycle:LeadLagRmse:NonfiniteRmse', ...
            'Lag %.17g produced a nonfinite standardized RMSE.',lag);
    end
    result(outputIndex,:) = [ ...
        lag,standardizedRmse,matchedCounts(candidateIndex), ...
        matchedReferenceCoordinate(1),matchedReferenceCoordinate(end)];
end

if ~(isa(result,'double') && isreal(result) && size(result,2) == 5 && ...
        all(isfinite(result),'all') && all(diff(result(:,1)) > 0) && ...
        all(result(:,3) >= minimumMatchedCount) && ...
        all(result(:,3) == fix(result(:,3))) && ...
        any(result(:,1) == 0))
    error('Acycle:LeadLagRmse:InvalidOutput', ...
        ['Lead-lag analysis must return a finite five-column result with ', ...
         'increasing lags and an eligible zero-lag row.']);
end

minimumRmse = min(result(:,2));
tiedResultRows = find(result(:,2) == minimumRmse);
tiedLags = result(tiedResultRows,1);
[~,tieOrder] = sortrows([abs(tiedLags),tiedLags],[1 2]);
bestResultRow = tiedResultRows(tieOrder(1));
bestLag = result(bestResultRow,1);
[negativeInterpretation,zeroInterpretation,positiveInterpretation] = ...
    directionInterpretations(coordinateDirection);
bestInterpretation = interpretationForLag( ...
    bestLag,negativeInterpretation,zeroInterpretation, ...
    positiveInterpretation);

candidateCoverageFractions = matchedCounts/referenceRows;
includedCoverageFractions = result(:,3)/referenceRows;
omittedMask = ~eligibleMask;
meta = struct( ...
    'version','lead-lag-rmse-v1', ...
    'analysis_scope','deterministic-descriptive-standardized-rmse', ...
    'input_policy', ...
        'strict-finite-real-single-or-double-n-by-2-unique-increasing', ...
    'result_columns',{{'lag','standardized_rmse','matched_count', ...
        'overlap_start','overlap_end'}}, ...
    'result_rows',resultRows, ...
    'result_columns_count',5, ...
    'reference_rows',referenceInfo.rows, ...
    'target_rows',targetInfo.rows, ...
    'reference_coordinate_start',referenceInfo.coordinate_start, ...
    'reference_coordinate_end',referenceInfo.coordinate_end, ...
    'target_coordinate_start',targetInfo.coordinate_start, ...
    'target_coordinate_end',targetInfo.coordinate_end, ...
    'requested_maximum_lag',maximumLag, ...
    'lag_step',lagStep, ...
    'raw_maximum_lag_steps',rawHalfCount, ...
    'actual_maximum_lag',actualMaximumLag, ...
    'maximum_lag_quantization_error',maximumLagQuantizationError, ...
    'lag_endpoint_reconciled',lagEndpointReconciled, ...
    'lag_endpoint_reconciliation_policy', ...
        'reconcile-requested-maximum-within-sixteen-ulps', ...
    'lag_grid_policy', ...
        'symmetric-integer-multiples-of-lag-step-with-zero', ...
    'lag_candidate_count',candidateCount, ...
    'candidate_lags',lagGrid, ...
    'coordinate_direction',coordinateDirection, ...
    'lag_definition','shifted_target_coordinate=target_coordinate+lag', ...
    'direction_affects_calculation',false, ...
    'negative_lag_interpretation',negativeInterpretation, ...
    'zero_lag_interpretation',zeroInterpretation, ...
    'positive_lag_interpretation',positiveInterpretation, ...
    'candidate_matched_counts',matchedCounts, ...
    'candidate_coverage_fractions',candidateCoverageFractions, ...
    'candidate_support_intersection_start',supportIntersectionStart, ...
    'candidate_support_intersection_end',supportIntersectionEnd, ...
    'eligible_candidate_mask',eligibleMask, ...
    'included_lags',result(:,1), ...
    'included_coverage_fractions',includedCoverageFractions, ...
    'omitted_lags',lagGrid(omittedMask), ...
    'omitted_lag_count',sum(omittedMask), ...
    'omission_policy','omit-matched-count-below-three', ...
    'minimum_matched_count',minimumMatchedCount, ...
    'zero_lag_matched_count',matchedCounts(zeroIndex), ...
    'zero_lag_coverage_fraction', ...
        candidateCoverageFractions(zeroIndex), ...
    'overlap_result_policy', ...
        'first-and-last-matched-reference-coordinates', ...
    'interpolation_method','linear', ...
    'interpolation_grid', ...
        'reference-coordinates-inside-shifted-target-support', ...
    'extrapolated',false, ...
    'standardization_scope','each-whole-input-record-once', ...
    'reference_standardization','sample-mean-and-sample-standard-deviation', ...
    'target_standardization','sample-mean-and-sample-standard-deviation', ...
    'standard_deviation_normalization','n-minus-one', ...
    'metric','standardized_rmse', ...
    'metric_definition', ...
        'root-mean-square-standardized-difference-on-matched-reference-grid', ...
    'best_result_row',bestResultRow, ...
    'best_lag',bestLag, ...
    'best_standardized_rmse',result(bestResultRow,2), ...
    'best_matched_count',result(bestResultRow,3), ...
    'best_overlap_start',result(bestResultRow,4), ...
    'best_overlap_end',result(bestResultRow,5), ...
    'best_coverage_fraction',includedCoverageFractions(bestResultRow), ...
    'best_lag_interpretation',bestInterpretation, ...
    'tie_policy','exact-rmse-then-minimum-absolute-lag-then-smaller-lag', ...
    'tie_count',numel(tiedLags), ...
    'tied_lags',tiedLags, ...
    'correlation_estimated',false, ...
    'significance_tested',false, ...
    'confidence_interval_estimated',false, ...
    'interpolation_work',interpolationWork, ...
    'maximum_lag_candidates',maximumLagCandidates, ...
    'maximum_interpolation_work',maximumInterpolationWork, ...
    'sorted',false, ...
    'merged_duplicates',false, ...
    'removed_rows',0, ...
    'file_io',false, ...
    'graphics',false, ...
    'dialogs',false, ...
    'working_directory_changes',false, ...
    'path_changes',false, ...
    'base_workspace_access',false, ...
    'root_state_changes',false, ...
    'random_number_generation',false, ...
    'side_effect_policy','none');
end

function [data,info] = validateSeries(data,label)
if ~((isa(data,'double') || isa(data,'single')) && ...
        ~issparse(data) && isreal(data) && ismatrix(data) && ...
        size(data,2) == 2)
    error('Acycle:LeadLagRmse:InvalidData', ...
        ['%s must be a full, real SINGLE or DOUBLE N-by-2 matrix ', ...
         '[coordinate,value].'],label);
end
if size(data,1) < 3
    error('Acycle:LeadLagRmse:TooFewRows', ...
        '%s must contain at least three rows.',label);
end
if any(~isfinite(data(:)))
    error('Acycle:LeadLagRmse:NonfiniteData', ...
        'Every coordinate and value in %s must be finite.',label);
end
data = full(double(data));
coordinate = data(:,1);
spacing = diff(coordinate);
if any(~isfinite(spacing))
    error('Acycle:LeadLagRmse:UnrepresentableCoordinateSpacing', ...
        '%s coordinate spacing must be finite in DOUBLE precision.',label);
end
if any(spacing <= 0)
    error('Acycle:LeadLagRmse:CoordinatesNotStrictlyIncreasing', ...
        ['%s coordinates must already be unique and strictly increasing; ', ...
         'rows are never sorted or merged.'],label);
end
coordinateSpan = coordinate(end)-coordinate(1);
if ~(isfinite(coordinateSpan) && coordinateSpan > 0)
    error('Acycle:LeadLagRmse:UnrepresentableCoordinateSpan', ...
        '%s coordinate span must be finite and positive.',label);
end
info = struct( ...
    'rows',size(data,1), ...
    'coordinate_start',coordinate(1), ...
    'coordinate_end',coordinate(end));
end

function value = positiveScalar(value,label)
if ~(isnumeric(value) && ~islogical(value) && isreal(value) && ...
        isscalar(value) && isfinite(value) && value > 0)
    error('Acycle:LeadLagRmse:InvalidPositiveScalar', ...
        '%s must be a finite positive real numeric scalar.',label);
end
value = double(value);
end

function direction = directionChoice(direction)
if isstring(direction) && isscalar(direction)
    direction = char(direction);
end
if ~(ischar(direction) && isrow(direction) && ...
        any(strcmp(direction,{'small_is_young','small_is_old'})))
    error('Acycle:LeadLagRmse:InvalidCoordinateDirection', ...
        ['COORDINATEDIRECTION must be ''small_is_young'' or ', ...
         '''small_is_old''.']);
end
end

function standardized = standardizeWholeRecord(values,label)
valueScale = max(abs(values));
if valueScale == 0
    error('Acycle:LeadLagRmse:ConstantSeries', ...
        '%s value column is constant; standardized RMSE is undefined.', ...
        label);
end
scaled = values/valueScale;
scaledMean = mean(scaled);
centered = scaled-scaledMean;
sampleStandardDeviation = std(centered,0);
if ~(isfinite(scaledMean) && isfinite(sampleStandardDeviation) && ...
        sampleStandardDeviation > 0)
    error('Acycle:LeadLagRmse:ConstantSeries', ...
        ['%s value column has no representable nonzero sample standard ', ...
         'deviation.'],label);
end
standardized = centered/sampleStandardDeviation;
if any(~isfinite(standardized))
    error('Acycle:LeadLagRmse:NonfiniteStandardization', ...
        '%s standardization produced a nonfinite value.',label);
end
end

function [supportStart,supportEnd,firstIndex,lastIndex,count] = ...
        supportAtLag(referenceCoordinate,targetCoordinate,lag)
shiftedTargetStart = targetCoordinate(1)+lag;
shiftedTargetEnd = targetCoordinate(end)+lag;
if ~(isfinite(shiftedTargetStart) && isfinite(shiftedTargetEnd) && ...
        shiftedTargetStart < shiftedTargetEnd)
    error('Acycle:LeadLagRmse:UnrepresentableShiftedTarget', ...
        ['TARGET support shifted by lag %.17g is not a finite, positive ', ...
         'interval in DOUBLE precision.'],lag);
end
supportStart = max(referenceCoordinate(1),shiftedTargetStart);
supportEnd = min(referenceCoordinate(end),shiftedTargetEnd);
firstIndex = firstAtOrAbove(referenceCoordinate,shiftedTargetStart);
lastIndex = lastAtOrBelow(referenceCoordinate,shiftedTargetEnd);
if firstIndex <= lastIndex
    count = lastIndex-firstIndex+1;
else
    count = 0;
    firstIndex = 0;
    lastIndex = 0;
end
end

function index = firstAtOrAbove(values,threshold)
lower = 1;
upper = numel(values)+1;
while lower < upper
    middle = floor((lower+upper)/2);
    if middle <= numel(values) && values(middle) < threshold
        lower = middle+1;
    else
        upper = middle;
    end
end
index = lower;
end

function index = lastAtOrBelow(values,threshold)
lower = 0;
upper = numel(values);
while lower < upper
    middle = ceil((lower+upper)/2);
    if values(middle) <= threshold
        lower = middle;
    else
        upper = middle-1;
    end
end
index = lower;
end

function [negative,zero,positive] = directionInterpretations(direction)
zero = 'target_in_phase_with_reference';
if strcmp(direction,'small_is_young')
    negative = 'target_leads_reference';
    positive = 'target_lags_reference';
else
    negative = 'target_lags_reference';
    positive = 'target_leads_reference';
end
end

function interpretation = interpretationForLag( ...
        lag,negative,zero,positive)
if lag < 0
    interpretation = negative;
elseif lag > 0
    interpretation = positive;
else
    interpretation = zero;
end
end
