function [data,info] = cocoPublicationPrepareData(rawData,label)
%COCOPUBLICATIONPREPAREDATA Audited full-record preprocessing for Adaptive COCO.
%
% [DATA,INFO] = COCOPUBLICATIONPREPAREDATA(RAWDATA,LABEL) removes rows
% whose first two columns are nonfinite, sorts by depth, averages duplicate
% proxy values at identical depths, and, only when necessary, linearly
% interpolates onto a grid defined by the median positive depth increment.
% DATA is therefore suitable for CORRCOEFSLICES_RANKNEW.  The complete
% operation is described in INFO.  If interpolation is performed, its
% parameters are printed in English to the Command Window.

if nargin < 2 || strlength(string(label)) == 0
    label = 'Adaptive COCO input';
end
validateattributes(rawData,{'numeric'}, ...
    {'2d','real','nonempty'},mfilename,'rawData',1);
if size(rawData,2) < 2
    error('cocoPublicationPrepareData:InsufficientColumns', ...
        'RAWDATA must contain at least two numeric columns (depth and value).');
end

originalRows = size(rawData,1);
raw = rawData(:,1:2);
finiteMask = all(isfinite(raw),2);
raw = raw(finiteMask,:);
if size(raw,1) < 4
    error('cocoPublicationPrepareData:InsufficientFiniteData', ...
        'At least four finite depth/value observations are required.');
end
raw = sortrows(raw,1);
[uniqueDepth,~,duplicateGroup] = unique(raw(:,1),'sorted');
uniqueValue = accumarray(duplicateGroup,raw(:,2),[],@mean);
clean = [uniqueDepth,uniqueValue];
if size(clean,1) < 4
    error('cocoPublicationPrepareData:InsufficientUniqueDepths', ...
        'At least four unique depths are required after de-duplication.');
end

spacing = diff(clean(:,1));
if any(~isfinite(spacing)) || any(spacing <= 0)
    error('cocoPublicationPrepareData:InvalidDepthSpacing', ...
        'A finite, strictly increasing depth coordinate is required.');
end
medianSpacing = median(spacing);
if ~isfinite(medianSpacing) || medianSpacing <= 0
    error('cocoPublicationPrepareData:InvalidMedianSpacing', ...
        'The median positive depth spacing must be finite and positive.');
end
tolerance = max(64*eps(max(1,max(abs(clean(:,1))))), ...
    1e-8*max(1,abs(medianSpacing)));
maximumDeviation = max(abs(spacing-medianSpacing));
interpolationApplied = maximumDeviation > tolerance;

if interpolationApplied
    exactIntervalCount = (clean(end,1)-clean(1,1))/medianSpacing;
    roundedIntervalCount = round(exactIntervalCount);
    countTolerance = 1e-10*max(1,abs(exactIntervalCount));
    if abs(exactIntervalCount-roundedIntervalCount) <= countTolerance
        intervalCount = roundedIntervalCount;
    else
        intervalCount = floor(exactIntervalCount);
    end
    outputPointCount = intervalCount+1;
    if ~isfinite(outputPointCount) || outputPointCount < 4 || ...
            outputPointCount > 1e6
        error('cocoPublicationPrepareData:InterpolationGridTooLarge', ...
            ['Median-spacing interpolation would create approximately ', ...
             '%.6g points (allowed range 4 to 1,000,000).'],outputPointCount);
    end
    grid = clean(1,1)+(0:intervalCount)'*medianSpacing;
    endpointTolerance = 16*eps(max(1,max(abs(clean([1,end],1))))) * ...
        max(1,numel(grid));
    if abs(grid(end)-clean(end,1)) <= endpointTolerance
        grid(end) = clean(end,1);
    end
    values = interp1(clean(:,1),clean(:,2),grid,'linear');
    valid = isfinite(grid) & isfinite(values);
    data = [grid(valid),values(valid)];
else
    data = clean;
end
if size(data,1) < 4
    error('cocoPublicationPrepareData:InsufficientOutputData', ...
        'Fewer than four finite observations remain after preprocessing.');
end

outputSpacing = median(diff(data(:,1)));
info = struct( ...
    'label',char(string(label)), ...
    'method','sort; mean duplicate values; conditional linear interpolation', ...
    'originalRowCount',originalRows, ...
    'finiteRowCount',size(raw,1), ...
    'nonfiniteRowsRemoved',originalRows-size(raw,1), ...
    'uniqueDepthCount',size(clean,1), ...
    'duplicateRowsCollapsed',size(raw,1)-size(clean,1), ...
    'interpolationApplied',interpolationApplied, ...
    'interpolationMethod','linear', ...
    'originalDepthRange',clean([1,end],1)', ...
    'outputDepthRange',data([1,end],1)', ...
    'spacingMinimum',min(spacing), ...
    'spacingMedian',medianSpacing, ...
    'spacingMaximum',max(spacing), ...
    'outputSpacing',outputSpacing, ...
    'maximumSpacingDeviation',maximumDeviation, ...
    'uniformityTolerance',tolerance, ...
    'maximumGapToMedianRatio',max(spacing)/medianSpacing, ...
    'outputPointCount',size(data,1));

if interpolationApplied
    fprintf('\n>> Adaptive COCO preprocessing: uneven depth spacing detected (%s).\n', ...
        info.label);
    fprintf('   Finite rows before de-duplication : %d\n',info.finiteRowCount);
    fprintf('   Unique depths after de-duplication: %d\n',info.uniqueDepthCount);
    fprintf('   Duplicate rows collapsed          : %d\n',info.duplicateRowsCollapsed);
    fprintf('   Original depth range              : %.12g to %.12g m\n', ...
        info.originalDepthRange);
    fprintf('   Original spacing (min/median/max) : %.12g / %.12g / %.12g m\n', ...
        info.spacingMinimum,info.spacingMedian,info.spacingMaximum);
    fprintf('   Uniformity tolerance              : %.12g m\n', ...
        info.uniformityTolerance);
    fprintf('   Maximum spacing deviation         : %.12g m\n', ...
        info.maximumSpacingDeviation);
    fprintf('   Largest gap / median spacing      : %.12g\n', ...
        info.maximumGapToMedianRatio);
    if info.maximumGapToMedianRatio > 10
        fprintf(['   WARNING: linear interpolation bridges a gap larger than ', ...
            '10 median intervals; the AR(1) null conditions on this ', ...
            'interpolation and does not model missingness.\n']);
    end
    fprintf('   Interpolation method              : %s\n', ...
        info.interpolationMethod);
    fprintf('   Interpolation interval            : %.12g m\n', ...
        info.outputSpacing);
    fprintf('   Interpolated point count          : %d\n', ...
        info.outputPointCount);
    fprintf('   Interpolated depth range          : %.12g to %.12g m\n\n', ...
        info.outputDepthRange);
end
end
