function report = bispectralSelfTest(varargin)
%BISPECTRALSELFTEST Deterministic numerical regression tests for the toolbox.
%   REPORT = BISPECTRALSELFTEST runs estimator identities, preprocessing,
%   a known quadratic phase-coupling positive control, a null control, and
%   both estimator paths. No files are written.

settings = struct('RunSurrogates',true,'Verbose',true);
if nargin == 1 && isstruct(varargin{1})
    supplied = varargin{1};
    names = fieldnames(supplied);
    for ii = 1:numel(names), settings.(names{ii}) = supplied.(names{ii}); end
elseif mod(nargin,2) == 0
    for ii = 1:2:nargin, settings.(varargin{ii}) = varargin{ii+1}; end
end

started = tic;
oldRng = rng;
cleanupRng = onCleanup(@()rng(oldRng));
rng(73019,'twister');

segmentLength = 256;
segmentCount = 24;
n = segmentLength*segmentCount;
t = (0:n-1)';
f1 = 30/segmentLength;
f2 = 17/segmentLength;
phaseOffset = 0.4;
coupled = zeros(n,1);
uncoupled = zeros(n,1);
for segment = 1:segmentCount
    index = (segment-1)*segmentLength+(1:segmentLength);
    phase1 = 2*pi*rand;
    phase2 = 2*pi*rand;
    phase3 = 2*pi*rand;
    base = cos(2*pi*f1*t(index)+phase1)+0.8*cos(2*pi*f2*t(index)+phase2);
    coupled(index) = base+0.7*cos(2*pi*(f1+f2)*t(index)+phase1+phase2+phaseOffset) ...
        +0.12*randn(segmentLength,1);
    uncoupled(index) = base+0.7*cos(2*pi*(f1+f2)*t(index)+phase3) ...
        +0.12*randn(segmentLength,1);
end

options = bispectralDefaults([t coupled]);
require(strcmp(options.SignificanceMethod,'none') && ...
    strcmp(options.SurrogateType,'iaaft') && options.NumSurrogates == 999 && ...
    options.IAAFTIterations == 200 && options.IAAFTSpectralTolerance == 0.02 && ...
    isequal(size(options.PlotFrequencyPairs),[0 2]), ...
    ['API defaults must perform no inference while making IAAFT max-statistic ', ...
     'the sole formal inference configuration when inference is enabled.']);
fractionalFields = {'NumSegments','FrequencySmoothingSpan', ...
    'MaxFrequencyBins','NumSurrogates','IAAFTIterations', ...
    'RandomSeed','PolynomialOrder','NFFT'};
fractionalValues = {8.5,3.5,512.5,999.5,200.5,1.5,2.5,256.5};
for fieldIndex = 1:numel(fractionalFields)
    fractionalOptions = options;
    fractionalOptions.(fractionalFields{fieldIndex}) = ...
        fractionalValues{fieldIndex};
    requireThrows(@()bispectralAnalyze([t coupled],fractionalOptions), ...
        'Acycle:Bispectral:InvalidOption',sprintf( ...
        'The core API silently rounded fractional %s.', ...
        fractionalFields{fieldIndex}));
end
invalidTypedFields = {'OverlapPercent','FrequencyMax','SampleInterval', ...
    'IAAFTSpectralTolerance','IrregularTolerance','GapWarningFactor'};
invalidTypedValues = {'5','1','1',0.02+1i,0.01+1i,5+1i};
invalidTypedIdentifiers = {'Acycle:Bispectral:InvalidOption', ...
    'Acycle:Bispectral:InvalidOption','Acycle:Bispectral:InvalidOption', ...
    'Acycle:Bispectral:InvalidIAAFTSpectralTolerance', ...
    'Acycle:Bispectral:InvalidIrregularTolerance', ...
    'Acycle:Bispectral:InvalidGapWarningFactor'};
for fieldIndex = 1:numel(invalidTypedFields)
    invalidTypedOptions = options;
    invalidTypedOptions.(invalidTypedFields{fieldIndex}) = ...
        invalidTypedValues{fieldIndex};
    requireThrows(@()bispectralAnalyze([t coupled],invalidTypedOptions), ...
        invalidTypedIdentifiers{fieldIndex},sprintf( ...
        'The core API accepted a non-real-numeric %s.', ...
        invalidTypedFields{fieldIndex}));
end
options.NumSegments = segmentCount;
options.OverlapPercent = 0;
options.NFFT = segmentLength;
options.ZeroPaddingFactor = 1;
options.Interpolate = 'never';
options.DetrendMethod = 'none';
options.SegmentDetrendMethod = 'mean';
options.Standardize = false;
options.FrequencyMax = 0.45;
options.SignificanceMethod = 'none';
positive = bispectralAnalyze([t coupled],options);
negative = bispectralAnalyze([t uncoupled],options);
require(~isfield(positive,'Bicoherence'), ...
    'The redundant Bicoherence=sqrt(BicoherenceSquared) result field was not removed.');
require(positive.Meta.ComputedAxisBinCount == numel(positive.Frequency) && ...
    positive.Meta.ComputedAxisFrequencyMinimum == positive.Frequency(1) && ...
    positive.Meta.ComputedAxisFrequencyMaximum == positive.Frequency(end) && ...
    positive.Meta.ComputedFrequencyMaximum == positive.Frequency(end) && ...
    ~isfield(positive.Meta,'DisplayedFrequencyBinCount'), ...
    'Computed-axis frequency metadata is missing or mislabeled as displayed data.');

% FrequencyMin and FrequencyMax are plotting preferences. They must not
% alter frequency bins, triads, estimates, or the inference family held in
% estimator state.
plotLimitedOptions = options;
plotLimitedOptions.FrequencyMin = 0.10;
plotLimitedOptions.FrequencyMax = 0.20;
plotLimited = bispectralAnalyze([t coupled],plotLimitedOptions);
require(isequal(positive.Frequency,plotLimited.Frequency) && ...
    isequal(positive.PrincipalDomainMask,plotLimited.PrincipalDomainMask) && ...
    isequaln(positive.Bispectrum,plotLimited.Bispectrum) && ...
    isequaln(positive.BicoherenceSquared,plotLimited.BicoherenceSquared), ...
    'Plotted frequency limits changed the numerical estimate.');
[~,column] = min(abs(positive.Frequency-f1));
[~,row] = min(abs(positive.Frequency-f2));
positiveB2 = positive.BicoherenceSquared(row,column);
negativeB2 = negative.BicoherenceSquared(row,column);
phaseError = circularDistance(positive.Biphase(row,column),-phaseOffset);
require(positiveB2 > 0.90,'Known coupled triad did not reach b^2 > 0.90.');
require(negativeB2 < 0.35,'Independent triad unexpectedly exceeded b^2 = 0.35.');
require(phaseError < 0.12,'Known biphase was not recovered within 0.12 rad.');

% Independently reconstruct one WOSA triad from the documented formula.
% This deliberately does not call BISPECTRALESTIMATE or reuse its state.
manualWindowIndex = (0:segmentLength-1)';
manualWindow = 0.5-0.5*cos(2*pi*manualWindowIndex/(segmentLength-1));
manualWindow = manualWindow/sqrt(mean(manualWindow.^2));
manualSpectra = complex(zeros(segmentLength,segmentCount));
for segment = 1:segmentCount
    index = (segment-1)*segmentLength+(1:segmentLength);
    manualSegment = coupled(index)-mean(coupled(index));
    manualSpectra(:,segment) = fft(manualSegment.*manualWindow,segmentLength) ...
        /segmentLength;
end
manualK1 = round(f1*segmentLength);
manualK2 = round(f2*segmentLength);
manualK3 = manualK1+manualK2;
manualA = manualSpectra(manualK1+1,:).*manualSpectra(manualK2+1,:);
manualC = manualSpectra(manualK3+1,:);
manualWosaBispectrum = mean(manualA.*conj(manualC));
manualWosaBicoherenceSquared = abs(sum(manualA.*conj(manualC))).^2 / ...
    (sum(abs(manualA).^2)*sum(abs(manualC).^2));
manualWosaBispectrumError = abs( ...
    positive.Bispectrum(row,column)-manualWosaBispectrum);
manualWosaBicoherenceError = abs( ...
    positive.BicoherenceSquared(row,column)-manualWosaBicoherenceSquared);
require(manualWosaBispectrumError < 5e-15, ...
    'WOSA complex bispectrum disagreed with an independent formula reconstruction.');
require(manualWosaBicoherenceError < 5e-15, ...
    'WOSA bicoherence disagreed with an independent formula reconstruction.');

finiteB2 = positive.BicoherenceSquared(isfinite(positive.BicoherenceSquared));
require(all(finiteB2 >= -1e-14 & finiteB2 <= 1+1e-12), ...
    'Bicoherence-squared escaped its [0,1] Cauchy-Schwarz bound.');
require(all(~positive.ValidMask(~isfinite(positive.BicoherenceSquared)) | ...
    isnan(positive.BicoherenceSquared(~isfinite(positive.BicoherenceSquared)))), ...
    'Nonfinite bicoherence cells were not represented as NaN.');

scaled = bispectralAnalyze([t 2*coupled],options);
mask = positive.ValidMask & scaled.ValidMask;
scaleBError = norm(scaled.Bispectrum(mask)-8*positive.Bispectrum(mask)) / ...
    norm(positive.Bispectrum(mask));
scaleB2Error = max(abs(scaled.BicoherenceSquared(mask)-positive.BicoherenceSquared(mask)));
require(scaleBError < 2e-12,'Bispectrum did not scale as amplitude cubed.');
require(scaleB2Error < 2e-12,'Bicoherence changed under positive amplitude scaling.');

reversed = bispectralAnalyze([t flipud(coupled)],options);
mask = positive.ValidMask & reversed.ValidMask;
reverseBError = norm(reversed.Bispectrum(mask)-conj(positive.Bispectrum(mask))) / ...
    norm(positive.Bispectrum(mask));
reverseB2Error = max(abs(reversed.BicoherenceSquared(mask)-positive.BicoherenceSquared(mask)));
require(reverseBError < 2e-11,'Time reversal did not conjugate the complex bispectrum.');
require(reverseB2Error < 2e-11,'Time reversal changed magnitude-squared bicoherence.');

constantOptions = options;
constantOptions.SegmentDetrendMethod = 'none';
constantResult = bispectralAnalyze([t zeros(n,1)],constantOptions);
require(all(isnan(constantResult.BicoherenceSquared(constantResult.PrincipalDomainMask))) && ...
    all(isnan(constantResult.Biphase(constantResult.PrincipalDomainMask))) && ...
    all(constantResult.InvalidDenominatorMask(constantResult.PrincipalDomainMask)) && ...
    constantResult.Meta.InvalidDenominatorTriadCount == nnz(constantResult.PrincipalDomainMask), ...
    'Zero denominator cells must be NaN, not zero or one.');
constantInferenceOptions = constantOptions;
constantInferenceOptions.SignificanceMethod = 'surrogate-global';
constantInferenceOptions.NumSurrogates = 19;
requireThrows(@()bispectralAnalyze([t zeros(n,1)],constantInferenceOptions), ...
    'Acycle:Bispectral:EmptyInferenceFamily', ...
    'Global inference accepted an empty finite observed triad family.');

% Paired sign-reversed segments have positive normalization denominators
% but exactly cancel their third-order products. The resulting zero complex
% bispectrum has no mathematically defined phase.
cancelSegmentLength = 64;
cancelCoordinateSegment = (0:cancelSegmentLength-1)';
cancelBase = cos(2*pi*7*cancelCoordinateSegment/cancelSegmentLength+0.2) ...
    +0.8*cos(2*pi*5*cancelCoordinateSegment/cancelSegmentLength-0.3) ...
    +0.6*cos(2*pi*12*cancelCoordinateSegment/cancelSegmentLength+0.1);
cancelSignal = [cancelBase;-cancelBase;cancelBase;-cancelBase];
cancelCoordinate = (0:numel(cancelSignal)-1)';
cancelOptions = bispectralDefaults([cancelCoordinate cancelSignal]);
cancelOptions.NumSegments = 4;
cancelOptions.OverlapPercent = 0;
cancelOptions.NFFT = cancelSegmentLength;
cancelOptions.Interpolate = 'never';
cancelOptions.DetrendMethod = 'none';
cancelOptions.SegmentDetrendMethod = 'mean';
cancelOptions.Standardize = false;
cancelOptions.FrequencyMax = 0.45;
cancelOptions.SignificanceMethod = 'none';
cancelResult = bispectralAnalyze([cancelCoordinate cancelSignal],cancelOptions);
[~,cancelColumn] = min(abs(cancelResult.Frequency-7/cancelSegmentLength));
[~,cancelRow] = min(abs(cancelResult.Frequency-5/cancelSegmentLength));
require(cancelResult.Denominator(cancelRow,cancelColumn) > 0, ...
    'The zero-bispectrum phase test did not retain a positive denominator.');
require(cancelResult.Bispectrum(cancelRow,cancelColumn) == 0 && ...
    cancelResult.BicoherenceSquared(cancelRow,cancelColumn) == 0, ...
    'Paired sign-reversed segments did not cancel the complex bispectrum exactly.');
require(isnan(cancelResult.Biphase(cancelRow,cancelColumn)), ...
    'A zero complex bispectrum must have NaN biphase.');

% A reusable lower-level state is valid only for the exact scientific
% estimator configuration. Plot and inference fields are deliberately absent
% from this signature because they do not alter FFT triads.
[stateEstimate,reusableState] = bispectralEstimate(cancelSignal,1,cancelOptions);
viewOnlyOptions = cancelOptions;
viewOnlyOptions.FrequencyMin = 0.05;
viewOnlyOptions.FrequencyMax = 0.15;
viewOnlyOptions.SignificanceMethod = 'analytical';
viewOnlyEstimate = bispectralEstimate(cancelSignal,1,viewOnlyOptions,reusableState);
require(isequaln(stateEstimate.Bispectrum,viewOnlyEstimate.Bispectrum) && ...
    isfield(reusableState,'Signature'), ...
    'Display/inference-only options prevented safe estimator-state reuse.');
requireThrows(@()bispectralEstimate(cancelSignal,2,cancelOptions,reusableState), ...
    'Acycle:Bispectral:StateSignatureMismatch', ...
    'Estimator state reuse accepted a different sample interval.');
changedStateOptions = cancelOptions;
changedStateOptions.Window = 'hamming';
requireThrows(@()bispectralEstimate(cancelSignal,1,changedStateOptions,reusableState), ...
    'Acycle:Bispectral:StateSignatureMismatch', ...
    'Estimator state reuse accepted a different taper.');
changedStateOptions = cancelOptions;
changedStateOptions.NFFT = 128;
requireThrows(@()bispectralEstimate(cancelSignal,1,changedStateOptions,reusableState), ...
    'Acycle:Bispectral:StateSignatureMismatch', ...
    'Estimator state reuse accepted a different NFFT.');
changedStateOptions = cancelOptions;
changedStateOptions.MaxFrequencyBins = 16;
requireThrows(@()bispectralEstimate(cancelSignal,1,changedStateOptions,reusableState), ...
    'Acycle:Bispectral:StateSignatureMismatch', ...
    'Estimator state reuse accepted a different computed-bin limit.');

lowerEstimatorFields = {'NumSegments','FrequencySmoothingSpan', ...
    'MaxFrequencyBins','NFFT'};
lowerEstimatorValues = {4.5,3.5,32.5,64.5};
lowerEstimatorIdentifiers = {'Acycle:Bispectral:InvalidSegments', ...
    'Acycle:Bispectral:InvalidSmoothingSpan', ...
    'Acycle:Bispectral:InvalidMaxFrequencyBins', ...
    'Acycle:Bispectral:InvalidNFFT'};
for fieldIndex = 1:numel(lowerEstimatorFields)
    fractionalEstimateOptions = cancelOptions;
    fractionalEstimateOptions.(lowerEstimatorFields{fieldIndex}) = ...
        lowerEstimatorValues{fieldIndex};
    requireThrows(@()bispectralEstimate( ...
        cancelSignal,1,fractionalEstimateOptions), ...
        lowerEstimatorIdentifiers{fieldIndex},sprintf( ...
        'The lower-level estimator silently rounded fractional %s.', ...
        lowerEstimatorFields{fieldIndex}));
end

oddNfftOptions = cancelOptions;
oddNfftOptions.NFFT = 65;
oddNfftOptions.MaxFrequencyBins = 16;
oddNfftResult = bispectralAnalyze([cancelCoordinate cancelSignal],oddNfftOptions);
oddComputedMaximum = oddNfftResult.Meta.ComputedAxisFrequencyMaximum;
require(isfinite(oddComputedMaximum) && oddComputedMaximum > 0 && ...
    oddComputedMaximum == ...
    oddNfftResult.Frequency(end) && ...
    oddNfftResult.Meta.NativePositiveFrequencyMaximum > ...
    oddComputedMaximum && ...
    oddNfftResult.Meta.PrincipalSumFrequencyMaximum <= ...
    oddNfftResult.Meta.NativePositiveFrequencyMaximum, ...
    'Stride-aware computed-axis and native-positive maxima are not distinguished.');
insufficientInference = cancelOptions;
insufficientInference.SignificanceMethod = 'surrogate-global';
insufficientInference.ConfidenceLevel = 0.99;
insufficientInference.NumSurrogates = 19;
requireThrows(@()bispectralSignificance(cancelSignal,1,insufficientInference, ...
    stateEstimate,reusableState), ...
    'Acycle:Bispectral:InsufficientSurrogatesForConfidence', ...
    'An inference configuration whose minimum plus-one p exceeds alpha was accepted.');
fractionalInference = cancelOptions;
fractionalInference.SignificanceMethod = 'surrogate-global';
fractionalInference.NumSurrogates = 19.5;
requireThrows(@()bispectralSignificance(cancelSignal,1,fractionalInference, ...
    stateEstimate,reusableState), ...
    'Acycle:Bispectral:InvalidSurrogateCount', ...
    'The lower-level inference API silently rounded fractional NumSurrogates.');
fractionalInference.NumSurrogates = 19;
fractionalInference.IAAFTIterations = 200.5;
requireThrows(@()bispectralSignificance(cancelSignal,1,fractionalInference, ...
    stateEstimate,reusableState), ...
    'Acycle:Bispectral:InvalidIAAFTIterations', ...
    'The lower-level inference API silently rounded fractional IAAFTIterations.');
fractionalInference.IAAFTIterations = 200;
fractionalInference.MaxSurrogateAttempts = 19.5;
requireThrows(@()bispectralSignificance(cancelSignal,1,fractionalInference, ...
    stateEstimate,reusableState), ...
    'Acycle:Bispectral:InvalidMaxSurrogateAttempts', ...
    'The lower-level inference API silently rounded fractional MaxSurrogateAttempts.');
fractionalInference.MaxSurrogateAttempts = 19;
fractionalInference.RandomSeed = 1.5;
requireThrows(@()bispectralSignificance(cancelSignal,1,fractionalInference, ...
    stateEstimate,reusableState), ...
    'Acycle:Bispectral:InvalidRandomSeed', ...
    'The lower-level inference API silently rounded fractional RandomSeed.');
analyticalCompatibility = cancelOptions;
analyticalCompatibility.SignificanceMethod = 'analytical';
analyticalSignificance = bispectralSignificance(cancelSignal,1, ...
    analyticalCompatibility,stateEstimate,reusableState);
require(any(contains(string(analyticalSignificance.Warnings), ...
    'compatibility','IgnoreCase',true)), ...
    'Analytical Beta inference was not labeled as compatibility-only.');

xIrregular = (0:0.1:30)';
xIrregular(50) = xIrregular(49);
xIrregular(180:end) = xIrregular(180:end)+0.035;
yIrregular = sin(2*pi*0.08*xIrregular);
irregularOptions = bispectralDefaults([xIrregular yIrregular]);
irregularOptions.SignificanceMethod = 'none';
[regularized,preMeta] = bispectralPreprocess([xIrregular yIrregular],irregularOptions);
regularSpacing = diff(regularized(:,1));
require(preMeta.DuplicateRowsCombined == 1,'Duplicate coordinate was not combined.');
require(preMeta.WasInterpolated,'Uneven sampling was not automatically regularized.');
require(max(abs(regularSpacing-median(regularSpacing))) < 1e-10, ...
    'The interpolated coordinate grid is not regular.');

% Strict input policy is the GUI-safe path: it validates a prepared series
% without deleting, sorting, averaging, or interpolating any observation.
strictCoordinate = (0:127)'.*0.1;
strictSignal = sin(2*pi*0.17*strictCoordinate)+0.2*cos(2*pi*0.31*strictCoordinate);
strictData = [strictCoordinate strictSignal];
strictOptions = bispectralDefaults(strictData);
strictOptions.InputPolicy = 'strict';
strictOptions.Interpolate = 'never';
strictOptions.DetrendMethod = 'none';
strictOptions.Standardize = false;
[strictProcessed,strictMeta] = bispectralPreprocess(strictData,strictOptions);
require(isequal(strictProcessed,strictData) && ...
    strictMeta.RemovedNonfiniteRows == 0 && ...
    strictMeta.DuplicateRowsCombined == 0 && ...
    ~strictMeta.WasInterpolated, ...
    'Strict input policy changed an already prepared regular series.');
strictNonfinite = strictData;
strictNonfinite(20,2) = NaN;
requireThrows(@()bispectralPreprocess(strictNonfinite,strictOptions), ...
    'Acycle:Bispectral:StrictNonfiniteData', ...
    'Strict input policy silently removed a nonfinite row.');
strictUnsorted = strictData;
strictUnsorted([20 21],:) = strictUnsorted([21 20],:);
requireThrows(@()bispectralPreprocess(strictUnsorted,strictOptions), ...
    'Acycle:Bispectral:StrictUnsortedCoordinates', ...
    'Strict input policy silently sorted input coordinates.');
strictDuplicate = [strictData;strictData(end,:)];
requireThrows(@()bispectralPreprocess(strictDuplicate,strictOptions), ...
    'Acycle:Bispectral:StrictDuplicateCoordinates', ...
    'Strict input policy silently combined duplicate coordinates.');
strictUneven = strictData;
strictUneven(64,1) = strictUneven(64,1)+2e-6;
requireThrows(@()bispectralPreprocess(strictUneven,strictOptions), ...
    'Acycle:Bispectral:StrictUnevenSampling', ...
    'Strict input policy accepted spacing departures larger than 10 ppm.');

% Nine-significant-digit text output can add about one ppm of coordinate
% jitter when a regular grid crosses a decimal-magnitude boundary. Strict
% analysis accepts that serialization artifact without changing the data.
quantizedCoordinate = 289.816514+(0:518)'.*3.9;
quantizedCoordinate = arrayfun( ...
    @(value)str2double(sprintf('%.9g',value)),quantizedCoordinate);
quantizedSignal = sin(2*pi*quantizedCoordinate/97);
quantizedData = [quantizedCoordinate quantizedSignal];
quantizedOptions = bispectralDefaults(quantizedData);
quantizedOptions.InputPolicy = 'strict';
quantizedOptions.Interpolate = 'never';
quantizedOptions.DetrendMethod = 'none';
quantizedOptions.Standardize = false;
[quantizedProcessed,quantizedMeta] = bispectralPreprocess( ...
    quantizedData,quantizedOptions);
require(isequal(quantizedProcessed,quantizedData) && ...
    ~quantizedMeta.WasInterpolated && ...
    quantizedMeta.AcceptedNearUniformSpacing && ...
    quantizedMeta.RelativeSpacingDeparture < ...
        quantizedMeta.StrictSpacingRelativeTolerance, ...
    ['Strict input policy did not preserve a regular grid containing only ', ...
     'nine-significant-digit serialization jitter.']);
fractionalPolynomialOptions = strictOptions;
fractionalPolynomialOptions.DetrendMethod = 'polynomial';
fractionalPolynomialOptions.PolynomialOrder = 2.5;
requireThrows(@()bispectralPreprocess(strictData,fractionalPolynomialOptions), ...
    'Acycle:Bispectral:InvalidPolynomialOrder', ...
    'The lower-level preprocessor silently rounded fractional PolynomialOrder.');

% All algorithms and null generators rely on Hermitian symmetry of a real
% series. Complex coordinates or values must fail before estimation.
complexData = strictData;
complexData(:,2) = complexData(:,2)+1i*0.01*cos(strictCoordinate);
requireThrows(@()bispectralAnalyze(complexData), ...
    'Acycle:Bispectral:ComplexData', ...
    'The core API accepted a complex-valued signal.');
requireThrows(@()bispectralEstimate(complexData(:,2),0.1,strictOptions), ...
    'Acycle:Bispectral:ComplexData', ...
    'The lower-level estimator accepted a complex-valued signal.');
requireThrows(@()bispectralSurrogate(complexData(:,2),'phase',1), ...
    'Acycle:Bispectral:ComplexData', ...
    'The surrogate generator accepted a complex-valued signal.');
requireThrows(@()bispectralEstimate('abc',0.1,strictOptions), ...
    'Acycle:Bispectral:InvalidEstimatorData', ...
    'The lower-level estimator converted character input to ASCII data.');
requireThrows(@()bispectralEstimate(reshape(strictSignal,16,8),0.1,strictOptions), ...
    'Acycle:Bispectral:InvalidEstimatorData', ...
    'The lower-level estimator silently flattened a signal matrix.');
requireThrows(@()bispectralEstimate(strictSignal,'1',strictOptions), ...
    'Acycle:Bispectral:InvalidSampleInterval', ...
    'The lower-level estimator converted a character dt to ASCII.');
invalidLowerOptions = strictOptions;
invalidLowerOptions.OverlapPercent = '5';
requireThrows(@()bispectralEstimate(strictSignal,0.1,invalidLowerOptions), ...
    'Acycle:Bispectral:InvalidOverlap', ...
    'The lower-level estimator converted character overlap to ASCII.');
invalidLowerOptions = strictOptions;
invalidLowerOptions.ZeroPaddingFactor = 'a';
requireThrows(@()bispectralEstimate(strictSignal,0.1,invalidLowerOptions), ...
    'Acycle:Bispectral:InvalidZeroPaddingFactor', ...
    'The lower-level estimator converted character zero padding to ASCII.');
requireThrows(@()bispectralSurrogate('abc','phase',1), ...
    'Acycle:Bispectral:InvalidSurrogateData', ...
    'The surrogate generator converted character input to ASCII data.');
requireThrows(@()bispectralSurrogate(reshape(strictSignal,16,8),'phase',1), ...
    'Acycle:Bispectral:InvalidSurrogateData', ...
    'The surrogate generator silently flattened a signal matrix.');

% Interpolation is not an anti-aliasing filter, so the preprocessing API
% must reject a user interval coarser than the original median spacing.
coarseCoordinate = (0:127)';
coarseSignal = sin(2*pi*0.12*coarseCoordinate);
coarseOptions = bispectralDefaults([coarseCoordinate coarseSignal]);
coarseOptions.SampleInterval = 2;
coarseRejected = false;
try
    bispectralPreprocess([coarseCoordinate coarseSignal],coarseOptions);
catch exception
    coarseRejected = strcmp(exception.identifier,'Acycle:Bispectral:AliasingRisk');
end
require(coarseRejected, ...
    'A coarser user SampleInterval was not rejected as an aliasing risk.');

% Records too short for three 32-point WOSA segments must automatically
% use the native-grid frequency-smoothed estimator.
shortN = 47;
shortCoordinate = (0:shortN-1)';
shortSignal = sin(2*pi*5*shortCoordinate/shortN) ...
    +0.3*cos(2*pi*9*shortCoordinate/shortN);
shortOptions = bispectralDefaults([shortCoordinate shortSignal]);
shortOptions.SignificanceMethod = 'none';
shortResult = bispectralAnalyze([shortCoordinate shortSignal],shortOptions);
require(strcmp(shortResult.Meta.Estimator,'frequency-smoothed'), ...
    'A 47-point record did not automatically select frequency smoothing.');
require(shortResult.Meta.NFFT == shortN && any(shortResult.ValidMask(:)), ...
    'The short-record frequency-smoothed estimate was empty or padded.');
shortTable = table(shortCoordinate,shortSignal, ...
    'VariableNames',{'Coordinate','Signal'});
shortTableOptions = bispectralDefaults(shortTable);
require(strcmp(shortTableOptions.Estimator,'frequency-smoothed') && ...
    shortTableOptions.NumSegments == shortOptions.NumSegments, ...
    'Table and numeric short records did not receive identical data-dependent defaults.');
shortTableResult = bispectralAnalyze(shortTable,shortTableOptions);
require(isequal(shortTableResult.Frequency,shortResult.Frequency) && ...
    isequaln(shortTableResult.BicoherenceSquared,shortResult.BicoherenceSquared), ...
    'Table and numeric short records did not produce identical estimates.');

% IAAFT must preserve the exact observed marginal distribution while
% approaching the target Fourier amplitudes to a useful tolerance.
rngBeforeIaaftInput = rng;
rng(44021,'twister');
iaaftDriver = filter(1,[1 -0.75],randn(512,1));
rng(rngBeforeIaaftInput);
iaaftDriver = (iaaftDriver-mean(iaaftDriver))/std(iaaftDriver,0);
iaaftInput = exp(0.35*iaaftDriver);
rngBeforeIaaft = rng;
rng(92831,'twister');
[iaaftSurrogate,iaaftMeta] = bispectralSurrogate( ...
    iaaftInput,'iaaft',options.IAAFTIterations);
rng(rngBeforeIaaft);
iaaftMarginalError = max(abs(sort(iaaftSurrogate)-sort(iaaftInput)));
require(iaaftMarginalError == 0, ...
    'IAAFT did not preserve the observed marginal distribution exactly.');
require(isfinite(iaaftMeta.RelativeSpectralError) && ...
    iaaftMeta.RelativeSpectralError <= options.IAAFTSpectralTolerance, ...
    'IAAFT did not satisfy the formal default non-DC spectral tolerance.');
require(contains(iaaftMeta.SpectralErrorDomain,'excluding DC'), ...
    'IAAFT quality metadata did not state that DC is excluded.');
requireThrows(@()bispectralSurrogate(iaaftInput,'iaaft',200.5), ...
    'Acycle:Bispectral:InvalidIAAFTIterations', ...
    'The standalone surrogate API silently rounded fractional IAAFTIterations.');
rngBeforeDefaultSurrogate = rng;
rng(31027,'twister');
[~,defaultSurrogateMeta] = bispectralSurrogate(iaaftInput(1:128));
rng(rngBeforeDefaultSurrogate);
require(strcmp(defaultSurrogateMeta.Type,'iaaft'), ...
    'The standalone surrogate API still defaulted to FT phase randomization.');

% A large constant offset changes only DC and must not make a poor non-DC
% IAAFT match look artificially accurate. Identical RNG streams should yield
% essentially the same positive-frequency error with or without the offset.
rngBeforeOffset = rng;
rng(11903,'twister');
[~,offsetFreeMeta] = bispectralSurrogate(iaaftInput,'iaaft',20);
rng(11903,'twister');
[~,largeOffsetMeta] = bispectralSurrogate(iaaftInput+1e6,'iaaft',20);
rng(rngBeforeOffset);
offsetErrorDifference = abs(offsetFreeMeta.RelativeSpectralError- ...
    largeOffsetMeta.RelativeSpectralError);
require(offsetErrorDifference <= 1e-6*max(1,offsetFreeMeta.RelativeSpectralError) && ...
    largeOffsetMeta.RelativeSpectralError > 1e-6, ...
    'IAAFT spectral quality was diluted by an irrelevant large DC offset.');

% FT phase randomization must preserve every Fourier amplitude (including
% DC and the even-length Nyquist coefficient) to roundoff for real inputs.
rngBeforePhase = rng;
rng(60421,'twister');
[phaseEven,phaseEvenMeta] = bispectralSurrogate(iaaftInput,'phase',1);
[phaseOdd,phaseOddMeta] = bispectralSurrogate(iaaftInput(1:end-1),'phase',1);
rng(rngBeforePhase);
phaseEvenError = norm(abs(fft(phaseEven))-abs(fft(iaaftInput))) / ...
    norm(abs(fft(iaaftInput)));
phaseOddError = norm(abs(fft(phaseOdd))-abs(fft(iaaftInput(1:end-1)))) / ...
    norm(abs(fft(iaaftInput(1:end-1))));
require(max([phaseEvenError,phaseOddError, ...
    phaseEvenMeta.RelativeSpectralError,phaseOddMeta.RelativeSpectralError]) < 5e-14, ...
    'FT phase randomization did not preserve the periodogram to roundoff.');

smoothOptions = options;
smoothOptions.Estimator = 'frequency-smoothed';
smoothOptions.NFFT = 4*n; % must be ignored on this estimator's native grid
smoothOptions.FrequencySmoothingSpan = 3;
smoothOptions.MaxFrequencyBins = 128;
smoothPositive = bispectralAnalyze([t coupled],smoothOptions);
smoothReverse = bispectralAnalyze([t flipud(coupled)],smoothOptions);
smoothMask = smoothPositive.ValidMask & smoothReverse.ValidMask;
smoothReverseBError = norm(smoothReverse.Bispectrum(smoothMask)- ...
    conj(smoothPositive.Bispectrum(smoothMask))) / norm(smoothPositive.Bispectrum(smoothMask));
smoothReverseB2Error = max(abs(smoothReverse.BicoherenceSquared(smoothMask)- ...
    smoothPositive.BicoherenceSquared(smoothMask)));
require(smoothPositive.Meta.NFFT == n, ...
    'Frequency-smoothed estimation incorrectly treated zero padding as new bins.');
require(size(smoothPositive.Meta.SmoothingOffsets,1) == 7, ...
    'The span-3 hexagonal kernel must contain seven triads.');
require(smoothReverseBError < 2e-11 && smoothReverseB2Error < 2e-11, ...
    'Frequency-smoothed time-reversal identities failed.');

% Independently reconstruct one frequency-smoothed triad using all seven
% offsets in |a|<=1, |b|<=1, |a+b|<=1 and uniform Daniell weights.
[~,smoothColumn] = min(abs(smoothPositive.Frequency-f1));
[~,smoothRow] = min(abs(smoothPositive.Frequency-f2));
require(smoothPositive.ValidMask(smoothRow,smoothColumn), ...
    'The selected manual frequency-smoothed triad is outside the principal domain.');
smoothWindowIndex = (0:n-1)';
smoothWindow = 0.5-0.5*cos(2*pi*smoothWindowIndex/(n-1));
smoothWindow = smoothWindow/sqrt(mean(smoothWindow.^2));
smoothSpectrum = fft((coupled-mean(coupled)).*smoothWindow,n)/n;
smoothK1 = round(smoothPositive.Frequency(smoothColumn)*n);
smoothK2 = round(smoothPositive.Frequency(smoothRow)*n);
[offsetA,offsetB] = meshgrid(-1:1,-1:1);
keepOffset = abs(offsetA+offsetB) <= 1;
offsets = [offsetA(keepOffset),offsetB(keepOffset)];
smoothA = complex(zeros(size(offsets,1),1));
smoothC = complex(zeros(size(offsets,1),1));
for offsetIndex = 1:size(offsets,1)
    k1 = smoothK1+offsets(offsetIndex,1);
    k2 = smoothK2+offsets(offsetIndex,2);
    smoothA(offsetIndex) = smoothSpectrum(k1+1)*smoothSpectrum(k2+1);
    smoothC(offsetIndex) = smoothSpectrum(k1+k2+1);
end
manualSmoothBispectrum = mean(smoothA.*conj(smoothC));
manualSmoothBicoherenceSquared = abs(mean(smoothA.*conj(smoothC))).^2 / ...
    (mean(abs(smoothA).^2)*mean(abs(smoothC).^2));
manualSmoothBispectrumError = abs( ...
    smoothPositive.Bispectrum(smoothRow,smoothColumn)-manualSmoothBispectrum);
manualSmoothBicoherenceError = abs( ...
    smoothPositive.BicoherenceSquared(smoothRow,smoothColumn) ...
    -manualSmoothBicoherenceSquared);
require(manualSmoothBispectrumError < 5e-15, ...
    ['Frequency-smoothed complex bispectrum disagreed with an independent ', ...
     'seven-triad reconstruction.']);
require(manualSmoothBicoherenceError < 5e-14, ...
    ['Frequency-smoothed bicoherence disagreed with an independent ', ...
     'seven-triad reconstruction.']);

surrogateDetected = NaN;
surrogateThreshold = NaN;
finiteSampleCriticalRankChecked = false;
finiteSampleThresholdTieRejected = false;
iaaftQualityAttemptCount = NaN;
iaaftQualityFailureRejected = NaN;
if settings.RunSurrogates
    formalSegmentLength = 64;
    formalSegmentCount = 8;
    formalN = formalSegmentLength*formalSegmentCount;
    formalCoordinate = (0:formalN-1)';
    formalSignal = zeros(formalN,1);
    formalF1 = 9/formalSegmentLength;
    formalF2 = 5/formalSegmentLength;
    rngBeforeFormalSignal = rng;
    rng(771,'twister');
    for segment = 1:formalSegmentCount
        index = (segment-1)*formalSegmentLength+(1:formalSegmentLength);
        phase1 = 2*pi*rand;
        phase2 = 2*pi*rand;
        formalSignal(index) = cos(2*pi*formalF1*formalCoordinate(index)+phase1) ...
            +0.8*cos(2*pi*formalF2*formalCoordinate(index)+phase2) ...
            +0.7*cos(2*pi*(formalF1+formalF2)*formalCoordinate(index) ...
            +phase1+phase2+0.3)+0.08*randn(formalSegmentLength,1);
    end
    rng(rngBeforeFormalSignal);
    inferenceOptions = bispectralDefaults([formalCoordinate formalSignal]);
    inferenceOptions.NumSegments = formalSegmentCount;
    inferenceOptions.OverlapPercent = 0;
    inferenceOptions.NFFT = formalSegmentLength;
    inferenceOptions.MaxFrequencyBins = 32;
    inferenceOptions.Interpolate = 'never';
    inferenceOptions.DetrendMethod = 'none';
    inferenceOptions.Standardize = false;
    inferenceOptions.SignificanceMethod = 'surrogate-global';
    inferenceOptions.NumSurrogates = 39;
    inferenceOptions.MaxSurrogateAttempts = 60;
    inferenceOptions.RandomSeed = 991;
    inferred = bispectralAnalyze([formalCoordinate formalSignal],inferenceOptions);
    [~,column] = min(abs(inferred.Frequency-formalF1));
    [~,row] = min(abs(inferred.Frequency-formalF2));
    surrogateDetected = inferred.SignificantMask(row,column);
    surrogateThreshold = inferred.Significance.Threshold;
    require(surrogateDetected, ...
        'The known coupled triad did not exceed the formal IAAFT global threshold.');
    require(strcmp(inferred.Significance.SurrogateType,'iaaft') && ...
        ~any(contains(string(inferred.Significance.Warnings), ...
        'compatibility','IgnoreCase',true)), ...
        'Formal IAAFT inference was mislabeled as a compatibility path.');
    require(inferred.Significance.InferenceFamilyTriadCount == ...
        nnz(inferred.ValidMask) && contains( ...
        inferred.Significance.InferenceFamilyDefinition,'Fixed finite'), ...
        'Formal inference did not record its fixed finite computed family.');
    require(all(inferred.Significance.PValue(inferred.ValidMask) >= ...
        1/(inferenceOptions.NumSurrogates+1)-eps), ...
        'Surrogate p-values did not use the finite-sample plus-one correction.');
    require(all(inferred.Significance.SurrogateSpectralErrors <= ...
        inferenceOptions.IAAFTSpectralTolerance), ...
        'Formal IAAFT inference admitted a surrogate above its quality tolerance.');

    % At 95% with M=20, the plus-one p-value can be <=0.05 only when the
    % observation strictly exceeds every surrogate maximum.  This is the
    % boundary count that distinguishes the exact finite-sample critical
    % rank from the ordinary empirical 95th percentile.
    boundaryOptions = inferenceOptions;
    boundaryOptions.NumSurrogates = 20;
    boundaryOptions.SurrogateType = 'phase';
    boundaryOptions.MaxSurrogateAttempts = 20;
    boundaryOptions.RandomSeed = 992;
    boundaryResult = bispectralAnalyze( ...
        [formalCoordinate formalSignal],boundaryOptions);
    boundaryMaximum = max(boundaryResult.Significance.SurrogateMaxima);
    finiteSampleCriticalRankChecked = ...
        boundaryResult.Significance.Threshold == boundaryMaximum && ...
        contains(boundaryResult.Significance.ThresholdComparison, ...
        'strictly greater','IgnoreCase',true);
    require(finiteSampleCriticalRankChecked, ...
        ['The stored M=20 maximum-statistic threshold did not use the exact ', ...
         'plus-one Monte Carlo critical rank.']);
    [tieObserved,tieState] = bispectralEstimate( ...
        formalSignal,1,boundaryOptions);
    tiePair = find(isfinite(tieObserved.PairBicoherenceSquared),1,'first');
    tieObserved.PairBicoherenceSquared(tiePair) = boundaryMaximum;
    tieSignificance = bispectralSignificance( ...
        formalSignal,1,boundaryOptions,tieObserved,tieState);
    tieLinearIndex = tieObserved.PairLinearIndex(tiePair);
    finiteSampleThresholdTieRejected = ...
        ~tieSignificance.SignificantMask(tieLinearIndex) && ...
        tieSignificance.PValue(tieLinearIndex) > ...
        1-boundaryOptions.ConfidenceLevel;
    require(finiteSampleThresholdTieRejected, ...
        'An observation tied with the plus-one critical maximum was rejected.');

    qualityN = 256;
    qualityCoordinate = (0:qualityN-1)';
    rngBeforeQualitySignal = rng;
    rng(5521,'twister');
    qualitySignal = sin(2*pi*qualityCoordinate/31) ...
        +0.25*randn(qualityN,1);
    rng(rngBeforeQualitySignal);
    qualityOptions = bispectralDefaults([qualityCoordinate qualitySignal]);
    qualityOptions.NumSegments = 4;
    qualityOptions.OverlapPercent = 0;
    qualityOptions.NFFT = 64;
    qualityOptions.MaxFrequencyBins = 32;
    qualityOptions.Interpolate = 'never';
    qualityOptions.DetrendMethod = 'none';
    qualityOptions.Standardize = false;
    qualityOptions.SignificanceMethod = 'surrogate-global';
    qualityOptions.ConfidenceLevel = 0.95;
    qualityOptions.NumSurrogates = 19;
    qualityOptions.SurrogateType = 'iaaft';
    qualityOptions.IAAFTIterations = 200;
    qualityOptions.IAAFTSpectralTolerance = 0.015;
    qualityOptions.MaxSurrogateAttempts = 29;
    qualityOptions.RandomSeed = 7611;
    qualityResult = bispectralAnalyze( ...
        [qualityCoordinate qualitySignal],qualityOptions);
    iaaftQualityAttemptCount = qualityResult.Significance.SurrogateAttemptCount;
    require(qualityResult.Significance.SurrogateAttemptCount > 19 && ...
        qualityResult.Significance.SurrogateAttemptCount <= 29 && ...
        qualityResult.Significance.RejectedIAAFTQualityCount > 0 && ...
        numel(qualityResult.Significance.SurrogateSpectralErrors) == 19 && ...
        all(isfinite(qualityResult.Significance.SurrogateSpectralErrors)) && ...
        all(qualityResult.Significance.SurrogateSpectralErrors <= 0.015) && ...
        any(contains(string(qualityResult.Significance.Warnings), ...
        'Rejected and replaced','IgnoreCase',true)), ...
        'IAAFT quality replacement or its metadata/warning was not retained.');
    pointwiseCompatibilityOptions = qualityOptions;
    pointwiseCompatibilityOptions.SignificanceMethod = 'surrogate-pointwise';
    pointwiseCompatibilityOptions.SurrogateType = 'phase';
    pointwiseCompatibilityResult = bispectralAnalyze( ...
        [qualityCoordinate qualitySignal],pointwiseCompatibilityOptions);
    require(any(contains(string(pointwiseCompatibilityResult.Significance.Warnings), ...
        'compatibility','IgnoreCase',true)) && ...
        any(isfinite(pointwiseCompatibilityResult.Significance.ThresholdMatrix(:))), ...
        'Pointwise surrogate API compatibility regression failed or lacked its warning.');
    rejectedQualityOptions = qualityOptions;
    rejectedQualityOptions.IAAFTSpectralTolerance = eps;
    rejectedQualityOptions.MaxSurrogateAttempts = 20;
    requireThrows(@()bispectralAnalyze( ...
        [qualityCoordinate qualitySignal],rejectedQualityOptions), ...
        'Acycle:Bispectral:IAAFTQualityFailure', ...
        'Poor-spectrum IAAFT null surrogates were not rejected after finite replacements.');
    iaaftQualityFailureRejected = true;
end

report = struct( ...
    'Passed',true, ...
    'ElapsedSeconds',toc(started), ...
    'CoupledTriadBicoherenceSquared',positiveB2, ...
    'UncoupledTriadBicoherenceSquared',negativeB2, ...
    'BiphaseErrorRadians',phaseError, ...
    'ManualWosaBispectrumAbsoluteError',manualWosaBispectrumError, ...
    'ManualWosaBicoherenceAbsoluteError',manualWosaBicoherenceError, ...
    'PlotFrequencyLimitIndependentOfEstimate',true, ...
    'StrictInputPolicyPreservedPreparedData',true, ...
    'ComplexInputsRejected',true, ...
    'FractionalScientificParametersRejected',true, ...
    'NonNumericAndMatrixLowerInputsRejected',true, ...
    'ShortTableDefaultsMatchNumeric',true, ...
    'EstimatorStateScientificSignatureChecked',true, ...
    'ComputedAxisMetadataChecked',true, ...
    'RedundantBicoherenceFieldRemoved',true, ...
    'FormalInferenceDefaultsUseIAAFT',true, ...
    'FiniteSampleCriticalRankChecked',finiteSampleCriticalRankChecked, ...
    'FiniteSampleThresholdTieRejected',finiteSampleThresholdTieRejected, ...
    'FTSurrogatePeriodogramMaximumRelativeError',max(phaseEvenError,phaseOddError), ...
    'AmplitudeScaleBispectrumRelativeError',scaleBError, ...
    'AmplitudeScaleBicoherenceMaximumError',scaleB2Error, ...
    'TimeReverseBispectrumRelativeError',reverseBError, ...
    'TimeReverseBicoherenceMaximumError',reverseB2Error, ...
    'ZeroBispectrumBiphaseIsNaN',isnan(cancelResult.Biphase(cancelRow,cancelColumn)), ...
    'CoarseSampleIntervalRejected',coarseRejected, ...
    'ShortRecordEstimator',shortResult.Meta.Estimator, ...
    'IAAFTMarginalMaximumError',iaaftMarginalError, ...
    'IAAFTRelativeSpectralError',iaaftMeta.RelativeSpectralError, ...
    'IAAFTLargeOffsetSpectralErrorDifference',offsetErrorDifference, ...
    'FrequencySmoothedReverseBispectrumRelativeError',smoothReverseBError, ...
    'FrequencySmoothedReverseBicoherenceMaximumError',smoothReverseB2Error, ...
    'ManualFrequencySmoothedBispectrumAbsoluteError',manualSmoothBispectrumError, ...
    'ManualFrequencySmoothedBicoherenceAbsoluteError',manualSmoothBicoherenceError, ...
    'GlobalIAAFTDetectedKnownTriad',surrogateDetected, ...
    'GlobalIAAFTThreshold',surrogateThreshold, ...
    'GlobalSurrogateDetectedKnownTriad',surrogateDetected, ...
    'GlobalSurrogateThreshold',surrogateThreshold, ...
    'IAAFTQualityAttemptCount',iaaftQualityAttemptCount, ...
    'IAAFTQualityFailureRejected',iaaftQualityFailureRejected);
if settings.Verbose
    fprintf(['Bispectral self-test passed in %.2f s. Coupled b^2=%.4f; ', ...
        'uncoupled b^2=%.4f; biphase error=%.4g rad.\n'], ...
        report.ElapsedSeconds,positiveB2,negativeB2,phaseError);
end
end

function distance = circularDistance(a,b)
distance = abs(angle(exp(1i*(a-b))));
end

function require(condition,message)
if ~condition
    error('Acycle:Bispectral:SelfTestFailure','%s',message);
end
end

function requireThrows(action,expectedIdentifier,message)
didThrowExpected = false;
try
    action();
catch exception
    didThrowExpected = strcmp(exception.identifier,expectedIdentifier);
end
if ~didThrowExpected
    error('Acycle:Bispectral:SelfTestFailure','%s',message);
end
end
