function validation = bispectralLocalDataValidation(outputParent,varargin)
%BISPECTRALLOCALDATAVALIDATION Reproducible LR04/CENOGRID study.
%   VALIDATION = BISPECTRALLOCALDATAVALIDATION(OUTPUTPARENT) analyzes
%   the local LR04 stack and three five-million-year CENOGRID intervals.
%   Each record is evaluated both before and after an explicitly documented
%   800 kyr LOWESS trend removal. Every selected record is explicitly rebuilt
%   on its interval-specific median-spacing grid before strict FFT analysis.
%   The bundled files in data/Examples are used by default. LR04File,
%   CenogridFile, LOWESSWindowKyr, PlotFrequencyMaximum, MaxFrequencyBins,
%   NumSurrogates, IAAFTIterations, IAAFTSpectralTolerance, and RandomSeed
%   can be overridden with name/value pairs. The formal defaults use 999
%   accepted IAAFT surrogates and at most 1024 computed frequency-axis bins.

toolboxDirectory = fileparts(mfilename('fullpath'));
repositoryRoot = fileparts(fileparts(fileparts(toolboxDirectory)));
settings = struct( ...
    'LR04File',fullfile(repositoryRoot,'data','Examples','LR04stack5320ka.txt'), ...
    'CenogridFile',fullfile(repositoryRoot,'data','Examples', ...
        'Example-cenogrid-d18o.txt'), ...
    'LOWESSWindowKyr',800, ...
    'PlotFrequencyMaximum',0.10, ...
    'MaxFrequencyBins',1024, ...
    'NumSurrogates',999, ...
    'IAAFTIterations',200, ...
    'IAAFTSpectralTolerance',0.02, ...
    'RandomSeed',20260802);
settings = parseSettings(settings,varargin{:});
validateSettings(settings);

if nargin < 1 || isempty(outputParent)
    error('Acycle:BispectralValidation:MissingOutput', ...
        'An output parent directory is required.');
end
if ~isfile(settings.LR04File)
    error('Acycle:BispectralValidation:MissingLR04','Missing file: %s',settings.LR04File);
end
if ~isfile(settings.CenogridFile)
    error('Acycle:BispectralValidation:MissingCenogrid', ...
        'Missing file: %s',settings.CenogridFile);
end
if ~isfolder(outputParent)
    [ok,message] = mkdir(outputParent);
    if ~ok, error('Acycle:BispectralValidation:CreateOutput','%s',message); end
end

outputDirectory = createUniqueValidationDirectory(outputParent);

lr04 = readTwoColumn(settings.LR04File);
cenogrid = readTwoColumn(settings.CenogridFile);
definitions = struct( ...
    'Name',{'LR04_0-5.32Ma','CENOGRID_0-5Ma','CENOGRID_10-15Ma','CENOGRID_50-55Ma'}, ...
    'Source',{'lr04','cenogrid','cenogrid','cenogrid'}, ...
    'StartKyr',{0,0,10000,50000}, ...
    'EndKyr',{5320,5000,15000,55000});

rows = repmat(emptySummaryRow(),numel(definitions),1);
caseFiles = cell(numel(definitions),1);
allSignificantTriads = table();
allComputedSignificantTriads = table();
tag = lowessTag(settings.LOWESSWindowKyr);
for caseIndex = 1:numel(definitions)
    definition = definitions(caseIndex);
    if strcmp(definition.Source,'lr04')
        sourceData = lr04;
        sourceFile = settings.LR04File;
    else
        sourceData = cenogrid;
        sourceFile = settings.CenogridFile;
    end
    selected = sourceData(sourceData(:,1) >= definition.StartKyr & ...
        sourceData(:,1) <= definition.EndKyr,:);
    if size(selected,1) < 32
        error('Acycle:BispectralValidation:TooShort', ...
            '%s contains fewer than 32 observations.',definition.Name);
    end
    fprintf('\n[%d/%d] %s: preparing %d observations\n', ...
        caseIndex,numel(definitions),definition.Name,size(selected,1));
    [regular,regularization] = prepareRegularSeries(selected);
    [detrended,trend,lowessSamples,effectiveLowessKyr] = ...
        removeLowessTrend(regular,settings.LOWESSWindowKyr);
    external = externalPreprocessingMetadata(regularization, ...
        settings.LOWESSWindowKyr,lowessSamples,effectiveLowessKyr);
    caseSettings = settings;
    caseSettings.RandomSeed = settings.RandomSeed+caseIndex-1;

    caseDirectory = fullfile(outputDirectory,definition.Name);
    [ok,message] = mkdir(caseDirectory);
    if ~ok, error('Acycle:BispectralValidation:CreateCaseOutput','%s',message); end
    trendVariable = matlab.lang.makeValidName([tag,'Trend']);
    inputTable = table(regular(:,1),regular(:,2),trend,detrended(:,2), ...
        'VariableNames',{'AgeKyr','RegularizedValue',trendVariable,'DetrendedValue'});
    writetable(inputTable,fullfile(caseDirectory,'analysis-inputs.csv'));

    rawOptions = studyOptions(regular,definition.Name,caseSettings,'none');
    fprintf('  raw/regularized estimate ...\n');
    rawResult = bispectralAnalyze(regular,rawOptions);
    rawResult.ExternalPreprocessing = external;
    rawResult.ExternalPreprocessing.Role = 'regularized raw sensitivity control';
    rawResult.ExternalPreprocessing.LOWESS.AppliedToResult = false;
    detrendedOptions = studyOptions(detrended, ...
        [definition.Name,'_',tag],caseSettings,'surrogate-global');
    fprintf('  LOWESS-detrended estimate with %d IAAFT max-stat surrogates ...\n', ...
        settings.NumSurrogates);
    detrendedResult = bispectralAnalyze(detrended,detrendedOptions);
    detrendedResult.ExternalPreprocessing = external;
    detrendedResult.ExternalPreprocessing.Role = ...
        'primary LOWESS-detrended sensitivity result';
    detrendedResult.ExternalPreprocessing.LOWESS.AppliedToResult = true;

    validateResult(rawResult,settings.PlotFrequencyMaximum,caseSettings,false);
    validateResult(detrendedResult,settings.PlotFrequencyMaximum,caseSettings,true);
    if ~isequal(rawResult.Frequency,detrendedResult.Frequency) || ...
            ~isequal(rawResult.PrincipalDomainMask,detrendedResult.PrincipalDomainMask)
        error('Acycle:BispectralValidation:InconsistentGrid', ...
            '%s raw and detrended results do not share a computed grid.',definition.Name);
    end

    fprintf('  rendering and saving validated Overview figures ...\n');
    [rawFiles,rawOverviewQA] = saveOverviewResult(rawResult,caseDirectory, ...
        [definition.Name,'_raw']);
    [detrendedFiles,detrendedOverviewQA] = saveOverviewResult( ...
        detrendedResult,caseDirectory,[definition.Name,'_',tag]);
    trendFiles = saveTrendFigure(regular,trend,detrended,caseDirectory, ...
        definition.Name,tag,settings.LOWESSWindowKyr);

    rawPeak = peakSummary(rawResult,settings.PlotFrequencyMaximum,false);
    detrendedPeak = peakSummary(detrendedResult,settings.PlotFrequencyMaximum,true);
    significantTriads = significantTriadTable( ...
        detrendedResult,settings.PlotFrequencyMaximum,definition.Name);
    computedSignificantTriads = significantTriadTable( ...
        detrendedResult,Inf,definition.Name);
    significantTriadPath = fullfile(caseDirectory,'significant-visible-triads.csv');
    computedTriadPath = fullfile(caseDirectory,'significant-computed-triads.csv');
    writetable(significantTriads,significantTriadPath);
    writetable(computedSignificantTriads,computedTriadPath);
    if isempty(allSignificantTriads)
        allSignificantTriads = significantTriads;
    else
        allSignificantTriads = [allSignificantTriads;significantTriads]; %#ok<AGROW>
    end
    if isempty(allComputedSignificantTriads)
        allComputedSignificantTriads = computedSignificantTriads;
    else
        allComputedSignificantTriads = [allComputedSignificantTriads; ...
            computedSignificantTriads]; %#ok<AGROW>
    end
    rows(caseIndex) = struct( ...
        'Case',string(definition.Name), ...
        'SourceFile',string(sourceFile), ...
        'StartKyr',regular(1,1), ...
        'EndKyr',regular(end,1), ...
        'OriginalN',regularization.OriginalCount, ...
        'RegularN',size(regular,1), ...
        'SampleIntervalKyr',regularization.SampleInterval, ...
        'OriginalMaxSpacingDeparturePercent', ...
            100*regularization.RelativeSpacingDeparture, ...
        'LargestGapFactor',regularization.LargestGapFactor, ...
        'OriginallyIrregular',regularization.OriginallyIrregular, ...
        'RegularGridReconstructed',regularization.RegularGridReconstructed, ...
        'LOWESSSamples',lowessSamples, ...
        'EffectiveLOWESSWindowKyr',effectiveLowessKyr, ...
        'RawLongPeriodPowerFraction',longPeriodPowerFraction( ...
            regular(:,2),regularization.SampleInterval,settings.LOWESSWindowKyr), ...
        'DetrendedLongPeriodPowerFraction',longPeriodPowerFraction( ...
            detrended(:,2),regularization.SampleInterval,settings.LOWESSWindowKyr), ...
        'RawPeakBicoherenceSquared',rawPeak.BicoherenceSquared, ...
        'RawPeakF1PerKyr',rawPeak.F1, ...
        'RawPeakF2PerKyr',rawPeak.F2, ...
        'DetrendedPeakBicoherenceSquared',detrendedPeak.BicoherenceSquared, ...
        'DetrendedPeakF1PerKyr',detrendedPeak.F1, ...
        'DetrendedPeakF2PerKyr',detrendedPeak.F2, ...
        'DetrendedSignificantVisibleTriads',detrendedPeak.SignificantCount, ...
        'DetrendedSignificantComputedTriads',height(computedSignificantTriads), ...
        'GlobalSurrogateThreshold',detrendedResult.Significance.Threshold, ...
        'ThresholdComparison',string( ...
            detrendedResult.Significance.ThresholdComparison), ...
        'InferenceMethod',"IAAFT maximum-statistic FWER", ...
        'FWERConfidenceLevel',detrendedResult.Significance.ConfidenceLevel, ...
        'InferenceFamily',string( ...
            detrendedResult.Significance.InferenceFamilyDefinition), ...
        'InferenceFamilyTriadCount', ...
            detrendedResult.Significance.InferenceFamilyTriadCount, ...
        'ComputedAxisBinCount',detrendedResult.Meta.ComputedAxisBinCount, ...
        'FrequencyBinStride',detrendedResult.Meta.FrequencyBinStride, ...
        'RayleighResolutionPerKyr',detrendedResult.Meta.RayleighResolution, ...
        'ComputedAxisFrequencyMinimumPerKyr', ...
            detrendedResult.Meta.ComputedAxisFrequencyMinimum, ...
        'ComputedAxisFrequencyMaximumPerKyr', ...
            detrendedResult.Meta.ComputedAxisFrequencyMaximum, ...
        'SurrogateType',string(detrendedResult.Significance.SurrogateType), ...
        'AcceptedSurrogates',detrendedResult.Significance.NumSurrogates, ...
        'IAAFTIterations',detrendedResult.Options.IAAFTIterations, ...
        'IAAFTSpectralTolerance', ...
            detrendedResult.Significance.IAAFTSpectralTolerance, ...
        'SurrogateAttempts',detrendedResult.Significance.SurrogateAttemptCount, ...
        'RejectedSurrogates',detrendedResult.Significance.RejectedSurrogateCount, ...
        'RandomSeed',detrendedResult.Significance.RandomSeed, ...
        'MaximumAcceptedIAAFTSpectralError',max( ...
            detrendedResult.Significance.SurrogateSpectralErrors,[],'omitnan'));
    caseFiles{caseIndex} = struct('Raw',rawFiles,'Primary',detrendedFiles, ...
        'RawOverviewQA',rawOverviewQA,'PrimaryOverviewQA',detrendedOverviewQA, ...
        'Trend',trendFiles,'VisibleSignificantTriads',significantTriadPath, ...
        'ComputedSignificantTriads',computedTriadPath);
    fprintf('  complete: raw long-period fraction %.4f -> detrended %.4f\n', ...
        rows(caseIndex).RawLongPeriodPowerFraction, ...
        rows(caseIndex).DetrendedLongPeriodPowerFraction);
end

summary = struct2table(rows);
writetable(summary,fullfile(outputDirectory,'validation-summary.csv'));
writetable(allSignificantTriads,fullfile(outputDirectory,'significant-visible-triads.csv'));
writetable(allComputedSignificantTriads, ...
    fullfile(outputDirectory,'significant-computed-triads.csv'));
writeStudyNotes(fullfile(outputDirectory,'README.md'),summary,settings);
validation = struct( ...
    'Passed',true, ...
    'OutputDirectory',outputDirectory, ...
    'Created',char(datetime('now','Format','yyyy-MM-dd HH:mm:ss')), ...
    'Settings',settings, ...
    'Summary',summary, ...
    'CaseFiles',{caseFiles});
save(fullfile(outputDirectory,'validation-workspace.mat'),'validation','-v7.3');
jsonSummary = struct('Passed',validation.Passed,'Created',validation.Created, ...
    'OutputDirectory',outputDirectory,'Settings',settings, ...
    'Summary',table2struct(summary));
writeText(fullfile(outputDirectory,'validation-summary.json'), ...
    [jsonencode(jsonSummary,'PrettyPrint',true),newline]);
fprintf('\nValidation output: %s\n',outputDirectory);
end

function triads = significantTriadTable(result,plotMaximum,caseName)
f = result.Frequency(:);
[f1Grid,f2Grid] = meshgrid(f,f);
mask = result.SignificantMask & f1Grid <= plotMaximum & f2Grid <= plotMaximum;
indices = find(mask);
[~,order] = sort(result.BicoherenceSquared(indices),'descend');
indices = indices(order);
[row,column] = ind2sub(size(mask),indices);
f1 = f(column);
f2 = f(row);
f3 = f1+f2;
triads = table(repmat(string(caseName),numel(indices),1),f1,f2,f3, ...
    1./f1,1./f2,1./f3,result.BicoherenceSquared(indices), ...
    result.Significance.PValue(indices),result.BispectrumMagnitude(indices), ...
    'VariableNames',{'Case','F1PerKyr','F2PerKyr','F3PerKyr', ...
    'Period1Kyr','Period2Kyr','Period3Kyr','BicoherenceSquared', ...
    'GlobalPValue','BispectrumMagnitude'});
end

function options = studyOptions(data,name,settings,significanceMethod)
options = bispectralDefaults(data);
options.InputPolicy = 'strict';
options.Interpolate = 'never';
options.SampleInterval = [];
options.DetrendMethod = 'none';
options.Standardize = false;
options.SegmentDetrendMethod = 'mean';
options.Estimator = 'wosa';
options.NumSegments = 8;
options.OverlapPercent = 50;
options.Window = 'hann';
options.ZeroPaddingFactor = 1;
options.MaxFrequencyBins = settings.MaxFrequencyBins;
options.FrequencyMin = 0;
options.FrequencyMax = settings.PlotFrequencyMaximum;
options.SignificanceMethod = significanceMethod;
options.ConfidenceLevel = 0.95;
options.NumSurrogates = settings.NumSurrogates;
options.SurrogateType = 'iaaft';
options.IAAFTIterations = settings.IAAFTIterations;
options.IAAFTSpectralTolerance = settings.IAAFTSpectralTolerance;
options.RandomSeed = settings.RandomSeed;
options.PlotQuantity = 'overview';
options.PlotPeakCount = 5;
options.ShowPeriodAxes = true;
options.InputName = name;
options.CoordinateUnit = 'kyr';
end

function [files,qa] = saveOverviewResult(result,outputDirectory,stem)
[fig,handles] = bispectralPlot(result,'Visible','off','Quantity','overview', ...
    'ShowPeriodAxes',true,'PeakCount',5);
cleanup = onCleanup(@()closeFigure(fig));
drawnow;
qa = validateOverviewFigure(fig,handles,result);
result.ExternalPreprocessing.OverviewValidation = qa;
files = bispectralSave(result,fig,outputDirectory,[stem,'_overview']);
end

function qa = validateOverviewFigure(fig,handles,result)
required = {'PowerLeft','PowerRight','Bispectrum','Bicoherence', ...
    'BispectrumMap','BicoherenceMap','PowerSpectrumMetadata'};
if ~all(isfield(handles,required))
    error('Acycle:BispectralValidation:OverviewHandles', ...
        'The Overview figure did not return its required axes and maps.');
end
leftPowerBox = actualPlotBox(handles.PowerLeft);
rightPowerBox = actualPlotBox(handles.PowerRight);
leftMapBox = actualPlotBox(handles.Bispectrum);
rightMapBox = actualPlotBox(handles.Bicoherence);
tolerancePixels = 2.5;
leftAligned = max(abs(leftPowerBox([1 3])-leftMapBox([1 3]))) <= tolerancePixels;
rightAligned = max(abs(rightPowerBox([1 3])-rightMapBox([1 3]))) <= tolerancePixels;
leftMapSquare = abs(leftMapBox(3)-leftMapBox(4)) <= tolerancePixels;
rightMapSquare = abs(rightMapBox(3)-rightMapBox(4)) <= tolerancePixels;
leftXAligned = max(abs(handles.PowerLeft.XLim-handles.Bispectrum.XLim)) <= ...
    64*eps(max(1,max(abs(handles.Bispectrum.XLim))));
rightXAligned = max(abs(handles.PowerRight.XLim-handles.Bicoherence.XLim)) <= ...
    64*eps(max(1,max(abs(handles.Bicoherence.XLim))));
twoLogAxes = strcmp(handles.PowerLeft.YScale,'log') && ...
    strcmp(handles.PowerRight.YScale,'log');
leftAlpha = handles.BispectrumMap.Image.AlphaData;
rightAlpha = handles.BicoherenceMap.Image.AlphaData;
independentMasksVisible = nnz(leftAlpha > 0) > 0 && nnz(rightAlpha > 0) > 0 && ...
    isfinite(handles.BispectrumMap.KeepCutoff) && ...
    isfinite(handles.BicoherenceMap.KeepCutoff);
renderSettings = getappdata(fig,'BispectralRenderSettings');
hasIndependentSettings = isstruct(renderSettings) && ...
    isfield(renderSettings,'BispectrumKeepStrongestFraction') && ...
    isfield(renderSettings,'BicoherenceKeepStrongestFraction');
interpolatedPcolor = strcmp(handles.BispectrumMap.Image.FaceColor,'interp') && ...
    strcmp(handles.BicoherenceMap.Image.FaceColor,'interp') && ...
    strcmp(handles.BispectrumMap.Image.EdgeColor,'none') && ...
    strcmp(handles.BicoherenceMap.Image.EdgeColor,'none');
valueContoursPresent = isgraphics(handles.BispectrumMap.ValueContour) && ...
    isgraphics(handles.BicoherenceMap.ValueContour);
colorGridRecordedAndApplied = hasIndependentSettings && ...
    isfield(renderSettings,'ColorGrid') && ...
    size(colormap(handles.Bispectrum),1) == renderSettings.ColorGrid && ...
    size(colormap(handles.Bicoherence),1) == renderSettings.ColorGrid;

[powerCurvesPresent,powerCurvesIdentical,powerCurvesMatchMTM, ...
    powerCurvePointCount] = validatePowerCurves(handles,result);
[mtmMetadataRecorded,mtmRenderSettingsConsistent] = ...
    validateMtmMetadata(handles.PowerSpectrumMetadata,renderSettings,result);
[powerScaleCorrect,powerTicksLabeled] = validatePowerDisplay(handles);
powerTitlesCorrect = strcmp(handles.PowerLeft.Title.String, ...
    'Complex bispectrum amplitude, |B|') && ...
    strcmp(handles.PowerRight.Title.String, ...
    'Magnitude-squared bicoherence, b^2');
powerLabelsCorrect = isempty(strtrim(handles.PowerLeft.XLabel.String)) && ...
    isempty(strtrim(handles.PowerRight.XLabel.String)) && ...
    strcmp(handles.PowerLeft.YLabel.String,'2\pi MTM power') && ...
    strcmp(handles.PowerRight.YLabel.String,'2\pi MTM power');
mapTitlesEmpty = isempty(strtrim(handles.Bispectrum.Title.String)) && ...
    isempty(strtrim(handles.Bicoherence.Title.String));
mapLabelsPresent = contains(handles.Bispectrum.XLabel.String,'f_1') && ...
    contains(handles.Bispectrum.YLabel.String,'f_2') && ...
    contains(handles.Bicoherence.XLabel.String,'f_1') && ...
    contains(handles.Bicoherence.YLabel.String,'f_2');
[horizontalColorbars,colorbarsBetweenMapsAndCaption,colorbarBoxes] = ...
    validateOverviewColorbars(fig,handles,leftMapBox,rightMapBox);
[figureTitleCorrect,figureTitleExtensionFree] = ...
    validateOverviewTitle(fig,renderSettings,result);
[retainSettingsConsistent,retainCutoffsConsistent,expectedCutoffs] = ...
    validateOverviewRetain(result,handles,renderSettings);

qa = struct( ...
    'TwoLogPowerAxes',twoLogAxes, ...
    'TwoPowerCurvesPresent',powerCurvesPresent, ...
    'PowerCurvesIdentical',powerCurvesIdentical, ...
    'PowerCurvesMatchMTM',powerCurvesMatchMTM, ...
    'PowerCurvePointCount',powerCurvePointCount, ...
    'MTMMetadataRecorded',mtmMetadataRecorded, ...
    'MTMRenderSettingsConsistent',mtmRenderSettingsConsistent, ...
    'PowerScaleVisibleRangeAndHeadroomCorrect',powerScaleCorrect, ...
    'PowerYTicksLabeled',powerTicksLabeled, ...
    'PowerSpectrumMetadata',handles.PowerSpectrumMetadata, ...
    'PowerTitlesCorrect',powerTitlesCorrect, ...
    'PowerAndMapLabelsCorrect',powerLabelsCorrect && mapLabelsPresent, ...
    'MapTitlesEmpty',mapTitlesEmpty, ...
    'LeftActualPlotBoxAligned',leftAligned, ...
    'RightActualPlotBoxAligned',rightAligned, ...
    'LeftFrequencyLimitsAligned',leftXAligned, ...
    'RightFrequencyLimitsAligned',rightXAligned, ...
    'LeftMapActualPlotBoxSquare',leftMapSquare, ...
    'RightMapActualPlotBoxSquare',rightMapSquare, ...
    'IndependentMasksVisible',independentMasksVisible, ...
    'IndependentRetainSettingsRecorded',hasIndependentSettings, ...
    'RetainSettingsConsistent',retainSettingsConsistent, ...
    'RetainCutoffsConsistent',retainCutoffsConsistent, ...
    'ExpectedRetainCutoffs',expectedCutoffs, ...
    'ActualRetainCutoffs',[handles.BispectrumMap.KeepCutoff, ...
        handles.BicoherenceMap.KeepCutoff], ...
    'InterpolatedPcolorWithoutEdges',interpolatedPcolor, ...
    'ValueContoursPresent',valueContoursPresent, ...
    'ColorGridRecordedAndApplied',colorGridRecordedAndApplied, ...
    'HorizontalColorbars',horizontalColorbars, ...
    'ColorbarsBetweenMapsAndCaption',colorbarsBetweenMapsAndCaption, ...
    'ColorbarBoxesPixels',colorbarBoxes, ...
    'FigureTitleCorrect',figureTitleCorrect, ...
    'FigureTitleExtensionFree',figureTitleExtensionFree, ...
    'PlotBoxTolerancePixels',tolerancePixels, ...
    'LeftPowerPlotBoxPixels',leftPowerBox, ...
    'LeftMapPlotBoxPixels',leftMapBox, ...
    'RightPowerPlotBoxPixels',rightPowerBox, ...
    'RightMapPlotBoxPixels',rightMapBox);
checks = [twoLogAxes,leftAligned,rightAligned,leftXAligned,rightXAligned, ...
    leftMapSquare,rightMapSquare,independentMasksVisible, ...
    hasIndependentSettings,interpolatedPcolor,valueContoursPresent, ...
    colorGridRecordedAndApplied,powerCurvesPresent,powerCurvesIdentical, ...
    powerCurvesMatchMTM,mtmMetadataRecorded,mtmRenderSettingsConsistent, ...
    powerScaleCorrect,powerTicksLabeled, ...
    powerTitlesCorrect,powerLabelsCorrect,mapTitlesEmpty,mapLabelsPresent, ...
    horizontalColorbars,colorbarsBetweenMapsAndCaption,figureTitleCorrect, ...
    figureTitleExtensionFree,retainSettingsConsistent,retainCutoffsConsistent];
if ~all(checks)
    error('Acycle:BispectralValidation:OverviewLayout', ...
        ['An Overview failed its MTM curve/metadata, title/label, square ', ...
        'plot-box, frequency, pcolor, contour, colorbar, colormap, or ', ...
        'independent-retain QA.']);
end
end

function [scaleCorrect,ticksLabeled] = validatePowerDisplay(handles)
axesToCheck = [handles.PowerLeft handles.PowerRight];
scaleCorrect = true;
ticksLabeled = true;
for axisIndex = 1:numel(axesToCheck)
    ax = axesToCheck(axisIndex);
    lines = findobj(ax,'Type','line');
    if ~isscalar(lines)
        scaleCorrect = false;
        ticksLabeled = false;
        continue
    end
    frequency = double(lines.XData(:));
    power = double(lines.YData(:));
    visible = isfinite(frequency) & frequency >= ax.XLim(1) & ...
        frequency <= ax.XLim(2) & isfinite(power) & power > 0;
    if ~any(visible)
        scaleCorrect = false;
    else
        lower = min(power(visible));
        peak = max(power(visible));
        limits = ax.YLim;
        tolerance = 256*eps(max([1 abs(lower) abs(limits)]));
        if peak > lower*(1+64*eps)
            peakHeight = (log(peak)-log(limits(1)))/ ...
                (log(limits(2))-log(limits(1)));
            headroomCorrect = abs(peakHeight-0.8) <= 1e-10;
        else
            headroomCorrect = limits(2) > limits(1);
        end
        scaleCorrect = scaleCorrect && ...
            abs(limits(1)-lower) <= tolerance && headroomCorrect;
    end
    labels = ax.YTickLabel;
    if ischar(labels)
        labels = string(cellstr(labels));
    else
        labels = string(labels(:));
    end
    ticksLabeled = ticksLabeled && numel(ax.YTick) >= 3 && ...
        numel(labels) >= 3 && all(strlength(strtrim(labels)) > 0);
end
scaleCorrect = scaleCorrect && numericVectorsClose( ...
    handles.PowerLeft.YLim,handles.PowerRight.YLim);
end

function [present,identical,matchesExpected,pointCount] = ...
        validatePowerCurves(handles,result)
leftLines = findobj(handles.PowerLeft,'Type','line');
rightLines = findobj(handles.PowerRight,'Type','line');
present = isscalar(leftLines) && isscalar(rightLines);
identical = false;
matchesExpected = false;
pointCount = 0;
if ~present
    return
end
leftFrequency = double(leftLines(1).XData(:));
leftPower = double(leftLines(1).YData(:));
rightFrequency = double(rightLines(1).XData(:));
rightPower = double(rightLines(1).YData(:));
pointCount = numel(leftFrequency);
identical = numericVectorsClose(leftFrequency,rightFrequency) && ...
    numericVectorsClose(leftPower,rightPower);

y = double(result.ProcessedData(:,2));
y = y-mean(y);
nfft = 5*numel(y);
[expectedPower,angularFrequency] = pmtm(y,2,nfft);
expectedFrequency = double(angularFrequency(:))/(2*pi*result.Meta.SampleInterval);
expectedPower = double(expectedPower(:));
expectedPower(~isfinite(expectedPower) | expectedPower <= 0) = NaN;
matchesExpected = numericVectorsClose(leftFrequency,expectedFrequency) && ...
    numericVectorsClose(leftPower,expectedPower);
end

function [metadataRecorded,renderSettingsConsistent] = ...
        validateMtmMetadata(metadata,renderSettings,result)
requiredMetadata = {'Method','TimeBandwidth','TaperCount','PaddingFactor', ...
    'NFFT','InputLength','MeanRemoved','FrequencyCoordinate'};
metadataRecorded = isstruct(metadata) && isscalar(metadata) && ...
    all(isfield(metadata,requiredMetadata));
if metadataRecorded
    n = size(result.ProcessedData,1);
    metadataRecorded = strcmp(metadata.Method,'2pi MTM (Thomson)') && ...
        metadata.TimeBandwidth == 2 && metadata.TaperCount == 3 && ...
        metadata.PaddingFactor == 5 && metadata.NFFT == 5*n && ...
        metadata.InputLength == n && isequal(metadata.MeanRemoved,true) && ...
        strcmp(metadata.FrequencyCoordinate,'cycles per coordinate unit');
end
requiredRender = {'PowerSpectrumMethod','PowerSpectrumTimeBandwidth', ...
    'PowerSpectrumTaperCount','PowerSpectrumPaddingFactor', ...
    'PowerSpectrumNFFT','PowerSpectrumInputLength', ...
    'PowerSpectrumMeanRemoved','PowerSpectrumFrequencyCoordinate', ...
    'PowerSpectrumDisplayed','PowerSpectrumHeadroomFraction', ...
    'PowerSpectrumYLimits','PowerSpectrumYTicks','MinimumFontSizePoints'};
renderSettingsConsistent = isstruct(renderSettings) && ...
    all(isfield(renderSettings,requiredRender));
if renderSettingsConsistent
    renderSettingsConsistent = metadataRecorded && ...
        strcmp(renderSettings.PowerSpectrumMethod,metadata.Method) && ...
        renderSettings.PowerSpectrumTimeBandwidth == metadata.TimeBandwidth && ...
        renderSettings.PowerSpectrumTaperCount == metadata.TaperCount && ...
        renderSettings.PowerSpectrumPaddingFactor == metadata.PaddingFactor && ...
        renderSettings.PowerSpectrumNFFT == metadata.NFFT && ...
        renderSettings.PowerSpectrumInputLength == metadata.InputLength && ...
        isequal(renderSettings.PowerSpectrumMeanRemoved,metadata.MeanRemoved) && ...
        strcmp(renderSettings.PowerSpectrumFrequencyCoordinate, ...
        metadata.FrequencyCoordinate) && ...
        isequal(renderSettings.PowerSpectrumDisplayed,true) && ...
        renderSettings.PowerSpectrumHeadroomFraction == 0.20 && ...
        numel(renderSettings.PowerSpectrumYLimits) == 2 && ...
        all(isfinite(renderSettings.PowerSpectrumYLimits)) && ...
        renderSettings.PowerSpectrumYLimits(1) > 0 && ...
        renderSettings.PowerSpectrumYLimits(2) > ...
        renderSettings.PowerSpectrumYLimits(1) && ...
        numel(renderSettings.PowerSpectrumYTicks) >= 3 && ...
        renderSettings.MinimumFontSizePoints >= 6;
end
end

function [horizontal,between,boxes] = validateOverviewColorbars( ...
        fig,handles,leftMapBox,rightMapBox)
colorbars = [handles.BispectrumMap.Colorbar,handles.BicoherenceMap.Colorbar];
horizontal = all(isgraphics(colorbars,'colorbar')) && ...
    all(strcmp({colorbars.Location},'southoutside')) && ...
    all(strcmp({colorbars.Orientation},'horizontal'));
between = false;
boxes = nan(2,4);
if ~horizontal
    return
end
textBoxes = findall(fig,'Type','textboxshape');
captionTop = -Inf;
figurePixels = getpixelposition(fig);
for ii = 1:numel(textBoxes)
    position = textBoxes(ii).Position;
    if position(2) < 0.2
        captionTop = max(captionTop,(position(2)+position(4))*figurePixels(4));
    end
end
boxes(1,:) = getpixelposition(colorbars(1),true);
boxes(2,:) = getpixelposition(colorbars(2),true);
belowMaps = boxes(1,2)+boxes(1,4) < leftMapBox(2) && ...
    boxes(2,2)+boxes(2,4) < rightMapBox(2);
aboveCaption = isfinite(captionTop) && boxes(1,2) > captionTop && ...
    boxes(2,2) > captionTop;
between = belowMaps && aboveCaption;
end

function [correct,extensionFree] = validateOverviewTitle(fig,renderSettings,result)
expectedTitle = [validationDisplayName(result),': bispectral analysis'];
correct = isfield(renderSettings,'Title') && ...
    strcmp(fig.Name,expectedTitle) && strcmp(renderSettings.Title,expectedTitle);
titleBoxes = findall(fig,'Type','textboxshape');
hasMatchingHeading = false;
for ii = 1:numel(titleBoxes)
    if titleBoxes(ii).Position(2) > 0.9 && ...
            strcmp(titleBoxes(ii).String,expectedTitle)
        hasMatchingHeading = true;
        break
    end
end
correct = correct && hasMatchingHeading;
displayedName = validationDisplayName(result);
[~,~,displayedExtension] = fileparts(displayedName);
knownExtensions = {'.txt','.csv','.dat','.out','.res','.tab', ...
    '.mat','.xlsx','.xls'};
extensionFree = ~any(strcmpi(displayedExtension,knownExtensions));
end

function name = validationDisplayName(result)
name = strtrim(char(result.InputName));
if isempty(name)
    name = 'Data';
    return
end
[~,base,extension] = fileparts(name);
knownExtensions = {'.txt','.csv','.dat','.out','.res','.tab', ...
    '.mat','.xlsx','.xls'};
if any(strcmpi(extension,knownExtensions))
    name = base;
else
    name = [base,extension];
end
end

function [settingsConsistent,cutoffsConsistent,expectedCutoffs] = ...
        validateOverviewRetain(result,handles,renderSettings)
required = {'BispectrumKeepStrongestFraction', ...
    'BicoherenceKeepStrongestFraction','FrequencyMinimum','FrequencyMaximum'};
settingsConsistent = isstruct(renderSettings) && all(isfield(renderSettings,required));
expectedCutoffs = [NaN NaN];
if ~settingsConsistent
    cutoffsConsistent = false;
    return
end
bispectrumFraction = renderSettings.BispectrumKeepStrongestFraction;
bicoherenceFraction = renderSettings.BicoherenceKeepStrongestFraction;
settingsConsistent = numericScalarsClose(bispectrumFraction, ...
    result.Options.PlotKeepStrongestBispectrumFraction) && ...
    numericScalarsClose(bicoherenceFraction, ...
    result.Options.PlotKeepStrongestBicoherenceFraction);
expectedCutoffs(1) = expectedRetainCutoff(result,'bispectrum-magnitude', ...
    bispectrumFraction,renderSettings.FrequencyMinimum, ...
    renderSettings.FrequencyMaximum);
expectedCutoffs(2) = expectedRetainCutoff(result,'bicoherence-squared', ...
    bicoherenceFraction,renderSettings.FrequencyMinimum, ...
    renderSettings.FrequencyMaximum);
cutoffsConsistent = numericScalarsClose( ...
    handles.BispectrumMap.KeepCutoff,expectedCutoffs(1)) && ...
    numericScalarsClose(handles.BicoherenceMap.KeepCutoff,expectedCutoffs(2));
end

function cutoff = expectedRetainCutoff(result,quantity,fraction,minimum,maximum)
f = result.Frequency(:);
[f1,f2] = meshgrid(f,f);
visible = f1 >= minimum & f1 <= maximum & f2 >= minimum & f2 <= maximum;
switch quantity
    case 'bispectrum-magnitude'
        raw = result.BispectrumMagnitude;
        finitePositive = raw(isfinite(raw) & raw > 0);
        if isempty(finitePositive)
            floorValue = realmin;
        else
            floorValue = max(realmin,min(finitePositive)*0.1);
        end
        metric = nan(size(raw));
        valid = isfinite(raw);
        metric(valid) = log10(max(raw(valid),floorValue));
    case 'bicoherence-squared'
        metric = result.BicoherenceSquared;
    otherwise
        error('Acycle:BispectralValidation:OverviewRetain', ...
            'Unknown retain metric: %s',quantity);
end
if fraction >= 1
    cutoff = -Inf;
    return
end
values = sort(metric(isfinite(metric) & visible));
if isempty(values)
    cutoff = -Inf;
    return
end
firstKept = max(1,min(numel(values),floor((1-fraction)*numel(values))+1));
cutoff = values(firstKept);
end

function same = numericVectorsClose(first,second)
first = double(first(:));
second = double(second(:));
if ~isequal(size(first),size(second)) || ...
        ~isequal(isnan(first),isnan(second)) || ...
        ~isequal(isinf(first),isinf(second))
    same = false;
    return
end
if ~all(first(isinf(first)) == second(isinf(second)))
    same = false;
    return
end
finite = isfinite(first) & isfinite(second);
scale = max([1;abs(first(finite));abs(second(finite))]);
same = all(abs(first(finite)-second(finite)) <= 512*eps(scale));
end

function same = numericScalarsClose(first,second)
same = numericVectorsClose(first,second);
end

function position = actualPlotBox(ax)
position = getpixelposition(ax,true);
if strcmp(ax.PlotBoxAspectRatioMode,'manual')
    ratio = ax.PlotBoxAspectRatio(1)/ax.PlotBoxAspectRatio(2);
    availableRatio = position(3)/position(4);
    if availableRatio > ratio
        width = position(4)*ratio;
        position(1) = position(1)+(position(3)-width)/2;
        position(3) = width;
    elseif availableRatio < ratio
        height = position(3)/ratio;
        position(2) = position(2)+(position(4)-height)/2;
        position(4) = height;
    end
end
end

function files = saveTrendFigure(regular,trend,detrended,outputDirectory,name, ...
        tag,windowKyr)
fig = figure('Visible','off','Color','w','Position',[100 100 1100 720], ...
    'Name',[name,' preprocessing sensitivity'],'NumberTitle','off');
cleanup = onCleanup(@()closeFigure(fig));
top = subplot(2,1,1,'Parent',fig);
plot(top,regular(:,1),regular(:,2),'Color',[0.12 0.12 0.12],'LineWidth',0.7);
hold(top,'on');
plot(top,regular(:,1),trend,'Color',[0.75 0.12 0.12],'LineWidth',1.2);
grid(top,'on'); box(top,'on');
xlabel(top,'Age (kyr)'); ylabel(top,'Value');
top.FontSize = 11;
top.Title.FontSize = 12;
title(top,sprintf('%s: regularized data and %g kyr LOWESS trend',name,windowKyr), ...
    'Interpreter','none','FontSize',12);
trendLegend = legend(top,{'Regularized data',sprintf('%g kyr LOWESS',windowKyr)}, ...
    'Location','best');
trendLegend.FontSize = 10;
bottom = subplot(2,1,2,'Parent',fig);
plot(bottom,detrended(:,1),detrended(:,2),'Color',[0.10 0.28 0.68],'LineWidth',0.7);
grid(bottom,'on'); box(bottom,'on');
xlabel(bottom,'Age (kyr)'); ylabel(bottom,'Detrended value');
bottom.FontSize = 11;
title(bottom,'Data used for the primary bispectral estimate','FontSize',12);
files = struct( ...
    'PDF',fullfile(outputDirectory,[name,'_',tag,'-diagnostic.pdf']), ...
    'PNG',fullfile(outputDirectory,[name,'_',tag,'-diagnostic.png']), ...
    'FIG',fullfile(outputDirectory,[name,'_',tag,'-diagnostic.fig']));
bispectralExportVectorPDF(fig,files.PDF);
exportgraphics(fig,files.PNG,'Resolution',300);
savefig(fig,files.FIG);
end

function validateResult(result,plotMaximum,settings,requireFormalInference)
finiteBicoherence = result.BicoherenceSquared(isfinite(result.BicoherenceSquared));
if isempty(finiteBicoherence) || any(finiteBicoherence < -1e-12 | ...
        finiteBicoherence > 1+1e-12)
    error('Acycle:BispectralValidation:BicoherenceBounds', ...
        'A result failed the bicoherence [0,1] bound check.');
end
if result.Meta.ComputedAxisFrequencyMaximum <= plotMaximum
    error('Acycle:BispectralValidation:FrequencyLimitCheck', ...
        'The test requires a plot maximum below the computed maximum.');
end
if result.Meta.TriadCount ~= nnz(result.PrincipalDomainMask)
    error('Acycle:BispectralValidation:TriadCount', ...
        'Stored triad count disagrees with the principal-domain mask.');
end
method = strtrim(char(result.Significance.Method));
if any(strcmpi(method,{'surrogate-global','global-surrogate','max-surrogate'})) && ...
        (result.Significance.InferenceFamilyTriadCount ~= nnz(result.ValidMask) || ...
        ~contains(result.Significance.InferenceFamilyDefinition,'Fixed finite'))
    error('Acycle:BispectralValidation:InferenceFamily', ...
        ['The saved formal result does not describe the fixed finite ', ...
         'computed-principal-domain inference family.']);
end
if requireFormalInference
    validateFormalInference(result,settings);
end
end

function validateFormalInference(result,settings)
significance = result.Significance;
required = {'Method','SurrogateType','NumSurrogates','ConfidenceLevel', ...
    'Threshold','ThresholdComparison','ThresholdMatrix','PValue', ...
    'SurrogateMaxima','SurrogateSpectralErrors','SurrogateAttemptCount', ...
    'RejectedSurrogateCount','IAAFTSpectralTolerance','RandomSeed', ...
    'InferenceFamilyTriadCount','FrequencyViewLimitsAffectInferenceFamily'};
if ~all(isfield(significance,required))
    error('Acycle:BispectralValidation:FormalInferenceQA', ...
        'The formal result is missing required IAAFT/FWER audit fields.');
end
expectedCount = settings.NumSurrogates;
tolerance = settings.IAAFTSpectralTolerance;
maxima = significance.SurrogateMaxima(:);
spectralErrors = significance.SurrogateSpectralErrors(:);
family = result.ValidMask & isfinite(result.BicoherenceSquared);
thresholdValues = significance.ThresholdMatrix(family);
familyPValues = significance.PValue(family);
alpha = 1-significance.ConfidenceLevel;
admissibleCounts = find((1+(0:expectedCount))/(expectedCount+1) <= alpha)-1;
expectedThreshold = NaN;
if ~isempty(admissibleCounts) && numel(maxima) == expectedCount
    criticalRank = expectedCount-max(admissibleCounts);
    sortedMaxima = sort(maxima);
    expectedThreshold = sortedMaxima(criticalRank);
end
confidenceTolerance = 64*eps(max(1,abs(significance.ConfidenceLevel)));
spectralTolerance = tolerance+64*eps(max(1,abs(tolerance)));
valid = strcmpi(significance.Method,'surrogate-global') && ...
    strcmpi(significance.SurrogateType,'iaaft') && ...
    significance.NumSurrogates == expectedCount && ...
    significance.RandomSeed == settings.RandomSeed && ...
    result.Options.IAAFTIterations == settings.IAAFTIterations && ...
    abs(significance.ConfidenceLevel-0.95) <= confidenceTolerance && ...
    isfinite(significance.Threshold) && ...
    significance.Threshold == expectedThreshold && ...
    contains(significance.ThresholdComparison,'strictly greater', ...
    'IgnoreCase',true) && ...
    numel(maxima) == expectedCount && all(isfinite(maxima)) && ...
    numel(spectralErrors) == expectedCount && all(isfinite(spectralErrors)) && ...
    all(spectralErrors <= spectralTolerance) && ...
    significance.IAAFTSpectralTolerance == tolerance && ...
    significance.SurrogateAttemptCount == expectedCount+ ...
    significance.RejectedSurrogateCount && ...
    significance.InferenceFamilyTriadCount == nnz(family) && ...
    ~significance.FrequencyViewLimitsAffectInferenceFamily && ...
    numel(thresholdValues) == nnz(family) && ...
    all(isfinite(thresholdValues)) && ...
    all(thresholdValues == significance.Threshold) && ...
    ~any(isfinite(significance.ThresholdMatrix(~family))) && ...
    all(isfinite(familyPValues)) && ...
    isequal(result.SignificantMask, ...
    family & result.BicoherenceSquared > significance.Threshold & ...
    significance.PValue <= alpha);
if ~valid
    error('Acycle:BispectralValidation:FormalInferenceQA', ...
        ['The primary result failed an accepted-count, IAAFT quality, ', ...
         'plus-one threshold, fixed-family, or FWER metadata assertion.']);
end
end

function peak = peakSummary(result,plotMaximum,requireSignificance)
f = result.Frequency(:);
[f1,f2] = meshgrid(f,f);
visible = result.ValidMask & f1 <= plotMaximum & f2 <= plotMaximum;
significant = visible & result.SignificantMask;
candidate = visible;
if requireSignificance && any(significant(:))
    candidate = significant;
end
indices = find(candidate & isfinite(result.BicoherenceSquared));
if isempty(indices)
    peak = struct('BicoherenceSquared',NaN,'F1',NaN,'F2',NaN, ...
        'SignificantCount',nnz(significant));
    return
end
[value,localIndex] = max(result.BicoherenceSquared(indices));
index = indices(localIndex);
[row,column] = ind2sub(size(result.BicoherenceSquared),index);
peak = struct('BicoherenceSquared',value,'F1',f(column),'F2',f(row), ...
    'SignificantCount',nnz(significant));
end

function [regular,meta] = prepareRegularSeries(data)
options = bispectralDefaults(data);
options.InputPolicy = 'prepare';
options.Interpolate = 'always';
options.InterpolationMethod = 'linear';
options.SampleInterval = [];
options.DetrendMethod = 'none';
options.Standardize = false;
[regular,meta] = bispectralPreprocess(data,options);
meta.OriginallyIrregular = ...
    meta.RelativeSpacingDeparture > meta.StrictSpacingRelativeTolerance;
meta.RegularGridReconstructed = meta.WasInterpolated;
meta.RegularizationPolicy = [ ...
    'Always reconstruct the median-spacing grid before strict analysis; ', ...
    'OriginallyIrregular uses the strict 10 ppm spacing tolerance.'];
end

function external = externalPreprocessingMetadata(preparation,requestedWindow, ...
        spanSamples,effectiveWindow)
if isfield(preparation,'Trend')
    preparation = rmfield(preparation,'Trend');
end
external = struct( ...
    'PerformedOutsideBispectralGUI',true, ...
    'CoordinateUnit','kyr', ...
    'PreparationFunction','bispectralPreprocess', ...
    'PreparationPolicy','prepare', ...
    'OriginallyIrregular',preparation.OriginallyIrregular, ...
    'RegularGridReconstructed',preparation.RegularGridReconstructed, ...
    'Regularization',preparation, ...
    'LOWESS',struct( ...
        'Method','MATLAB smoothdata lowess', ...
        'RequestedWindowKyr',requestedWindow, ...
        'SpanSamples',spanSamples, ...
        'EffectiveSupportWidthKyr',effectiveWindow, ...
        'EffectiveWidthConvention','(SpanSamples-1) * regular sample interval', ...
        'EdgePolicy',[ ...
            'Use smoothdata lowess with only the observations available near ', ...
            'each endpoint; no reflection, padding, or extrapolation is added.'], ...
        'AppliedToResult',false));
end

function [detrended,trend,spanSamples,effectiveWindow] = ...
        removeLowessTrend(regular,windowKyr)
dt = median(diff(regular(:,1)));
spanSamples = max(3,round(windowKyr/dt));
if mod(spanSamples,2) == 0, spanSamples = spanSamples+1; end
spanSamples = min(spanSamples,size(regular,1)-mod(size(regular,1)+1,2));
trend = smoothdata(regular(:,2),'lowess',spanSamples);
detrended = [regular(:,1),regular(:,2)-trend];
effectiveWindow = (spanSamples-1)*dt;
end

function fraction = longPeriodPowerFraction(y,dt,cutoffPeriod)
y = double(y(:))-mean(y,'omitnan');
nfft = 2^nextpow2(numel(y));
spectrum = fft(y,nfft);
power = abs(spectrum(2:floor(nfft/2)+1)).^2;
frequency = (1:floor(nfft/2))'/(nfft*dt);
total = sum(power);
if total <= 0
    fraction = NaN;
else
    fraction = sum(power(frequency <= 1/cutoffPeriod))/total;
end
end

function data = readTwoColumn(path)
data = readmatrix(path);
if ~isnumeric(data) || ~isreal(data) || size(data,2) < 2
    error('Acycle:BispectralValidation:InvalidInput','Not a two-column file: %s',path);
end
data = double(data(:,1:2));
end

function row = emptySummaryRow()
row = struct( ...
    'Case',"",'SourceFile',"",'StartKyr',NaN,'EndKyr',NaN, ...
    'OriginalN',NaN,'RegularN',NaN,'SampleIntervalKyr',NaN, ...
    'OriginalMaxSpacingDeparturePercent',NaN,'LargestGapFactor',NaN, ...
    'OriginallyIrregular',false,'RegularGridReconstructed',false, ...
    'LOWESSSamples',NaN,'EffectiveLOWESSWindowKyr',NaN, ...
    'RawLongPeriodPowerFraction',NaN,'DetrendedLongPeriodPowerFraction',NaN, ...
    'RawPeakBicoherenceSquared',NaN,'RawPeakF1PerKyr',NaN,'RawPeakF2PerKyr',NaN, ...
    'DetrendedPeakBicoherenceSquared',NaN,'DetrendedPeakF1PerKyr',NaN, ...
    'DetrendedPeakF2PerKyr',NaN,'DetrendedSignificantVisibleTriads',NaN, ...
    'DetrendedSignificantComputedTriads',NaN, ...
    'GlobalSurrogateThreshold',NaN,'ThresholdComparison',"", ...
    'InferenceMethod',"", ...
    'FWERConfidenceLevel',NaN,'InferenceFamily',"", ...
    'InferenceFamilyTriadCount',NaN, ...
    'ComputedAxisBinCount',NaN, ...
    'FrequencyBinStride',NaN,'RayleighResolutionPerKyr',NaN, ...
    'ComputedAxisFrequencyMinimumPerKyr',NaN, ...
    'ComputedAxisFrequencyMaximumPerKyr',NaN,'SurrogateType',"", ...
    'AcceptedSurrogates',NaN,'IAAFTIterations',NaN, ...
    'IAAFTSpectralTolerance',NaN,'SurrogateAttempts',NaN, ...
    'RejectedSurrogates',NaN,'RandomSeed',NaN, ...
    'MaximumAcceptedIAAFTSpectralError',NaN);
end

function writeStudyNotes(path,summary,settings)
lines = { ...
    '# LR04 and CENOGRID bispectral validation'; ...
    ''; ...
    '## Analysis choices'; ...
    ''; ...
    '- Ages and all frequency units are kyr and kyr^-1.'; ...
    '- Every interval is explicitly reconstructed on its median-spacing linear grid before strict FFT analysis. OriginallyIrregular and RegularGridReconstructed are reported separately.'; ...
    sprintf('- The explicit LOWESS window is %g kyr. Raw/regularized results are retained as a sensitivity control.',settings.LOWESSWindowKyr); ...
    sprintf(['- Colored maps use an explicit frequency mesh and a 1:1 x/y ', ...
        'plot ratio. With the default strongest-value masks, weak values are ', ...
        'transparent and retained |B|/b^2 values use white-to-red colors; ', ...
        '100%% retention restores the complete red-white-blue map. The visible ', ...
        'maximum is %.4g kyr^-1.'],settings.PlotFrequencyMaximum); ...
    sprintf(['- Primary detrended inference uses %d accepted IAAFT ', ...
        'maximum-statistic surrogates at 95%% FWER confidence over the ', ...
        'fixed finite observed triads in the complete computed principal ', ...
        'domain, %d IAAFT ', ...
        'iterations, and accepted relative Fourier-amplitude error <= %.6g.'], ...
        settings.NumSurrogates,settings.IAAFTIterations, ...
        settings.IAAFTSpectralTolerance); ...
    sprintf('- Case-specific deterministic random seeds are %d through %d.', ...
        settings.RandomSeed,settings.RandomSeed+height(summary)-1); ...
    sprintf(['- MaxFrequencyBins is %d. The summary records actual computed ', ...
        'axis-bin count, native-bin stride, Rayleigh resolution, and computed ', ...
        'frequency maximum for every case; display interpolation is not ', ...
        'treated as numerical frequency resolution.'],settings.MaxFrequencyBins); ...
    '- Maximum plotted frequency does not alter estimation or the fixed complete-computed-domain FWER family.'; ...
    ['- Every raw and primary Overview passed two recomputed 2pi-MTM-curve ', ...
        'and metadata checks, exact title/label checks, actual plot-box and ', ...
        'frequency alignment, colorbar placement, extension-free title, ', ...
        'and independent retain-fraction/cutoff QA before saving.']; ...
    ''; ...
    '## Data-driven preprocessing assessment'; ...
    ''};
for ii = 1:height(summary)
    if summary.OriginallyIrregular(ii)
        spacingText = 'original spacing exceeded strict 10 ppm regularity';
    else
        spacingText = 'original spacing already met strict 10 ppm regularity';
    end
    reconstructionText = 'median-spacing grid reconstructed';
    if ~summary.RegularGridReconstructed(ii)
        reconstructionText = 'median-spacing grid was not reconstructed';
    end
    reduction = summary.DetrendedLongPeriodPowerFraction(ii) / ...
        summary.RawLongPeriodPowerFraction(ii);
    lines{end+1} = sprintf(['- %s: %s; %s (dt %.6g kyr; largest gap %.2f x dt). ', ...
        'Power at periods >=%g kyr changed from %.4f to %.4f (ratio %.3f); ', ...
        'the fixed FWER family contained %d finite computed triads. ', ...
        'Features at periods near or shorter than the %.6g kyr largest ', ...
        'original gap are interpolation-sensitive.'], ...
        summary.Case(ii),spacingText,reconstructionText, ...
        summary.SampleIntervalKyr(ii), ...
        summary.LargestGapFactor(ii),settings.LOWESSWindowKyr, ...
        summary.RawLongPeriodPowerFraction(ii), ...
        summary.DetrendedLongPeriodPowerFraction(ii),reduction, ...
        summary.InferenceFamilyTriadCount(ii), ...
        summary.LargestGapFactor(ii)*summary.SampleIntervalKyr(ii)); %#ok<AGROW>
end
lines = [lines; {''; ...
    sprintf(['The %g kyr LOWESS result is the primary detrending sensitivity ', ...
        'analysis, not an anti-aliasing filter. Endpoint windows use only ', ...
        'available observations, without padding or reflection. Interpret ', ...
        'features near record edges and the LOWESS transition cautiously. ', ...
        'The regularized, non-LOWESS result shows which features depend on ', ...
        'this choice.'], ...
        settings.LOWESSWindowKyr)}];
notes = strjoin(lines,newline);
writeText(path,sprintf('%s\n',notes));
end

function writeText(path,textValue)
fileId = fopen(path,'w');
if fileId < 0, error('Acycle:BispectralValidation:WriteText','Cannot write %s',path); end
cleanup = onCleanup(@()fclose(fileId));
fprintf(fileId,'%s',textValue);
end

function closeFigure(fig)
if ~isempty(fig) && isgraphics(fig,'figure'), close(fig); end
end

function outputDirectory = createUniqueValidationDirectory(outputParent)
timestamp = char(datetime('now','Format','yyyyMMdd_HHmmss_SSS'));
baseName = ['LR04_CENOGRID_validation_',timestamp];
for index = 1:9999
    if index == 1
        candidate = fullfile(outputParent,baseName);
    else
        candidate = fullfile(outputParent,sprintf('%s_%d',baseName,index));
    end
    if isfile(candidate) || isfolder(candidate)
        continue
    end
    [ok,message] = mkdir(candidate);
    if ok && isempty(message)
        outputDirectory = candidate;
        return
    end
    if ~ok
        error('Acycle:BispectralValidation:CreateOutput','%s',message);
    end
end
error('Acycle:BispectralValidation:CreateOutput', ...
    'Could not create a unique validation directory in %s.',outputParent);
end

function tag = lowessTag(windowKyr)
number = sprintf('%.12g',windowKyr);
number = strrep(number,'-','m');
number = strrep(number,'.','p');
number = strrep(number,'+','');
tag = ['lowess',number,'kyr'];
end

function validateSettings(settings)
positiveScalars = {'LOWESSWindowKyr','PlotFrequencyMaximum','MaxFrequencyBins', ...
    'NumSurrogates','IAAFTIterations','IAAFTSpectralTolerance'};
for ii = 1:numel(positiveScalars)
    value = settings.(positiveScalars{ii});
    if ~(isnumeric(value) && isscalar(value) && isfinite(value) && value > 0)
        error('Acycle:BispectralValidation:InvalidSettings', ...
            '%s must be a positive finite scalar.',positiveScalars{ii});
    end
end
integerScalars = {'MaxFrequencyBins','NumSurrogates','IAAFTIterations','RandomSeed'};
for ii = 1:numel(integerScalars)
    value = settings.(integerScalars{ii});
    if ~(isnumeric(value) && isscalar(value) && isfinite(value) && ...
            value == round(value))
        error('Acycle:BispectralValidation:InvalidSettings', ...
            '%s must be a finite integer.',integerScalars{ii});
    end
end
if settings.NumSurrogates < 19
    error('Acycle:BispectralValidation:InvalidSettings', ...
        'NumSurrogates must be at least 19.');
end
if settings.NumSurrogates > 99999
    error('Acycle:BispectralValidation:InvalidSettings', ...
        'NumSurrogates must not exceed 99999.');
end
if settings.MaxFrequencyBins < 16
    error('Acycle:BispectralValidation:InvalidSettings', ...
        'MaxFrequencyBins must be at least 16.');
end
if settings.IAAFTSpectralTolerance > 1
    error('Acycle:BispectralValidation:InvalidSettings', ...
        'IAAFTSpectralTolerance must lie in (0,1].');
end
end

function settings = parseSettings(settings,varargin)
if isempty(varargin), return, end
if mod(numel(varargin),2) ~= 0
    error('Acycle:BispectralValidation:InvalidOptions','Use name/value pairs.');
end
names = fieldnames(settings);
for ii = 1:2:numel(varargin)
    index = find(strcmpi(char(varargin{ii}),names),1);
    if isempty(index)
        error('Acycle:BispectralValidation:UnknownOption', ...
            'Unknown option: %s',char(varargin{ii}));
    end
    settings.(names{index}) = varargin{ii+1};
end
end
